libvips/resample/resize.c
Hi John,
The tilecache created during the resize operation uses the [7th](https://github.com/jcupitt/libvips/blob/master/libvips/resample/resize.c#L160) temporary image but only 6 are allocated.
This fix prevents a memory leak and an occasional segfault.
(PR is for the master branch as I can't find a 7.42 branch for bug fixes.)
=> Ensure resize operation has the required number of temp images

libvips/foreign/openslide2vips.c
Almost all pixels emitted by OpenSlide are either fully transparent or fully opaque.  Add a special case for opaque pixels to avoid the multiplication/division, and restructure both special cases to compile to a single shift + OR + bswap.  On my system, this produces a 1.95x speedup in user time for `vips openslideload CMU-1.svs out.v` and a 1.28x speedup for `vips openslideload CMU-1.mrxs --level 2 out.v`.
=> Improve performance of openslide2vips argb2rgba()

libvips/foreign/foreign.c, libvips/include/vips/foreign.h
This commits adds a vips_foreign_is_a_buffer() method, similar to
vips_foreign_is_a().
=> Add vips_foreign_is_a_buffer() method

libvips/foreign/openslide2vips.c
Inspired by #261 I ran sharp's leak testing script and, thanks to the forthcoming addition of openslide support, discovered a small leak in openslide2vips which this PR fixes:
```
==2994== 24 bytes in 1 blocks are definitely lost in loss record 2,709 of 6,526
==2994==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2994==    by 0xCE94610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==2994==    by 0xCEAD56D: g_strjoinv (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==2994==    by 0xC76B2CB: readslide_new (openslide2vips.c:380)
==2994==    by 0xC76B892: vips__openslide_read (openslide2vips.c:502)
==2994==    by 0xC76BEBB: vips_foreign_load_openslide_load (openslideload.c:131)
```
I also received the following report about dzsave but …
=> Fix small memory leak in openslide loader

libvips/foreign/magick2vips.c
As `read_free` can be called twice since fc5a4a9, this change is required for GraphicsMagick compatibility. It avoids failing the [assert](http://sourceforge.net/p/graphicsmagick/code/ci/default/tree/magick/error.c#l359) in `DestroyExceptionInfo` on the second occasion.
=> Ensure expected signature in ExceptionInfo before destroy

configure.ac, libvips/foreign/foreign.c, libvips/foreign/jpegsave.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vipsjpeg.h
These features are available now in mozjpeg and support for the extension parameter API will be added to the next release of libjpeg-turbo.
This PR adds `./configure` time detection by looking for the new `J_BOOLEAN_PARAM` enum type of `jpeglib.h`, which will also be present in libjpeg-turbo >= 1.5.
It also uses a runtime guard via the new `jpeg_c_x_param_supported` methods. I believe libjpeg-turbo is hoping to support overshoot deringing first, then add other features later as they are optimised to use intrinsics.
If JPEG extension parameters are not available, which will be for the majority of users right now until libjpeg-turbo updates roll out, the new features that use them silently have no effect. Would you prefer these options to fail if unavailable at runtime?
Here are some …
=> Expose JPEG extension parameters. Support trellis quantisation, deringing and scan optimisation.

libvips/Makefile.am
Ensure `introspect` is built before `g-ir-scanner` tries to run it.  This should fix MacPorts' Buildbot builds on OS X 10.8 (which run with `make -j8`).
=> Fix .gir file dependencies

libvips/foreign/magick2vips.c
Hey, I was having some issues with converting animated gifs, in that my app was leaking like a sieve, after a couple of days of digging into it, think i finally tracked it down to this diff.
As far as i can tell, calling ```DestroyImage``` only destroys the first image in the list, and leaves the rest around, whereas ```DestroyImageList``` goes through all of them and covers the single image case as well.
The repro for the leak i was trying to fix is fairly simple, just magick_open an animated gif and save it, should be fairly noticeable.
=> Fix memory leak in magick free

acinclude.m4
Python3 and python2 compatible print call in configure script.
=> acinlude.m4: python3 compatible print

libvips/include/vips/vips.h
I think it has to be ifdef–no? Couldn't get it to compile otherwise (XCode 7)
=> fixing typo, should be Ifdef

cplusplus/VImage.cpp, cplusplus/include/vips/VError8.h, cplusplus/include/vips/VImage8.h, cplusplus/include/vips/vips8
Hi John,
C++ name mangling means the `libvips-cpp-42.dll` file created via mingw can't be used with Node on Windows as MSVC is the only supported compiler on that platform.
This means I need to build the vips8 C++ bindings as a DLL using MSVC, but to do this I had to make a couple of syntactic changes and conditionally add MS-only `__declspec` modifiers to the public API.
Cheers,
Lovell
=> Enable compilation of vips8 C++ bindings with MSVC

libvips/arithmetic/max.c, libvips/arithmetic/min.c, libvips/colour/LabQ2sRGB.c, libvips/include/vips/util.h
Hi John,
Profiling `vipsthumbnail` using `callgrind` reveals there are a lot of `isnan` and `isinf` checks during the building of colour translation look-up tables at start-up time. GCC and clang don't/can't optimise these and will instead call the libc implementation.
In my tests, switching to the builtin versions improves `vipsthumbnail` perf by ~4% with -O2 and by ~9% with -O3 (I guess the builtins become non-compliant with IEEE754 when optimised).
I read (somewhere, can't find it now) that the builtin functions are up to 7x faster than libc on ARM CPUs.
Results, with timing and instruction counts, for running the command follow:
$ vipsthumbnail [2569067123_aca715a2ee_o.jpg](https://github.com/lovell/sharp/blob/master/test/fixtures/2569067123_aca715a2ee_o.jpg)
Cheers,
Lovell
**Before, …
=> Use gcc/clang isnan and isinf builtin functions, where available

libvips/resample/shrinkh.c
Hi John,
Based on `callgrind` testing, these changes seem to grant the compiler (gcc 5.3 in my tests) use of the vector unit with `vips_shrinkh`.
When compiled with -O3 this allows `vips_shrinkh_gen` to run with ~25% fewer instructions, so the `vips_shrink` operation as a whole runs up to about 10% faster.
I'm seeing the performance of a more typical shrink+affine reduction improved by ~5%.
Below are the `callgrind` results of running a 2x shrink operation on a WebP image 100x.
Current code, using -O2, `vips_shrinkh_gen` and `vips_shrinkv_gen` are about the same.
```
6,191,513,100  ???:0x000000000002ca10 [/usr/lib/x86_64-linux-gnu/libwebp.so.5.0.1]
5,729,485,600  ???:0x000000000000d140 [/usr/lib/x86_64-linux-gnu/libwebp.so.5.0.1]
2,634,604,404  resample/shrinkh.c:vips_shrinkh_gen …
```
=> Allow compiler to use vector unit with vips_shrinkh for ~25% boost

libvips/resample/affine.c, libvips/resample/bicubic.cpp, libvips/resample/mapim.c, libvips/resample/presample.h, libvips/resample/templates.h
Hi John,
There were a few copies of the `FAST_PSEUDO_FLOOR` macro, so these all now reference the same version and, if available, will use the ~7% faster `__builtin_floor` function.
`vips_afffine_gen` already uses `vips_interpolate_get_method` so the `interpolate` instance isn't required by the `interpolate` method. I've run the sharp unit tests over this to ensure all the interpolators still work.
It looks like register starvation was starting to affect `vips_interpolate_bicubic_interpolate` so there's now one less temp variable in there.
The result is ~10% less time spent in `vips_affine_gen` and ~5% less time spent in `vips_interpolate_bicubic_interpolate`.
I see an overall improvement to `vips_affine` of ~3%.
Cheers,
Lovell
Before:
```
4,444,599,308  ???:decode_mcu …
```
=> Small perf improvements to vips_affine + bicubic

libvips/colour/LabQ2sRGB.c
This change makes `vips_LabQ2sRGB_line` follow the pattern of the pixel-based conversion functions such as `vips_col_scRGB2sRGB_8` by only building the LUTs when first used.
More importantly, this change reduces the start-up time of the `vips`, `vipsthumbnail` etc. command line tools by ~20ms. For trivial operations on small images, where a LAB to sRGB conversion is not used, I see a ~3x speed-up.
=> Performance: only build LAB to sRGB look-up tables if needed

libvips/foreign/magick2vips.c
Fixes a compiler warning and not much else.
=> Remove = in #define

libvips/conversion/premultiply.c
This also updates the macro name to make it more descriptive and consistent with its equivalent in `vips_unpremultiply`.
This makes `vips_premultiply` ~10% faster plus prevents a segfault in the (very uncommon) case of 2 bands plus alpha channel.
Example instruction count before:
```
204,704,256  ???:vips_premultiply_gen [/usr/local/lib/libvips.so.42.4.0]
176,529,416  ???:vips_cast_gen [/usr/local/lib/libvips.so.42.4.0]
```
and after:
```
176,529,416  ???:vips_cast_gen [/usr/local/lib/libvips.so.42.4.0]
119,760,384  ???:vips_premultiply_gen [/usr/local/lib/libvips.so.42.4.0]
```
=> Ensure premultiply fast-path for RGBA is used

configure.ac
The pkg-config test requires >= 0.30.0, but the warning message asks for >= 0.40.0.
=> Fix required poppler-glib version in AC_MSG_WARN()

configure.ac, libvips/foreign/foreign.c, libvips/foreign/vips2webp.c, libvips/foreign/webp.h, libvips/foreign/webpsave.c, libvips/include/vips/enumtypes.h, libvips/include/vips/foreign.h, libvips/iofuncs/enumtypes.c, test/test_formats.sh
* Switch to WebP Advanced Encoding API to allow access to `WebPConfig`
* Add `preset` enumerable to tune WebP lossy compression for certain types of images
* Add `smart_subsample` switch that greatly reduces color bleeding from 4:2:0 subsampling
* Add `near_lossless` switch that allows preprocessing in lossless mode using `Q` option
* Add `alphaQ` option similar to `Q` that allows to reduce alpha palette in lossy mode
=> Use WebP Advanced Encoding API and make it tunable

acinclude.m4
This uses a combination of the old giflib4 and the new giflib5 checks.
Fixes #435.
=> Fix configure check for giflib4

test/test_threading.sh, test/test_thumbnail.sh
Both scripts were not using the $vips variables required to use vips from the source directory instead of from the system.
=> Fix threading and thumbnail tests without make install

libvips/foreign/foreign.c, libvips/foreign/jpegsave.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vipsjpeg.h
This allows to choose from 8 predefined quantization tables when libvips is compiled against mozjpeg.
Tuning the quantization table helps to improve file size in the higher quality range and avoid artefacts in the lower range.
One example would be to use table 3 at quality 75, where it consistently compresses better than any of the other tables, but to use table 2 for a "retina" image compressed at qualities below 50, where it performs better at keeping color accurate and avoiding banding in flat areas and gradients.
I have also added some advice on which table to choose, based on limited personal observations, which is probably much better than blindly having to choose a numerical index ;-)
=> Add mozjpeg quant_table option to jpegsave

.travis.yml, libvips/foreign/webpsave.c, test/test_formats.sh
This switches from the current backport ppa to testing against the system provides libwebp-0.1.3 on Travis CI. As a consequence the lossless test in `test_formats.sh` was dropped, because it's not supported on that old version.
I've also fixed the default value for webpsave `alpha_q` to be 100 instead of 0. I had assumed that would be already handled by defining the `VIPS_ARG_INT`, but that doesn't seem to be the case.
=> Test system webp on Travis CI and fix alpha_q default value

libvips/foreign/vips2jpeg.c
This was only ut in for debugging which quant_table is used in the `JCP_FASTEST` vs. `JCP_MAX_COMPRESSION` profile and should've never been committed.
This is a fixup for #434.
=> Remove jpegsave default quant_table debug print

.gitignore, bootstrap.sh, configure.ac, m4/python.m4
* Vendor the pygobject `m4/python.m4` to fix wrong multiarch exec paths
* Fix several problems with gi path warnings
* Disable vips7 SWIG bindings for python3 (see #334)
* Warn if the gi module could not be loaded
* Fix `VIPS_LIBDIR` being `"NONE"` without explicit `--prefix`
For details see #438 and the individual commit messages.
=> Fix Python and GI path detection problems

test/test_foreign.py
I had to write the buffer to a temp file and then load that because there is no `radload_buffer`
=> Add unit test for radiance buffer save

bootstrap.sh
Not all versions of echo support `-n` so using it is not portable. One example where this does not work is bash in sh mode on Mac OS X. Replaced with `printf` which the BSD manpage suggest to use for portability.
=> Use printf instead of non-portable echo -n in bootstrap.sh

.travis.yml, README.md
This re-enables travis ci to trigger for all branches, so it can be used to check the build on forks without having to modify `.travis.yml`.
The reason given for the change was the failing build badge, so this changes the build badge to monitor the master branch instead.
=> Re-enable Travis CI builds on all branches

libvips/foreign/dzsave.c, test/test_foreign.py
This adds support for enabling ZIP compression and setting the deflate compression level when using dzsave with the zip container type.
The general consensus is, that there's no use in compressing already compressed image types like JPEG. However this is not true if the file itself is not well compressible by JPEG, as is the case with (mostly) blank tiles.
In my tests I am saving between 15-25% on the total ZIP size depending on the JPEG compression level used and how many solid areas the source image contains. Also see my comments in #352.
Example using the [Blue Marble Next Generation](http://visibleearth.nasa.gov/view.php?id=73909) image, which contains some nearly solid areas like oceans and Antarctica:
```sh
for i in `seq 0 9`; do
echo -n "$i "
time vips dzsave world-86400x43200.tif …
```
=> Vips dzsave zip compression support

libvips/foreign/dzsave.c
Don't strip the extension at the end until you know you are saving to a file
=> Allow for output directory names containg a dot

libvips/foreign/dzsave.c
This fixes a duplicate root path for the vips-properties.xml, when either the zoomify or goolgle layouts are used.
Example: `foo/foo/image-properties.xml` becomes `foo/image-properties.xml`
This resolves issue #460.
=> Fix dzsave vips-properties path for non-dz layout

cplusplus/VImage.cpp, cplusplus/include/vips/VImage8.h
Hi John, this PR updates the assignment operator overloads introduced in 28efdf1 to work with MSVC by moving them "outside" the class and therefore enable DLL exporting.
Without this, MSVC generates the following rather cryptic error:
```
error C2487: '+=': member of dll interface class may not be declared with dll interface
```
There's also a bit of an MSVC annoyance in that when returning by reference, the __declspec bit has to go before the type, so what I ended up doing was ensuring a consistent modifier order across all exported functions, which looks a bit neater.
=> cplusplus - move assignment operators outside class, enables DLL exporting

libvips/foreign/svgload.c
Hi John, was the 200 value an otherwise arbitrary limit? Increasing it to 250 will provide support for "real world" SVG files such as the following unnecessary preamble exported by Adobe Illustrator:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg ...
```
https://raw.githubusercontent.com/sandstorm-io/sandstorm/master/icons/key.svg
=> Increase SVG buffer check length by 50 bytes

libvips/resample/reduceh.cpp, libvips/resample/reducev.cpp
GCC v6+ is starting to warn about the use of `NULL` as a sentinel value in C++ sources (as `NULL` is considered a zero value rather than a null pointer).
```
reduceh.cpp: In function 'int vips_reduceh_build(VipsObject*)':
reduceh.cpp:509:8: warning: missing sentinel in function call [-Wformat=]
NULL ) )
^
reduceh.cpp:514:41: warning: missing sentinel in function call [-Wformat=]
VIPS_DEMAND_STYLE_THINSTRIP, in, NULL ) )
^
reducev.cpp:790:40: warning: missing sentinel in function call [-Wformat=]
VIPS_DEMAND_STYLE_FATSTRIP, in, NULL ) )
^
reducev.cpp: In function 'int vips_reducev_build(VipsObject*)':
reducev.cpp:873:8: warning: missing sentinel in function call [-Wformat=]
NULL ) )
^
reducev.cpp:897:9: warning: missing sentinel in function call [-Wformat=]
NULL ) )
^
```
=> Silence 'missing sentinel' warnings in GCC v6+

libvips/Makefile.am
This patch adds the `--c-include` option to the `g-ir-scanner` options in the build system. It enables the main C header, `vips/vips.h`, to be identified in the GIR. This is needed by bindings generated for Vala.
=> Add C header to GIR file

cplusplus/include/vips/VImage8.h
Hi John, I spotted this small API gotcha in the C++ bindings, mostly harmless but worth fixing even though it's a breaking change.
=> cplusplus: offset coords are int rather than double

libvips/resample/thumbnail.c
Fix regression from https://github.com/jcupitt/libvips/commit/260180197d234c7a200c735350c29cc367184c88#diff-91d7263682820594ab7f1b7c450778c1R272.
Closes https://github.com/jcupitt/libvips/issues/735.
=> vips_thumbnail: Fix SVG/PDF input (#735)

libvips/foreign/svgload.c
Hi John,
Since the changes for #688, made available in libvips v8.5.7+, SVG images without `width` and `height` attributes can no longer be scaled using the `dpi` and `scale` parameters of `vips_svgload`.
For example, the following commands all produce the same 620x472 output:
```sh
$ curl -O https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg
$ vips copy Test.svg Test.png
$ vips copy Test.svg[dpi=150] Test-dpi-150.png
$ vips copy Test.svg[scale=2] Test-scale-2.png
$ vipsheader *.png
Test-dpi-150.png: 620x472 uchar, 4 bands, srgb, pngload
Test.png: 620x472 uchar, 4 bands, srgb, pngload
Test-scale-2.png: 620x472 uchar, 4 bands, srgb, pngload
```
This PR is a proposed solution for this problem.
When `dpi`/`scale` are set to non-default values, two pairs of `rsvg_handle_set_dpi` / …
=> Correct scaling of SVG input without width and height attributes

.travis.yml
It look as though the Travis build for macOS is failing because brew errors
out when it finds pkg-config and automake have already been installed.
=> Remove additional install of pkg-config and automake from macOS CI

libvips/arithmetic/abs.c, libvips/arithmetic/add.c, libvips/arithmetic/boolean.c, libvips/arithmetic/complex.c, libvips/arithmetic/deviate.c, libvips/arithmetic/divide.c, libvips/arithmetic/find_trim.c, libvips/arithmetic/getpoint.c, libvips/arithmetic/hist_find.c, libvips/arithmetic/hist_find_indexed.c, libvips/arithmetic/hist_find_ndim.c, libvips/arithmetic/hough_circle.c, libvips/arithmetic/hough_line.c, libvips/arithmetic/invert.c, libvips/arithmetic/linear.c, libvips/arithmetic/math.c, libvips/arithmetic/math2.c, libvips/arithmetic/max.c, libvips/arithmetic/measure.c, libvips/arithmetic/min.c, libvips/arithmetic/multiply.c, libvips/arithmetic/profile.c, libvips/arithmetic/project.c, libvips/arithmetic/relational.c, libvips/arithmetic/remainder.c, libvips/arithmetic/round.c, libvips/arithmetic/sign.c, libvips/arithmetic/stats.c, libvips/arithmetic/subtract.c, libvips/arithmetic/sum.c
PR adds `(out)` for out parameters. Most functions take a single Image input and those have been marked as `(method)`. Functions that take two Image inputs, e.g. add, remain as functions, rather than methods. There are also a few `(array length=n)` additions.
=> Update GObject introspection annotations for /libvips/arithmetic

configure.ac, libvips/resample/affine.c, libvips/resample/interpolate.c, libvips/resample/mapim.c, libvips/resample/quadratic.c, libvips/resample/reduce.c, libvips/resample/reduceh.cpp, libvips/resample/reducev.cpp, libvips/resample/resize.c, libvips/resample/shrink.c, libvips/resample/shrinkh.c, libvips/resample/shrinkv.c, libvips/resample/similarity.c, libvips/resample/thumbnail.c
#741 
`resample.h` had to be added to `headers` in `configure.ac` for the functions to appear in the GIR. I assumed that `resample.h` was part of the public VIPS8 API.
There are also a couple of C++ files: reducev.cpp and reduceh.cpp. These look as though they have public functions, but aren't part of `instrospection_sources` in `configure.ac`. I've not made any changes to the build system for these two files.
=> Update GObject introspection annotations for libvips/resample directory

libvips/resample/resize.c
Hi John, you'll be pleased to learn that sharp will soon be moving to use `vips_resize` (instead of 4x separate `vips_shrink*` and `vips_reduce*` operations in duplicate code).
One feature of sharp missing from libvips is this faster, more accurate integral nearest-neighbour upsampling path using `vips_zoom`.
See https://github.com/lovell/sharp/issues/752 for the background.
=> Faster and more accurate integral nearest-neighour upsampling

libvips/arithmetic/math2.c
Hi John, this small change improves performance of the attention smartcrop operation by ~30% (tested with gcc 5.4 on Ubuntu 16.04).
Before:
```
20,393,996,328  /build/glibc-bfm8X4/glibc-2.23/math/../sysdeps/ieee754/dbl-64/e_pow.c:__ieee754_pow_sse2 [/lib/x86_64-linux-gnu/libm-2.23.so]
14,434,340,104  libvips/conversion/extract.c:vips_extract_band_buffer [/usr/local/lib/libvips.so.42.8.0]
9,370,217,274  /build/glibc-bfm8X4/glibc-2.23/math/../sysdeps/ieee754/dbl-64/e_exp.c:__exp1 [/lib/x86_64-linux-gnu/libm-2.23.so]
8,487,829,504  /build/glibc-bfm8X4/glibc-2.23/math/../sysdeps/ieee754/dbl-64/e_atan2.c:__ieee754_atan2_avx [/lib/x86_64-linux-gnu/libm-2.23.so]
8,267,273,599  libvips/colour/LabQ2sRGB.c:vips_col_sRGB2scRGB_8 [/usr/local/lib/libvips.so.42.8.0]
6,164,317,372 …
```
=> Prefer ~10x faster sqrt instead of pow when y=0.5

libvips/conversion/smartcrop.c
Hi John, this prevents large reductions from generating `GLib-GObject-WARNING **: value "0.000453" of type 'gdouble' is invalid or out of range for property 'sigma' of type 'gdouble' gaussblur: parameter sigma not set`.
```sh
$ vips smartcrop 10000x10000.v out.v 1 1
```
=> Smartcrop: clamp sigma to avoid out of range warnings

libvips/conversion/smartcrop.c
Hi John, given only the luminance band from the LCH colourspace conversion is used, I think we can instead use LAB here. If so, this provides a fairly big performance improvement (independent of #809) by avoiding the costly atan2 conversion to polar coords.
Before:
```sh
$ time vips smartcrop 10000x10000.v out.v 100 10000
real    0m18.665s
user    0m18.424s
sys     0m0.272s
```
```
36,788,404,121  ???:vips_extract_band_buffer [/usr/local/lib/libvips.so.42.8.0]
15,708,124,763  /build/glibc-bfm8X4/glibc-2.23/math/../sysdeps/ieee754/dbl-64/e_atan2.c:__ieee754_atan2_avx [/lib/x86_64-linux-gnu/libm-2.23.so]
14,953,036,753  ???:vips_col_sRGB2scRGB_8 [/usr/local/lib/libvips.so.42.8.0]
12,562,353,888  ???:vips_ifthenelse_gen [/usr/local/lib/libvips.so.42.8.0]
12,262,089,216 …
```
=> Smartcrop: ~19% speedup by getting luminance from LAB instead of LCH

libvips/colour/LabQ2sRGB.c
Hi John, I'm increasingly seeing sRGB to scRGB colour conversion appear when profiling so thought I'd take a look at what could be done to help.
At the moment, for every pixel converted, there is a glib shared library call to `g_once`.
Here's the `-O3` timing/profile of converting 100m pixels:
```sh
$ time vips colourspace 10000x10000.v out.v scrgb
real    0m8.697s
user    0m1.672s
sys     0m1.208s
```
```
5,000,000,003  ???:vips_col_sRGB2scRGB_8 [/usr/local/lib/libvips.so.42.8.0]
2,301,250,004  ???:vips_sRGB2scRGB_gen [/usr/local/lib/libvips.so.42.8.0]
1,200,211,873  /build/glibc-bfm8X4/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:__memcpy_avx_unaligned [/lib/x86_64-linux-gnu/libc-2.23.so]
```
This PR moves the two `GOnce` instances up a scope level, which then …
=> Colour: ~20% speedup for sRGB to scRGB pixel conversion

libvips/conversion/premultiply.c, libvips/conversion/unpremultiply.c
...and as a bonus improves the precision of unpremultiply for float/double input.
This change removes 3 instructions per pixel for premultiply, 5 instructions per pixel for unpremultiply. The following timings are using gcc at `-O3` with a 100m pixel input image.
Premultiply before:
```sh
$ time vips premultiply 10000x10000-4.v premultiplied.v
real    0m12.538s
user    0m0.848s
sys     0m1.348s
```
```
3,401,460,000  ???:vips_premultiply_gen [/usr/local/lib/libvips.so.42.8.0]
1,600,211,922  /build/glibc-bfm8X4/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:__memcpy_avx_unaligned [/lib/x86_64-linux-gnu/libc-2.23.so]
```
Premultiply after:
```sh
$ time vips premultiply 10000x10000-4.v premultiplied.v
real    0m12.715s
user    0m0.716s
sys     0m1.532s
```
``` …
```
=> (Un)premultiply: ~10-15% speedup by matching clipped alpha type with IN/OUT

libvips/foreign/vipspng.c
Hi John, commit https://github.com/jcupitt/libvips/commit/cbd9fad040c1358587d4323eded3cc7e83971ac8 added a manual call to `png_set_interlace_handling` to avoid a warning from libpng.
However, this results in the internal `num_rows` member of the opaque `png_structp` not being correctly set and so interlaced PNG input fails when using libvips 8.6.0-beta with libpng 1.6.x.
This appears to be a limitation of the current libpng so probably needs addressing upstream.
https://github.com/glennrp/libpng/blob/f23b41d7b1acc2b95be18a776c3cc4453af6598a/pngread.c#L729-L730
This PR returns things to the current "stable" behaviour of working, albeit with the existing ignorable warning.
=> libvips v8.6.0-beta: ensure interlaced PNG input works with libpng16

libvips/foreign/vips2jpeg.c
Hi John, this PR prevents a 15024 byte leak when an error occurs on the input side and the output is a JPEG buffer.
It's possible the `term_destination` clean-up function is not called, which means the internal `dbuf` is never "stolen" and therefore never freed.
```
==6382== 15,024 bytes in 1 blocks are possibly lost in loss record 5,935 of 5,960
==6382==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6382==    by 0x4C2FDEF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==6382==    by 0x9E8E565: vips_dbuf_minimum_size (dbuf.c:76)
==6382==    by 0x9E73CFA: empty_output_buffer (vips2jpeg.c:707)
==6382==    by 0xB3E035B: jpeg_start_compress (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==6382==    by 0x9E73FC1: write_vips …
```
=> Prevent ~15KB leak for JPEG buffer output error

libvips/conversion/composite.cpp
Hi John, this quick fix uses the same approach as #668.
```
composite.cpp: In function 'int vips_composite_base_build(VipsObject*)':
composite.cpp:983:39: warning: missing sentinel in function call [-Wformat=]
if( vips_addalpha( in[i], &x, NULL ) )
^
composite.cpp:1035:39: warning: missing sentinel in function call [-Wformat=]
composite->compositing_space, NULL ) )
^
```
=> composite.cpp: silence 'missing sentinel' warnings in GCC v6+

cplusplus/include/vips/VImage8.h
Silences this warning seen when compiling with MSVC.
> cplusplus\include\vips\VImage8.h(477): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
=> Make size_t to int cast explicit to prevent compiler warning

libvips/foreign/svgload.c
Hi John, I noticed the other day that there is currently no `is_a` check in the SVG file loader.
```sh
$ file what-is-it
what-is-it: SVG Scalable Vector Graphics image
$ head -3 what-is-it
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.2" baseProfile="tiny" xml:id="svg-root" width="100%" height="100%"
viewBox="0 0 480 360" xmlns="http://www.w3.org/2000/svg"
$ vipsheader what-is-it
vipsheader: VipsForeignLoad: "what-is-it" is not a known file format
```
This PR adds a new internal method so that the above now works:
```sh
$ vipsheader what-is-it
what-is-it: 480x360 uchar, 4 bands, srgb, svgload
```
Rather than massively re-order functions in the `svgload.c` source file, I've declared the existing `vips_foreign_load_svg_is_a_buffer` function before using it in the proposed …
=> Add is_a support to SVG file class loader

libvips/convolution/sharpen.c
I noticed that the `radius` parameter has been deprecated, and it's not listed in the parameter list anymore, so I also removed its mention from the documentation.
=> Remove mention of deprecated radius parameter in vips_sharpen()

libvips/conversion/bandjoin.c
I don't know if this is used for function introspection (and in this case if it's related to https://github.com/jcupitt/ruby-vips/issues/168), but I saw all other functions having `(out)` specified like this.
=> Add "(out)" to "out" parameter in vips_addalpha()

libvips/include/vips/foreign.h
The value is derived by oring all the filter flags:
0x08 | 0x10 | 0x20 | 0x40 | 0x80 == 0xf8
The value was also checked against PNG_ALL_FILTERS in png.h of libpng 1.6.34.
=> Fix wrong value for VIPS_FOREIGN_PNG_FILTER_ALL

libvips/iofuncs/cache.c
_From the commit message:_
Both `vips_cache_drop_all` and `vips_cache_print` acquire `vips_cache_lock` on entry, but `vips_cache_drop_all` calls `vips_cache_print` internally if `vips__cache_dump` is true, leading to a deadlock situation.
This commit solves the issue using one further level of indirection and a new `vips_cache_print_nolock` function.
---
I tried adhering to the existing code style, but I'm not sure if I got this right as I only started working with libvips last week.
=> Fixed deadlock in vips_cache_drop_all if vips__cache_dump is true

libvips/foreign/svgload.c
Hi John, this was originally reported in https://github.com/lovell/sharp/issues/1222
The example [image.svg](https://raw.githubusercontent.com/nikwen/sharp-demo/master/image.svg) makes heavy use of Gaussian blur filters and takes 3.5s to render via `rsvg-convert`.
```sh
$ time rsvg-convert image.svg >output.png
real    0m3.351s
user    0m3.320s
sys     0m0.032s
```
A similar operation using the `vips` command line (latest master) takes ~10x longer.
```sh
$ time vips copy image.svg output.png
real    0m38.264s
user    0m37.548s
sys     0m0.304s
```
The SVG loader currently [defines a cache](https://github.com/jcupitt/libvips/blob/5176b4a17ec9ca5151f1b8b503b2f237f3c83b27/libvips/foreign/svgload.c#L387) to typically hold three 30000x16 tiles, but this doesn't appear to be enough to prevent …
=> Reduce SVG re-renders with taller cache tiles

libvips/conversion/composite.cpp, libvips/create/perlin.c, libvips/foreign/rawsave.c, libvips/foreign/tiff2vips.c, libvips/foreign/vipspng.c, libvips/include/vips/type.h, libvips/include/vips/util.h, libvips/iofuncs/generate.c, libvips/iofuncs/image.c, libvips/iofuncs/mapfile.c, libvips/iofuncs/memory.c, libvips/iofuncs/util.c, libvips/mosaicing/im_lrmerge.c, libvipsCC/include/vips/VDisplay.h, libvipsCC/include/vips/VError.h, libvipsCC/include/vips/VImage.h, libvipsCC/include/vips/VMask.h, libvipsCC/include/vips/vips
These are various fixes in order to build the library with my custom Visual Studio 2017 project.
My custom project is in this repository: https://github.com/angelmixu/libvips-vs2017
The explanation for the fixes are in the commit's comment.
Feel free to suggest, modify or comment them.
=> Fixes for being able to build libvips in Visual Studio 2017 with an external project

libvips/foreign/vips2webp.c
Hi John, when libvips is compiled with support for libwebpmux, writing WebP images with `strip=FALSE` can currently fail silently in `vips_webp_add_metadata`.
This was discovered whilst investigating https://github.com/lovell/sharp/issues/1242, which this change fixes.
=> Ensure WebP can add metadata when compiled with libwebpmux

libvips/conversion/composite.cpp
This references issue https://github.com/jcupitt/libvips/issues/892
I've added optional x, y coordinates to the `vips_composite` functions. 
This uses `vips_embed` to resize all the images to the size of the target image, placed at the specified x, y coordinate. Example usage:
```
vips composite2 in0.png in1.png out.png over --x "400" --y "20"
```
=> Adding x,y arguments to vips_composite

libvips/conversion/bandjoin.c
Docs for [`vips_addalpha()`](http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-addalpha) are missing from the website. I don't know if this PR fixes that, but that's the only difference I saw from the other function documentations.
=> Fix missing vips_addalpha() docs

libvips/convolution/convi.c
This fixes posterization in the vector path for convolution caused by a typo in commit eefb2dad980c12922ad15d987be7c4b42a44d5cf.
The fix was suggested by @jcupitt.
Fixes #1001.
=> Fix convolution vector path posterization

.travis.yml
* Download pyvips version specified by PYVIPS_VERSION environment variable and run its test suite after the C based tests
* Fix the macOS build and use the latest Xcode/macOS versions
* Disable homebrew updates for more predictable builds
* Sync dependencies between linux and osx targets
Fixes #742.
=> Run pyvips test suite on Travis CI

.travis.yml
This should make it easier to see which tests cause problems.
This is related to #1005 and should help with troubleshooting the random segfaults on macOS.
=> Run pytest verbose on Travis CI

configure.ac, libvips/foreign/pforeign.h, libvips/foreign/pngsave.c, libvips/foreign/vipspng.c, test/test_formats.sh
This adds support for saving 8-Bit one band palette based PNG images with palette based alpha channel (often called PNG8+Alpha).
The image is first converted to sRGBA and then quantized using [libimagequant](https://pngquant.org/lib/) controlled by the `colors`, `Q` and `dither` params.
* By default quantization is disabled and it must be enabled by specifying the `palette` flag.
* The `colours` parameter specifies the maximum number of colors (2-256).
* The `Q` parameter controls how lossy the quantization should be, similar to JPEG.
* The `dither` parameter controls how much Floyd-Steinberg dithering is used.
All of the code that deals with quantization is in the method `quantise_image` which writes back two `VipsImage` objects: a 1-band grayscale image where the pixel values correspond …
=> 8-Bit PNG Quantization Support

libvips/foreign/exif.c
vipsheader -a path/to/foo.jpg
...
exif-ifd2-ExifVersion: Exif Version 2.21 (Exif Version 2.21, Undefined, 4 components, 4 bytes)
...
exif-ifd3-InteroperabilityIndex: N (N, ASCII, 2 components, 2 bytes)
exif-ifd3-InteroperabilityVersion: 40/1 1/1 58/100 (40,  1, 0.58, Rational, 3 components, 24 bytes)
The above two tag name are incorrect, should be:
exif-ifd3-GPSLatitudeRef: N (N, ASCII, 2 components, 2 bytes)
exif-ifd3-GPSLatitude: 40/1 1/1 58/100 (40,  1, 0.58, Rational, 3 components, 24 bytes)
Signed-off-by: Water Liu <water@yunify.com>
=> Should use exif_tag_name_in_ifd() instead of exif_tag_get_name()

libvips/arithmetic/getpoint.c
vips_getpoint() doesn't unref VipsArea.
=>  Fix missing area unref in getpoint()

libvips/colour/icc_transform.c
Hi John, this PR fixes a small memory leak on the "happy path" in the `vips_icc_is_compatible_profile` function added recently in commit https://github.com/jcupitt/libvips/commit/e686614f2ce4a130ecb8f264d100410ac55a7507
```
==26991== 72 bytes in 3 blocks are indirectly lost in loss record 4,012 of 5,782
==26991==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==26991==    by 0xB492177: ??? (in /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8)
==26991==    by 0xB499CD4: cmsOpenIOhandlerFromMem (in /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8)
==26991==    by 0xB49B544: cmsOpenProfileFromMemTHR (in /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8)
==26991==    by 0x9EB1B90: vips_icc_is_compatible_profile (icc_transform.c:1261)
==26991==    by 0x9F34258: …
```
=> Fix 72 byte leak when ICC profile is compatible

ChangeLog, configure.ac, libvips/foreign/exif.c
we were using g_str_to_ascii(), but it was only added in glib 2.40
see https://github.com/libvips/libvips/issues/1117
=> fix build on older glibs

cplusplus/include/vips/VImage8.h
This pull request adds an is_null check, which is then used in VImage.
The usefulness is described in #1132.
=> Add is_null check to VImage

libvips/foreign/tiff2vips.c
Some image formats allow pixel data to be stored in premultiplied form. This PR adds a new `VIPS_META_PREMULTIPLIED` meta field and sets it for TIFF images based on the `EXTRASAMPLE_ASSOCALPHA` value.
See https://github.com/lovell/sharp/issues/1445 for a good example of this.
With this change:
```sh
$ vipsheader -a test_white_1_main.tiff
test_white_1_main.tiff: 800x800 uchar, 4 bands, srgb, tiffload
width: 800
height: 800
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 11.811
yres: 11.811
filename: test_white_1_main.tiff
vips-loader: tiffload
n-pages: 1
icc-profile-data: 3144 bytes of binary data
xmp-data: 18323 bytes of binary data
photoshop-data: 6536 bytes of binary data
resolution-unit: in
orientation: 1
premultiplied: 1
```
```sh
$ vipsheader -a …
```
=> Unpremultiply TIFF with associated alpha channel

.travis.yml
See https://changelog.travis-ci.com/oclint-is-removed-from-mac-builds-79270
=> Remove unnecessary uninstall of oclint

libvips/colour/CMYK2XYZ.c, libvips/colour/XYZ2CMYK.c
If HAVE_LCMS2 is not defined, VipsImage is not declared in both
CMYK2XYZ and XYZ2CMYK source files.
#1197
=> Fix compilation error when lcms has not been found

libvips/foreign/vipspng.c
Hello, this is a small addition to the PNG header reader to attach the bit depth of the palette, if any, as metadata.
By way of example, using test images from http://www.schaik.com/pngsuite/pngsuite_bas_png.html we can now differentiate 4-bit vs 8-bit palette:
```sh
$ vipsheader -a basn3p04.png
basn3p04.png: 32x32 uchar, 3 bands, srgb, pngload
width: 32
height: 32
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 2.834
yres: 2.834
filename: basn3p04.png
vips-loader: pngload
palette-bit-depth: 4
```
```sh
$ vipsheader -a basn3p08.png
basn3p08.png: 32x32 uchar, 3 bands, srgb, pngload
width: 32
height: 32
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 2.834
yres: 2.834
filename: basn3p08.png
vips-loader: pngload …
```
=> PNG loader: attach palette bit depth, if any, as metadata

cplusplus/VError.cpp, cplusplus/VImage.cpp, cplusplus/include/vips/VError8.h, cplusplus/include/vips/VImage8.h, cplusplus/include/vips/VInterpolate8.h
The functions `has_alpha()` and `copy_memory()` were missing from the C++ binding.
=> Add missing C++ functions

libvips/conversion/cast.c
Commit https://github.com/libvips/libvips/commit/07d58f81b3c6e6f034e5bb84f6023d1d08ac0061 on the `master` branch changed the way floats are cast to ints.
Using the following test image:
```sh
$ curl -O https://raw.githubusercontent.com/lovell/sharp/master/docs/image/sharp-logo.svg
```
The following resize operation works as expected:
```sh
$ vips resize sharp-logo.svg sharp-logo.png 0.9
```
However the following, casting to and from float values, results in what appear to be rounding-error artefacts:
```sh
$ vips cast sharp-logo.svg sharp-logo.v float
$ vips resize sharp-logo.v sharp-logo.png 0.9
```
My best guess is that this relates to the introduction of logic to floor the (possibly negative) float value in the `CAST_FLOAT_INT` macro before an implicit truncate. When I remove the use …
=> Avoid artefacts when casting from float to int (master)

libvips/foreign/pforeign.h, libvips/foreign/vips2webp.c, libvips/foreign/webpsave.c
Skal from the team that maintains libwebp at Google opened https://github.com/lovell/sharp/issues/1545 to note that its `method` parameter is not currently made available.
His recommendation is to expose this as the more appropriately-named `reduction_effort` (I agree with this as the use of `method` is far too overloaded).
Hence this PR, which adds and documents a new `reduction_effort` parameter to the WebP savers.
Running the following commands:
```sh
$ vips copy input.jpg reduction_effort.default.webp
$ vips copy input.jpg reduction_effort.0.webp[reduction_effort=0]
$ vips copy input.jpg reduction_effort.4.webp[reduction_effort=4]
$ vips copy input.jpg reduction_effort.6.webp[reduction_effort=6]
```
results in:
```
365958 reduction_effort.0.webp
253340 reduction_effort.4.webp
253340 …
```
=> Expose libwebp reduction_effort parameter

libvips/iofuncs/image.c
`vips_image_temp_name` can be called concurrently and thus the usage of the static `name` array is not thread safe.
`-fsanitize=address` spuriously complains about `heap-buffer-overflow` errors due to this.
---
**A different issue follows, but I thought I'd might write it up already.**
I recently upgraded all dependencies of a project I'm working on from libvips 8.6.4 to 8.7.2, as well as Alpine from 3.7 to 3.8 (i.e. an upgrade of liborc from 0.4.27 to 0.4.28).
Ever since then I'm seeing spurious, seemingly racy, segmentation faults.
This PR is the first thing that came out of the bug hunt. :smile: 
I personally suspect that this is due to liborc, as I can see the following if I compile with `-fsanitize=address`:
```
AddressSanitizer:DEADLYSIGNAL …
```
=> vips_image_temp_name: Fixed race condition / heap-buffer-overflow

libvips/colour/profile_load.c
The recent change to the `master` branch introduced by #1194 leaks the ICC profile data:
```
==28548== 2,429 bytes in 1 blocks are definitely lost in loss record 6,423 of 6,523
==28548==    at 0x483774F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28548==    by 0x9424650: g_malloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.1)
==28548==    by 0x8FCD261: vips_malloc (memory.c:176)
==28548==    by 0x8FD7722: vips__file_read (util.c:754)
==28548==    by 0x8FD77D6: vips__file_read_name (util.c:787)
==28548==    by 0x8EFBA6D: vips_profile_load_build (profile_load.c:137)
==28548==    by 0x8FBEF18: vips_object_build (object.c:367)
==28548==    by 0x8FCAA57: vips_cache_operation_buildp (cache.c:866)
==28548==    by 0x8FD074C: vips_call_required_optional …
```
=> Ensure ICC profile data is freed after use (master)

libvips/colour/profile_load.c
Hello, to add to #1214, this prevents the new static profiles leaking and a use-after-free.
=> profile_load: ensure once-ness, prevent profile use-after-free (master)

libvips/resample/thumbnail.c
For example, this allows us to thumbnail any page from a PDF-formatted memory buffer:
```cpp
auto buffer_thumb = vips::VImage::thumbnail_buffer(blob, 200,
vips::VImage::option()->set("option_string", "[page=1]"));
```
Resolves #1147.
=> vips_thumbnail_buffer: add optional option_string argument (#1147)

configure.ac, libvips/foreign/magick.c, libvips/foreign/magick.h, libvips/foreign/magicksave.c
Hi,
Looks like I made `vips_magicksave` working with GM. There is what I've done:
1. GraphicsMagick has [its own implementation](http://hg.code.sf.net/p/graphicsmagick/code/file/c38fc0e3e465/wand/magick_compat.c#l315) of `ImportImagePixels` in the wand part. Since it's pointlessly to link the wand part, I just borrowed the code. Using `SetImagePixels` may be a more effective solution, but the current one is better than nothing.
2. GM doesn't have `UndefinedPixel` value. Since we anyway will throw an error in `vips_foreign_save_magick_build ` if the band format is unsupported, I've decided that we can safely assign `CharPixel` to `magick->storage_type` at the start. Maybe, we even can remove this assignation, but I'm not sure about this.
3. Also, GM doesn't have `ImagesToBlob` function. …
=> vips_magicksave for GraphicsMagick

libvips/iofuncs/threadpool.c
ThreadPool was allocating memory for threads and pools locally to the image object. As that image could not be freed from cache, for each sink operation done for that image the code was creating new pools and threads without freeing the previous ones. So, the more number of threads and the more operations the bigger the hidden leak was. The fix just creates the objects not locally to that image, and also free them in its destroy functions
=> Fix for hidden leaks in ThreadPool

libvips/resample/thumbnail.c
The current master does not succeed in thumbnailing a WebP image: 
```
wget https://www.gstatic.com/webp/gallery/4.webp
vipsthumbnail 4.webp \
--size 128 \
-o tn_%s.jpg \
--eprofile srgb
``` 
```
vipsthumbnail: unable to thumbnail 4.webp
webpload: no property named `scale'
```
Looks like a regression from: https://github.com/libvips/libvips/commit/22ba9106b5c671765d156719ae39e2582279ad04. This PR ensures that the parameter `shrink` is used instead of `scale`.
By the way,
The same WebP image as above generates the following warnings:
```
(vipsthumbnail:3859): VIPS-WARNING **: 17:27:43.555: webp2vips: not all frames have equal duration
(vipsthumbnail:3859): VIPS-WARNING **: 17:27:43.568: webp2vips: not all frames have equal duration
```
Perhaps the frames check here: …
=> Fix thumbnailing of a WebP image (master)

tools/vipsprofile
I don't know how to test this (I don't know or use libvips), so please give it a try.
Unless there is a typo, I'm pretty confident this cannot break anything, however I don't know yet if this the full change needed.
=> Convert tools/vipsprofile to Python 3+2

configure.ac, libvips/iofuncs/init.c
- Added a new environment variable called VIPS_MIN_STACK_SIZE, so that we can set the default stack size on some linux platforms e.g alpine, which uses musl and assumes a lower default stack size for embedded systems and containers. Some libraries are heavy users of a larger stack size such as poppler for PDF conversion.
- This is only set on linux and only if the environment variable "VIPS_MIN_STACK_SIZE" is set and is higher than the current stack size.
- We default to 2MB if we cannot parse this value.
- Added an error message with the current stack size.
- Tested on a PDF to png conversion that used around 90k stack for a recursive call, which is in connection to issue #1287
e.g it can be used like so, if you pass a string it defaults to 2MB otherwise the value passed.
``` …
```
=> provide an option to set the default stack size on linux

libvips/iofuncs/init.c
- This fixes set_stacksize which broke during the merge.
- I changed the condition on checking the current stack size with the minimum to make it easier to read as it was reversed.
- I added logging using g_info so we can see the actual size the OS has set.
```
G_MESSAGES_DEBUG=VIPS VIPS_MIN_STACK_SIZE=10m vips copy stackheavy.pdf x.png
VIPS-INFO: 16:13:41.937: current stack size is set to 10485760
```
=> fixes set_stacksize which broke during merge

libvips/foreign/vipspng.c
It looks like commit 57ce5a3 prevents interlaced PNG handling working with newer libpng versions.
```sh
$ vipsthumbnail interlaced.png
(vipsthumbnail:31018): VIPS-WARNING **: 22:37:46.939: bad adaptive filter value
vipsthumbnail: unable to thumbnail interlaced.png
```
This PR ensures the new call to `png_set_interlace_handling` occurs before the first call to `png_read_update_info`.
(Calling `png_set_interlace_handling` for non-interlaced PNG images appears to be OK, or at least is sensibly ignored internally by libpng.)
=> master: fix interlaced PNG input handling with newer libpng versions

libvips/foreign/heifload.c, libvips/foreign/heifsave.c, libvips/include/vips/enumtypes.h, libvips/include/vips/foreign.h, libvips/iofuncs/enumtypes.c
This implements an existing TODO in the heifsave code. I tested against the latest libheif master and avif branches and it appears to either work or return (expected) "unsupported" messages with the various values so this change will future-proof libvips against upstream libheif changes.
It also improves libheif error messaging and adds a couple of further suffixes that libheif can load.
=> heifsave: expose compression option

configure.ac, libvips/foreign/vips2webp.c
`WebPConfig.preprocessing` is not documented to have a value of 4 (https://github.com/webmproject/libwebp/blob/1.0.3/src/webp/encode.h#L130).
libwebp caller should use `WebPConfig.use_sharp_yuv` instead (introduced in 0.6.0: https://github.com/webmproject/libwebp/commit/4689ce16353fec7a7193c1ba4b6f5a9e0bce060e#diff-a602a176048dbf8f1c2da5fd9836d23dR345)
This PR replaces the usage of `WebPConfig.preprocessing` with `WebPConfig.use_sharp_yuv` and updates the minimal version of libwebp from 0.5.0 to 0.6.0.
The latter one, if necessary, can also be done by `if WEBP_ENCODER_ABI_VERSION >= 0x020e`.
To prove that those options are equivalent:
```
$ ./tools/vips webpsave /tmp/test.jpg /dev/stdout | md5sum
78a69451d5193430e6aadbefdebc30a1  -
$ ./tools/vips webpsave /tmp/test.jpg /dev/stdout …
```
=> [webp] Use well documented use_sharp_yuv option instead of preprocessing

cplusplus/include/vips/VImage8.h
Can be useful, for example:
```c++
std::vector<int> delays = image.get_array_int("delay");
for (int i : delays) {
std::cout << i << std::endl;
}
delays = {100, 200, 300, 400, 500};
image.set("delay", delays);
```
=> Support std::vector within the image_get/set_array_int functions

fuzz/jpegsave_buffer_fuzzer.cc, fuzz/pngsave_buffer_fuzzer.cc, fuzz/sharpen_fuzzer.cc, fuzz/thumbnail_fuzzer.cc, fuzz/webpsave_buffer_fuzzer.cc, libvips/iofuncs/generate.c
Hi. I have been tracking the project since the fuzzers are running in oss-fuzz.com to check if they are going well and I see you have already fixed several issues. Congrats.
You pushed a commit to skip large images using the macro FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION. This macro should be used to make code "friendly" to fuzzers, but only in very specific cases. For instance:
- to ignore failed checksums
- to make code deterministic (e.g. feed a random generator with the same seed value)
Any other issue with the fuzzers should be handled in the fuzzing functions themselves, rather than in the library. Otherwise, you will end up testing different execution paths when fuzzing than when using the library regularly, which is like testing two diverging versions of the same library.
This PR …
=> skip large images in the fuzzers not in the lib

.travis.yml, fuzz/test_fuzz.sh
This adds the undefined sanitizer [UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) to the fuzzing build in travis. Currently, [ClusterFuzz](https://github.com/google/oss-fuzz/blob/master/docs/clusterfuzz.md) is fuzzing libvips with both ASAN and UBSAN sanitizers enabled by default. But in travis only ASAN was specified.
This PR also fix the declaration of FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION (see https://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode). This must be a C macro instead of a env variable. This works in the oss-fuzz environemnt because they set CFLAGS correctly, but in travis we were missing this macro.
=> Add undefined sanitizer

fuzz/Makefile.am, fuzz/mosaic_fuzzer.cc, fuzz/smartcrop_fuzzer.cc
Two new fuzzers for high-level functions: vips_smartcrop and vip_mosaic. Smartcrop is interesting because is an optional operation for thumbnailing. Mosaic tests vips_merge and several subfunctions.
To fuzz vip_mosaic, it joins the original image with itself rotated 180 degrees and choose the join-coordinates and orientation randomly.
=> add fuzzers for vips_smartcrop and vip_mosaic

libvips/foreign/webp2vips.c
Before:
```sh
$ vips copy image-with-fake-header.webp out.jpg
(vips:27665): VIPS-WARNING **: 19:06:10.312: error in tile 0 x 0
webp2vips: unable to read pixels
```
After:
```sh
$ vips copy image-with-fake-header.webp out.jpg
webp: bad image dimensions
```
https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be
=>  WebP loader: verify upper limit on dimensions in header

libvips/foreign/vipspng.c
A [previous change](https://github.com/OrderMyGear/libvips/commit/8d7e03237a264001ca3427c361bd74d2a95d4a71) increased the max malloc when reading a png from a file. This PR applies the same configuration when reading from an in-memory buffer.
=> also set png max chunk malloc when reading buffer

.github/FUNDING.yml
Links the libvips GitHub repo to https://opencollective.com/libvips
=> Add link to opencollective

libvips/foreign/heifload.c, libvips/iofuncs/util.c
I stumbled across these whilst investigating a unrelated compiler bug/feature on an ARM64 machine (I had enabled the "-Werror" switch).
=> Silence a couple of GCC compiler warnings

libvips/Makefile.am
I added libvips to the official MINGW-packages here https://github.com/msys2/MINGW-packages/pull/5885 and added this patch to libvips in https://github.com/msys2/MINGW-packages/pull/5907 . So this is the upstream PR. Hope it's correct.
=> Fix dependency to introspect program on Windows MINGW

libvips/foreign/svgload.c
See the example in https://github.com/lovell/sharp/issues/1947, which at a density of 220 (scale = 3.055556) is currently incorrectly rendered at 64x42. With the change in this PR it correctly renders at 64x43.
=> Ensure SVG dimensions are rounded correctly when scaling or setting density via cairo

.travis.yml, ChangeLog, libvips/convolution/convsep.c, libvips/foreign/dzsave.c, libvips/foreign/heifsave.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vips2webp.c, libvips/iofuncs/header.c, libvips/resample/thumbnail.c, test/test-suite/test_foreign.py, test/test-suite/test_stream.py
If images are shared (ref count > 1), block changes to the set of metadata items on the image. These can cause crashes in highly threaded programs.
See https://github.com/lovell/sharp/issues/1986
=> block metadata changes on shared images

libvips/foreign/vips2webp.c
Expression could be truthy even when no `delay` was provided by user.
Now, the `delay_length` is 0 by default to avoid this situation.
=> fix: do not try to use "undefined" delay during WEBP animation save

libvips/iofuncs/init.c
In some environment, building fails because of backward memcpy().
=> Fix crash on backward memcpy()

libvips/foreign/exif.c, test/test-suite/test_foreign.py
If data in the orientation field `exif-ifd0-Orientation` is incorrect, ignore the orientation value.
Other software seems to be ignoring orientation value if it's not within an expected range, libvips was falling back to orientation 8.
=> Reset orientation if exif data is incorrect

autogen.sh
Linux distros will usually want to run configure separately so the script should respect their wishes. See also https://people.gnome.org/~walters/docs/build-api.txt
=> autogen.sh: Honor NOCONFIGURE

libvips/iofuncs/threadpool.c
Also backport the patch from https://bugzilla.gnome.org/show_bug.cgi?id=748530
=> Use g_get_num_processors() when GLib >= 2.48.1

configure.ac
Fall back to AM_WITH_EXPAT if it could not be found.
=> Prefer to find expat with pkg-config

libvips/iofuncs/init.c
The thread-safety problem was fixed in GLib 2.48.1.
See: https://bugzilla.gnome.org/show_bug.cgi?id=748474
=> Only call g_get_language_names when GLib < 2.48.1

configure.ac
libglib is always thread-enabled since v2.32.
=> Do not link against libgthread when GLib >= 2.32

cplusplus/include/vips/VImage8.h
This fixes #1595.
I tested it didn't break anything in my own environment but I was unable to locate unit tests related to VImage in the libvips repo (maybe I just missed them) so I'm deferring to Travis here ;)
=> allow null image as source for assignment and copy constructor

.travis.yml, suppressions/lsan.supp
This PR contains various Travis changes, including:
- Upgrade Python to version 3 as 2.7 is EOL now.
- Upgrade Clang to version 10 to fix the ASAN suppression parse errors.
- Fix the macOS build (that was broken due to a [non-working brew addon](https://changelog.travis-ci.com/xcode-11-3-1-xcode-11-2-1-xcode-11-1-and-xcode11-images-updated-142286)) by updating the base `osx_image` to `xcode11` (macOS 10.14).
- On macOS vips is now linked against libjpeg-turbo to fix [an assertion failure in `TestForeign::test_jpeg`](https://travis-ci.org/github/kleisauke/libvips/jobs/677783472#L3032-L3069).
=> Upgrade Python and Clang to latest version on Travis

libvips/iofuncs/util.c
There was a possible chance that `vips__temp_name` could generate the same filename twice if it is called concurrently.
This PR ensures that the serial increment is an atomic operation, similar to #1211.
=> Ensure vips__temp_name creates unique filenames

libvips/include/vips/memory.h, libvips/include/vips/util.h, libvips/iofuncs/memory.c, libvips/iofuncs/source.c, libvips/iofuncs/util.c, libvips/iofuncs/vips.c
This PR replaces the varargs in `vips_tracked_open` and `vips__open` with direct arguments.
Reading non-existent arguments may work on most native platforms, however on WASM it can fail. See for example:
<details>
```
=================================================================
==42==ERROR: AddressSanitizer: null-pointer-dereference on address 0x00000000 at pc 0x0042db9a bp 0x035acc30 sp 0x035acc3c
READ of size 4 at 0x00000000 thread T0
#0 0x42db9a in vips_tracked_open ../../vips/libvips/iofuncs/memory.c:385:9
#1 0x47a73d in vips_source_unminimise ../../vips/libvips/iofuncs/source.c:598:44
Address 0x00000000 is located in the shadow gap area.
SUMMARY: AddressSanitizer: null-pointer-dereference ../../vips/libvips/iofuncs/memory.c:386:9 in vips_tracked_open …
```
=> Remove use of varargs in vips_*_open

libvips/conversion/cast.c, libvips/foreign/heifload.c
```
cast.c:400:4: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
BAND_SWITCH_INNER( float,
^~~~~~~~~~~~~~~~~~~~~~~~~
cast.c:312:32: note: expanded from macro 'BAND_SWITCH_INNER'
INT( ITYPE, signed int, int, CAST_INT ); \
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
cast.c:225:10: note: expanded from macro 'CAST_FLOAT_INT'
q[x] = CAST( p[x] ); \
^~~~~~~~~~~~
cast.c:132:38: note: expanded from macro 'CAST_INT'
#define CAST_INT( X ) VIPS_MIN( (X), INT_MAX )
~~~~~~~~~~~~~~~^~~~~~~~~
/emsdk/upstream/emscripten/system/include/libc/limits.h:30:18: note: expanded from macro 'INT_MAX'
#define INT_MAX  0x7fffffff
^~~~~~~~~~
../../libvips/include/vips/util.h:55:34: note: expanded from macro 'VIPS_MIN'
#define VIPS_MIN( A, B …
```
=> Fix two compiler warnings

tools/vipsthumbnail.c
This patch assumes that the --delete option of vipsthumbnail has been ignored by intend. If that's the case it should be hidden, to not cost someone else an hour.
=> deprecate unused option --delete

libvips/foreign/magick7load.c
This change add the same `len > 10` check to the buffer-based logic to bring it in line with the existing file-checking logic:
https://github.com/libvips/libvips/blob/a592d99bb2e8a90be00121bf81cba338232183b5/libvips/foreign/magick7load.c#L752-L760
This prevents a call to `GetImageMagick` with a zero-length buffer, which crashes on FreeBSD.
=> Ensure magick7 buffer+file checks use consistent min length guard

libvips/resample/reduceh.cpp, libvips/resample/templates.h
We were seeing small displacements at some shrink factors because of
rounding in the mask size calcualation. This PR takes the rounding into
account when positioning the mask.
See https://github.com/libvips/libvips/pull/1592#issuecomment-626363031
=> revise kernel mask calculations

configure.ac, libvips/foreign/heifload.c
libheif will soon support h265 and/or AVIF (using the same API) so this PR allows libvips to look for either at compile time (see https://github.com/strukturag/libheif/pull/222 for the upstream change).
It also adds the newer `ftypavif` magic bytes (older AVIF images recycled the use of `ftypmif1`, but that is no longer recommended).
=> Improve compile-time libheif and runtime AVIF detection

libvips/foreign/spngload.c
Revised spngloader to be structurally similar to the libpng loader and the [test case](https://github.com/randy408/libspng/blob/master/tests/test_spng.h#L93) which guarantees the outputs will be identical for all possible color and bit depth combinations.
There might be some minor syntax errors, I haven't tried to build it.
=> Revise spngloader

libvips/foreign/spngload.c
The header has been moved for v0.6.0, `#include <spng/spng.h>` is the correct way to include the header from now on.
=> Update include path for libspng

libvips/foreign/spngload.c
The include path will stay the same for v0.6.0, sorry about that.
Reverts libvips/libvips#1694
=> Revert "Update include path for libspng"

libvips/foreign/vips2webp.c
When `min_size` has been explicitly set to minimise the size of an animated WebP image, also setting `allow_mixed` allows the encoder to evaluate and mix both lossy and lossless frames.
See https://github.com/webmproject/libwebp/commit/f29bf582df2349b29264e188670750b54850651e
The original claim is a 5% reduction, but I've seen anywhere from a ~2%-15% reduction depending on the input. There doesn't appear to be any increase in compression time and I've not seen any increase in file size so this seems like a safe setting.
=> Further reduce animated WebP image size by ~5% when min_size is set

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Added Issue Templates to the `.github` folder, Issue templates help to organize the project issues and support auto-labeling issues upon creation, which I think will save you loads of time.
Added Issue Template for 
- Bug Report
- Enhancement
- Question
Create Issue window should be like this (Taken from one of my projects): 
The issue created will have the corresponding label based on the template chosen.
=> Add Issue Templates with Auto Labeling

.gitignore, autogen.sh, configure.ac, doc/Makefile.am, libvips/include/vips/Makefile.am, libvips/iofuncs/Makefile.am, libvips/iofuncs/image.c, libvips/iofuncs/init.c, libvips/iofuncs/threadpool.c, libvips/iofuncs/vector.c, tools/vips.c
This PR fixes a few out-of-source build issues as mentioned in https://github.com/libvips/libvips/issues/1704#issuecomment-653933150. Here's a test script that I used to find these issues:
<details>
<summary>Test script</summary>
```bash
mkdir vips
curl -Ls https://github.com/libvips/libvips/releases/download/v8.10.0-beta1/vips-8.10.0-beta1.tar.gz | tar xzC vips --strip-components=1
#curl -Ls https://kleisauke.nl/vips-8.10.0-beta1.tar.gz | tar xzC vips --strip-components=1
cd vips
[ -f "libvips/include/vips/version.h" ] && echo "WARNING: version.h exists in tarball" 
srcdir=$PWD
mkdir build && cd build
../configure --prefix=$srcdir/inst/ --enable-debug
[ -f "$srcdir/libvips/include/vips/version.h" ] && [ -f "libvips/include/vips/version.h" ] && echo "WARNING: two version.h files detected, …
```
=> Fix out-of-source build issues

libvips/deprecated/vips7compat.c, libvips/include/vips/mosaicing.h, libvips/include/vips/vips7compat.h, libvips/mosaicing/global_balance.c, libvips/mosaicing/global_balance.h, libvips/mosaicing/im_avgdxdy.c, libvips/mosaicing/im_improve.c, libvips/mosaicing/im_lrcalcon.c, libvips/mosaicing/im_tbcalcon.c, libvips/mosaicing/lrmerge.c, libvips/mosaicing/lrmosaic.c, libvips/mosaicing/matrixinvert.c, libvips/mosaicing/pmosaicing.h, libvips/mosaicing/tbmerge.c, libvips/mosaicing/tbmosaic.c
Here's the `abi-compliance-checker` result between v8.9.2 and this branch:
https://kleisauke.nl/compat_reports/vips/8.9.2_to_vips-7-compat/compat_report.html
=> Add missing vips7 compat wrappers

.travis.yml, libvips/foreign/dzsave.c, suppressions/lsan.supp
This PR improves the CI by upgrading Ubuntu and GCC to the latest version available. The `-Wcast-function-type` warning is now enabled as discussed in https://github.com/libvips/libvips/pull/1697.
I had to add bash to the LSan suppression file, otherwise the build will somehow fail during `make check`.
=> Travis improvements

doc/extending.xml
vips-gmic doesn't appear to be a libvips repo anymore.
=> Update link for vips-gmic

libvips/colour/Lab2LCh.c
This is a proposal to remove the atan2 paths from the LAB to LCH conversion code as these incur a greater performance cost than the atan paths.
It's quite likely there was a good reason for using atan2 though, hence this is only a proposal.
Before:
```sh
$ time vips colourspace in.jpeg out.v lch
real	0m0.149s
user	0m0.205s
sys	0m0.032s
```
```
175,203,081  /build/glibc-5mDdLG/glibc-2.30/math/../sysdeps/ieee754/dbl-64/e_atan2.c:__ieee754_atan2_fma [/usr/lib/x86_64-linux-gnu/libm-2.30.so]
150,596,456  ???:vips_XYZ2Lab_line [/usr/local/lib/libvips.so.42.12.3]
46,873,827  ???:vips_col_scRGB2XYZ [/usr/local/lib/libvips.so.42.12.3]
41,210,169  ???:vips_Lab2LCh_line [/usr/local/lib/libvips.so.42.12.3]
33,169,488  /build/glibc-5mDdLG/glibc-2.30/math/w_atan2_compat.c:atan2 …
```
=> Performance: improve LAB to LCH conversion by ~30%

libvips/colour/XYZ2Lab.c
This PR switches the XYZ to LAB clipping from fmax/fmin maths library calls to instead use the simple ternary operators of `VIPS_CLIP`, which the compiler is able to heavily optimise.
Before:
```
150,596,456  ???:vips_XYZ2Lab_line [/usr/local/lib/libvips.so.42.12.3]
46,873,827  ???:vips_col_scRGB2XYZ [/usr/local/lib/libvips.so.42.12.3]
25,567,542  /build/glibc-5mDdLG/glibc-2.30/math/../sysdeps/x86_64/fpu/s_fmax.S:fmax [/usr/lib/x86_64-linux-gnu/libm-2.30.so]
25,567,542  /build/glibc-5mDdLG/glibc-2.30/math/../sysdeps/x86_64/fpu/s_fmin.S:fmin [/usr/lib/x86_64-linux-gnu/libm-2.30.so]
24,180,156  ???:vips_scRGB2XYZ_line [/usr/local/lib/libvips.so.42.12.3]
21,563,120  /build/glibc-5mDdLG/glibc-2.30/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms …
```
=> Performance: improve XYZ to LAB conversion by ~15%

libvips/colour/XYZ2Lab.c
This is a safer implementation of https://github.com/libvips/libvips/pull/1729, which switches the XYZ to LAB clipping from fmax/fmin maths library calls to instead use the simple ternary operators of VIPS_CLIP, which the compiler is able to heavily optimise, whilst also ensuring that NaN cannot creep through as an index into the cubed root lookup tables.
Before:
```
150,596,456  ???:vips_XYZ2Lab_line [/usr/local/lib/libvips.so.42.12.3]
46,873,827  ???:vips_col_scRGB2XYZ [/usr/local/lib/libvips.so.42.12.3]
25,567,542  /build/glibc-5mDdLG/glibc-2.30/math/../sysdeps/x86_64/fpu/s_fmax.S:fmax [/usr/lib/x86_64-linux-gnu/libm-2.30.so]
25,567,542  /build/glibc-5mDdLG/glibc-2.30/math/../sysdeps/x86_64/fpu/s_fmin.S:fmin [/usr/lib/x86_64-linux-gnu/libm-2.30.so]
24,180,156  ???:vips_scRGB2XYZ_line …
```
=> Performance: safely improve XYZ to LAB conversion by ~12%

libvips/colour/LabQ2sRGB.c, libvips/colour/scRGB2sRGB.c, libvips/include/vips/util.h
Hello, I think we can safely remove the `isinf` checks as the values are clipped before use (this represents about half of the savings).
The `CLIP` macro was missing an `else`, which I think was preventing the compiler from detecting this as a "clip a value" operation.
Out-of-gamut tracking is optional and at a slight cost so we can remove it where the return value is ignored.
Before:
```
225,846,621  ???:vips_col_scRGB2sRGB_8 [/usr/local/lib/libvips.so.42.12.3]
31,367,336  ???:vips_scRGB2sRGB_gen [/usr/local/lib/libvips.so.42.12.3]
```
After:
```
198,858,660  ???:vips_col_scRGB2sRGB_8 [/usr/local/lib/libvips.so.42.12.3]
31,365,334  ???:vips_scRGB2sRGB_gen [/usr/local/lib/libvips.so.42.12.3]
```
(All these timings are using gcc v9.2.1 with the `-O3` flag.)
=> Performance: improve scRGB to sRGB conversion by ~8%

libvips/foreign/magickload.c
The change in #1642 for magick v7 is also required in the magick v6 loader.
The sharp unit tests picked this up - I think the assertion in `GetImageMagick` has recently been backported.
=> Ensure magick buffer+file checks use consistent min length guard

libvips/iofuncs/sinkscreen.c
Noticed this while debugging https://github.com/libvips/libvips/issues/1792.
=> Fix a small memory leak in sinkscreen

cplusplus/VImage.cpp
I'm unsure if this is the _right_ way to solve this problem, but it does at least appear to prevent GType from being null and therefore triggering a segfault.
Example backtrace when the error occurs:
```
#0  0x00007ffff4c7b23a in g_type_value_table_peek () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff4c7d28f in g_value_init () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff51adbf7 in vips::VOption::set(char const*, vips::VObject) (this=this@entry=0x7fffd400a990, name=name@entry=0x7ffff51cd667 "in", value=...) at VImage.cpp:199
#3  0x00007ffff51af40d in vips::VImage::jpegsave(char const*, vips::VOption*) const (this=0x7fffdc90f8a8, filename=0x456f038 "out.jpg", options=<optimised out>) at ../cplusplus/include/vips/VImage8.h:122
#4  0x00007ffff522f5d1 in …
```
=> cplusplus: ensure VOption::set for VObject uses class to determine type

libvips/foreign/heifload.c
Ensures the first 4 bytes contain one of these two standard signatures, which (hopefully) all valid HEIF/HEIC/AVIF files will start with.
=> heifload: verify ISO BMFF/3GPP2 signature in is_a check

libvips/foreign/heifload.c
I found a valid example image with 0,0,0,28 as the first 4 bytes that was failing the new check :(
This PR is a clean-up of #1828 to convert the first 4 bytes to a 32-bit unsigned integer and then verify it is a multiple of 4, up to 32. Apologies for not doing it this way the first time around.
=> libheif: simplify is_a check of first 4 bytes

libvips/create/fractsurf.c
The optional parameters of `vips_gaussnoise` were incorrectly
passed within `vips_fractsurf`. This was discovered when running
the libvips testsuite on Windows 10 IoT (ARM32).
=> Fix test failure on ARM-based Windows

configure.ac, libvips/foreign/heifload.c
Requires libheif 1.4.0 for `heif_main_brand` but versions prior to that didn't support AV1. The approach in this PR should hopefully provide useful information for newer versions whilst degrading gracefully for older versions.
```sh
$ vipsheader -a test.heic | grep heif
vips-loader: heifload
heif-primary: 0
heif-compression: hevc
```
```sh
$ vipsheader -a test.avif | grep heif
vips-loader: heifload
heif-primary: 0
heif-compression: av1
```
=> heifload: expose heif-compression metadata

libvips/include/vips/object.h
By using [`G_VALUE_COLLECT_INIT`](https://developer.gnome.org/gobject/stable/gobject-Varargs-Value-Collection.html#G-VALUE-COLLECT-INIT:CAPS), according to [this upstream bug report](https://bugzilla.gnome.org/show_bug.cgi?id=603590) this could give a speed-up varying from 15% to 30% (measured with Callgrind).
=> Speed up VIPS_ARGUMENT_COLLECT_SET

libvips/iofuncs/image.c, libvips/iofuncs/util.c, libvips/iofuncs/vips.c, test/test-suite/test_foreign.py
MSB-ordered vips images were always byte swapped on both little- and big endian systems. And LSB-ordered vips images were loaded without a byte swap. This works correctly on little endian systems, but will not work on big endian systems where the byte swap must be done vice versa.
This PR ensures that the byte swap only takes place when needed. I also simplified the MSB-ordered image check (by using a helper) and moved the endianness check to compile time.
Resolves https://github.com/libvips/libvips/issues/1847.
(This PR targets the 8.10 branch, but I can change it to the master branch if necessary)
=> Ensure vipsload only byte swaps if necessary

libvips/foreign/webp2vips.c
A possible fix for https://github.com/lovell/sharp/issues/2341#issuecomment-738726237
=> webpload: ensure first frame is not blended

libvips/resample/bicubic.cpp, libvips/resample/reduceh.cpp, libvips/resample/reducev.cpp
This PR is a split-off from https://github.com/libvips/libvips/pull/1769, targeting the [`8.10`](https://github.com/libvips/libvips/tree/8.10) branch.
It fixes two small bugs that have been found with [jsummers/resamplescope](https://github.com/jsummers/resamplescope). The first commit (https://github.com/kleisauke/libvips/commit/49d8051e22d1b06f64a7f85b2c70db2497cece54) restores the round-to-nearest behaviour in `reduce{h,v}`, that was removed with PR https://github.com/libvips/libvips/pull/1592. This change can be observed in the following graphs:
| Before | After |
| :---: |  :---: |
| ![pd_vips_lanczos3-out.png](https://raw.githubusercontent.com/kleisauke/pyvips-issue-148/438bd3c0cd5c6a859c92d9df9bde956f48ffa20e/output-patch/pd_vips_lanczos3-out.png) | …
=> Resolve rounding issues in reduce

libvips/iofuncs/source.c
See https://github.com/lovell/sharp/issues/2494 for context.
=> Avoid seeking on bad file descriptors

configure.ac
This became unused after commit 346a9e7.
=> Remove redundant -lstdc++ configure check

libvips/foreign/vipspng.c
Similar to ce63fc1, but allowing libpng to be configured with `-DPNG_NO_READ` (i.e reading functionally disabled).
=> Exclude libpng load when building with libspng

libvips/colour/scRGB2BW.c, libvips/colour/scRGB2sRGB.c
As discussed in https://github.com/libvips/libvips/pull/1735#issuecomment-662439737. I didn't actually benchmark this, but it seems like a straightforward change (hence targeting the [`8.10`](https://github.com/libvips/libvips/tree/8.10) branch).
=> Switch VIPS_FCLIP to VIPS_CLIP in vips_scRGB2{BW,sRGB}

cplusplus/include/vips/VImage8.h, libvips/foreign/heifsave.c, libvips/foreign/jpegsave.c, libvips/foreign/pforeign.h, libvips/foreign/vips2jpeg.c, libvips/include/vips/enumtypes.h, libvips/include/vips/foreign.h, libvips/iofuncs/enumtypes.c, test/test-suite/test_foreign.py
As discussed in #1788, providing control over the use of chroma subsampling is a genuinely useful feature for still images created via libheif and is consistently supported by all of its encoder plugins.
This PR also adds a test for this now that the CI environment supports the AVIF format.
=> heifsave: add option to control chroma subsampling

libvips/foreign/svgload.c
libvips 8.10.x requires librsvg >=2.40.3
https://github.com/libvips/libvips/blob/8.10/configure.ac#L911
librsvg >=2.40.3 <2.51.0 includes `librsvg-features.h` for you
https://github.com/GNOME/librsvg/blob/2.40.3/rsvg.h#L259
...plus displays a deprecation warning when included directly
https://github.com/GNOME/librsvg/blob/2.40.3/librsvg-features.h.in#L2
librsvg >=2.51.0 removes it entirely
https://github.com/GNOME/librsvg/commit/b8c8756a0e8148afb2752acb62f06c57c917e4b4
=> svgload: remove was-deprecated, now-removed librsvg-features.h include

configure.ac, libvips/foreign/exif.c, libvips/iofuncs/buffer.c, libvips/iofuncs/cache.c, libvips/iofuncs/gate.c, libvips/iofuncs/init.c, libvips/iofuncs/threadpool.c
This does mean libvips 8.11.0 will drop support for RHEL6 (glib 2.28.8), but that reached EOL in November 2020.
=> Set minimum glib-2.0 dependency version of 2.40 (March 2014)

libvips/colour/profile_load.c, libvips/colour/wrap-profiles.sh
At runtime, this change decompresses colour profiles on the fly, as required. This reduces the shared library binary size (and therefore memory consumption) by 580KB, which at `-O2` represents a 17% saving.
Before:
```
5892519 profiles.c
3362808 libvips.so.42.13.0
```
After:
```
2360469 profiles.c
2782232 libvips.so.42.13.0
```
I'm unsure if the existing libvips test suite covers this, but the sharp tests do and they pass.
=> Compress fallback colour profiles with zlib (zopfli, via pigz)

libvips/foreign/tiffsave.c, libvips/foreign/vips2tiff.c
Hi, thank you for the quickly fix to #2128. And based on that I tried to make `--predictor` also available to ZSTD compression in tiff.
Before the commit, `vips` cannot set `predictor` on ZSTD compressed TIFF:
By this commit, `vips` now can set `predictor` on ZSTD TIFF:
=> Add tiff zstd predictor support

configure.ac, libvips/foreign/tiff.c, libvips/include/vips/object.h, libvips/iofuncs/error.c, libvips/iofuncs/image.c, libvips/iofuncs/init.c, libvips/iofuncs/mapfile.c, libvips/iofuncs/source.c, libvips/iofuncs/target.c, libvips/iofuncs/threadpool.c, libvips/iofuncs/util.c, libvips/iofuncs/vips.c, libvips/iofuncs/window.c, libvips/mosaicing/lrmerge.c, tools/vips.c, tools/vipsedit.c, tools/vipsheader.c, tools/vipsthumbnail.c
This PR cleanups `configure.ac` and a bunch of `#ifdef`'s. I used this renaming/remove strategy:
- `OS_WIN32` -> `G_OS_WIN32` (GLib definition when compiling for native Win32)
- `BINARY_OPEN` ->  `G_PLATFORM_WIN32` (GLib definition when compiling for native Win32 or Cygwin environments)
- `HAVE_G_WIN32_GET_COMMAND_LINE` -> `G_OS_WIN32`
- `VIPS_OS_DARWIN` -> <kbd>Delete</kbd> (appears to be unused)
This implies that the old definitions should no longer be used. Note that since the new definitions originates from GLib, it is necessary to include `vips/vips.h` prior to using them.
After this renaming, the following decoupled variables were removed from `configure.ac`:
- `vips_os_win32`
- `vips_binary_open`
- `have_g_win32_get_command_line`
- `vips_os_darwin`
Plus a couple of no longer …
=> Cleanup configure.ac and #ifdef's

libvips/foreign/vips2webp.c, test/test-suite/test_foreign.py
See:
https://bugs.chromium.org/p/webp/issues/detail?id=379
https://github.com/webmproject/libwebp/commit/09333097ed4fd474916edf723d1ad07f72a9ab4d
Resolves: https://github.com/weserv/images/issues/275.
=> vips2webp: force low duration frames to 100ms

configure.ac, libvips/resample/bicubic.cpp
Drop last remnant of dmalloc which was removed in version 7.28.0 with https://github.com/libvips/libvips/commit/ae8faf6597c738b5d8adf9f6c29fc7d02203ca44
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> drop last remnant of dmalloc

libvips/foreign/nsgifload.c
GIF dimensions are 16-bit unsigned according to https://en.wikipedia.org/wiki/GIF
As images may be truncated, memory is zero initialised.
=> nsgifload: check dimensions before memory allocation

libvips/foreign/nsgifload.c
As discussed in https://github.com/libvips/libvips/pull/2176
The GIF spec allows dimensions up to 65535 (16-bit unsigned), but this equates to 17GB/frame.
A common task is to convert animated GIF to animated WebP, and the latter supports dimensions up to 16383 (14-bit unsigned), so that seems like a sensible limit and equates to 1GB/frame.
Also makes the error message consistent with other loaders.
=> nsgifload: enforce maximum GIF dimensions of 16383

cplusplus/include/vips/VImage8.h
Useful for retrieving and setting background colour metadata, for example:
```c++
std::vector<double> background = image.get_array_double("background");
for (double i : background) {
std::cout << i << std::endl;
}
background = {255.0, 255.0, 255.0};
image.set("background", background);
```
=> C++: add set/get for an array of doubles

libvips/foreign/libnsgif/Makefile.am
```
libvips/foreign/libnsgif/Makefile.am:5: warning: whitespace following trailing backslash
```
(Split out from #2167)
=> Fix autogen warning

libvips/iofuncs/image.c, libvips/iofuncs/init.c, libvips/iofuncs/threadpool.c, libvips/iofuncs/vector.c
We can simplify these directives into one statement, instead of duplicating the `#else` branch.
(Split out from #2167)
=> Simplify preprocessor directives

cplusplus/Makefile.am
```
make[2]: Entering directory '/home/kleisauke/libvips/cplusplus'
( cd '/usr/share/doc/vips' && rm -f html )
rm: cannot remove 'html': Is a directory
make[2]: *** [Makefile:672: uninstall-htmlDATA] Error 1
```
(Split out from #2167)
=> Fix make uninstall with Doxygen

.gitignore
Somehow I sometimes encounter this file while committing, I think we could safely ignore this file.
(Split out from #2167)
=> gitignore: ignore .dirstamp files

.github/workflows/ci.yml
(We can always add it back later should it start to work again.)
=> CI: remove imagemagick as a dependency on macOS

.github/workflows/ci.yml, libvips/deprecated/vips7compat.c, libvips/include/vips/internal.h, libvips/include/vips/thread.h, libvips/include/vips/threadpool.h, libvips/include/vips/vips7compat.h, libvips/iofuncs/buffer.c, libvips/iofuncs/gate.c, libvips/iofuncs/init.c, libvips/iofuncs/sink.c, libvips/iofuncs/sinkdisc.c, libvips/iofuncs/sinkmemory.c, libvips/iofuncs/sinkscreen.c, libvips/iofuncs/threadpool.c, suppressions/tsan.supp
This PR revamps the threading system of libvips by using [GLib's threadpool](https://developer.gnome.org/glib/stable/glib-Thread-Pools.html) as discussed in #2038. This implementation allows reuse of already started threads.
Here is a brief overview of the related changes within this PR (see the individual commits for more details).
- Add `vips_threadpool_push` for inserting an new function into the list of tasks to be executed by libvips' thread pool.
- Add `vips__threadpool_shutdown` to shutdown the thread pool during [`vips_shutdown()`](https://libvips.github.io/libvips/API/current/libvips-vips.html#vips-shutdown).
- Add `vips__buffer_shutdown` to free the calculated pixel buffer cache early during [`vips_thread_shutdown()`](https://libvips.github.io/libvips/API/current/libvips-vips.htm …
=> Reuse threads by using the thread pool of GLib (#2038)

cplusplus/include/vips/VImage8.h, cplusplus/vips-operators.cpp, doc/function-list.xml
This PR adds the new JPEG XL load/save operations to the C++ binding and documentation, which were missed in PR #2212.
=> Update C++ binding and function list

configure.ac
This was noticed within the CI, see: https://github.com/libvips/libvips/runs/2599127347#step:12:417.
=> Only build libjxl as a loadable module when it can be found

libvips/iofuncs/source.c, libvips/iofuncs/target.c, libvips/iofuncs/util.c, libvips/iofuncs/vips.c
`G_PLATFORM_WIN32` is no longer defined for Cygwin, see:
https://github.com/GNOME/glib/blob/b4522e680cfe6288e52aba0e99131ef849263047/meson.build#L221-L226
This PR ensures that it remains compatible with Cygwin after commit https://github.com/libvips/libvips/commit/3ed50e0427f731803a7b41d02fea0e780837b53e.
=> Ensure compatibility with Cygwin

libvips/iofuncs/init.c
Hi,
I'm currently using libvips with my own application and I see a lots of possible leaks from libvips.
I know there is a debate whether we should spend time fixing the "possible" leaks or not.
Feel free to reject my pull request if it's not desired.
Note that most leaks are from GLib but at least someone is trying to fix them upstream, see https://gitlab.gnome.org/GNOME/glib/-/issues/2076.
I cloned the repository today so I'm up to date.
The following have been done before and after my patch:
- built libvips using `CFLAGS="-g -Wall" CXXFLAGS="-g -Wall" ./autogen.sh --enable-debug && make && sudo make install` on a fresh docker container based on ubuntu:hirsute image.
- built my test program using `clang `pkg-config --cflags vips` `pkg-config --libs vips` ./test.c`.
- ran valgind using …
=> Clean up more resources in vips_shutdown

libvips/foreign/svgload.c
Even if `rsvg_handle_render_cairo` failed, we should delete the Cairo context. Otherwise, the context will leak.
=> Delete Cairo context on rsvg_handle_render_cairo error

libvips/foreign/pdfiumload.c
Closes #2306 
This fixes the leak for my case but I'm not sure if `pdf->source` should be checked for NULL.
=> Unref source on vips_foreign_load_pdf_close

libvips/iofuncs/init.c
On RPM distribution
* /bin is a symlink to /usr/bin
* /lib is a symlink to /usr/lib
* /lib64 is a symlink to /usr/lib64
When /usr/bin/vips is used, plugins are search in /usr/lib64, as expected
```
$ strace vips dzsave test.svs abc 2>&1 | grep vips-modules
openat(AT_FDCWD, "/usr/lib64/vips-modules-8.11", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
```
When /bin/vips is used, plugins are search in /lib, , so of course are not found, which explain this problem
```
$ strace /bin/vips dzsave test.svs abc 2>&1 | grep vips-modules
openat(AT_FDCWD, "/lib/vips-modules-8.11", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```
Using this patch, this work
```
$ strace /bin/vips --version 2>&1 | grep vips-modules
openat(AT_FDCWD, "/lib64/vips-modules-8.11", …
```
=> use /lib64 instead of /lib when needed

configure.ac
Might help: https://github.com/libvips/libvips/issues/2317. Users may still opt-in with `--enable-modules` when building static libraries.
=> Disable modules by default when building static libraries

Makefile.am, configure.ac
In addition, this PR also adds support for the `--with-pkgconfigdir=` argument while configuring libvips. This can be useful for Windows where one wants the dynamic modules installed (and be found) in the `bin/` directory, while still preserving the location of the pkg-config files (see for e.g. commit https://github.com/libvips/build-win64-mxe/commit/365870359dde8c7b971617d348ae8de41f5f690f).
=> Use autoconf macros for pkgconf where possible

cplusplus/VImage.cpp
Avoids unnecessary resizes.
Found with clang-tidy's performance-inefficient-vector-operation
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> VImage: reserve vector before push_back loop

libvips/foreign/pforeign.h, libvips/foreign/pngsave.c, libvips/foreign/quantise.c, libvips/foreign/vipspng.c
This is a rather useful setting for control over the creation of palette-based PNGs (and other palette-based "future" image formats) as the performance varies hugely between the slowest and fastest speeds.
```sh
$ time vips copy in.jpg out.png[palette]
real	0m2.641s
user	0m2.609s
sys	0m0.020s
$ time vips copy in.jpg out.png[palette,speed=1]
real	0m8.089s
user	0m8.072s
sys	0m0.017s
$ time vips copy in.jpg out.png[palette,speed=10]
real	0m0.676s
user	0m0.650s
sys	0m0.027s
```
=> pngsave: expose quantisation effort setting

libvips/colour/LCh2Lab.c, libvips/colour/Lab2XYZ.c, libvips/colour/XYZ2Lab.c
GCC 11.x could produce bad assembly code due to this. See for example: https://godbolt.org/z/8vT7W8d1o.
```
Lab2XYZ.c: In function ‘vips_col_Lab2XYZ’:
Lab2XYZ.c:250:43: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
250 |         vips_Lab2XYZ_line( (VipsColour *) &Lab2XYZ,
|                                           ^~~~~~~~
Lab2XYZ.c:251:47: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
251 |                 (VipsPel *) out, (VipsPel **) &x, 1 );
|                                               ^~
LCh2Lab.c: In function ‘vips_col_Ch2ab’:
LCh2Lab.c:113:64: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
113 |         vips_LCh2Lab_line( NULL, …
```
=> Fix a few `-Wstrict-aliasing=1` warnings

test/test-suite/test_foreign.py
- `heifsave` defaults to AV1 compression for .avif suffix since commit 8c44863.
- Test lossless compression mode.
=> Adapt `TestForeign.test_heifsave` test

.github/workflows/ci.yml, configure.ac, cplusplus/include/vips/VImage8.h, cplusplus/vips-operators.cpp, fuzz/Makefile.am, fuzz/gifsave_buffer_fuzzer.cc, libvips/foreign/Makefile.am, libvips/foreign/cgifsave.c, libvips/foreign/foreign.c, libvips/include/vips/foreign.h, test/test-suite/test_foreign.py
This PR adds support for GIF encoding via the MIT-licenced [cgif](https://github.com/dloebl/cgif), which is performant, well maintained and tested, plus supports streaming. The aim is that this new saver will be easier/simpler/faster than the *magick-based approach.
It relies on libimagequant to generate the (global) palette and quantise, as we already do for 8-bit PNGs. The palette is intentionally limited to a maximum of 255 colours, which leaves cgif one extra colour for it to optimise frames.
The cgif library is not yet "officially" available via the usual package managers but I've created https://github.com/lovell/cgif-packaging to help start that process.
TODO (there may be more):
=> Add gifsave operation, depends on cgif and libimagequant

cplusplus/include/vips/VImage8.h, libvips/foreign/pforeign.h, libvips/foreign/pngload.c, libvips/foreign/spngload.c, libvips/foreign/vipspng.c
Following this discussion: https://github.com/libvips/libvips/discussions/2418
Adds the flag: `unlimited`, which allows for unlimited-many text chunks when reading PNGs.
Open to feedback
=> Introduce unlimited flag, enabling unlimited text chunks in PNGs

libvips/foreign/cgifsave.c
See https://github.com/dloebl/cgif/pull/18, which is a precursor to the first tagged/published version of cgif.
The Ubuntu PPA and homebrew tap managed by https://github.com/lovell/cgif-packaging have both been updated with this change.
=> gifsave: use cgif namespaced API

libvips/resample/thumbnail.c
By moving the corresponding logic from `vips_thumbnail_calculate_common_shrink` to `vips_thumbnail_calculate_shrink`. This was found while working on PR https://github.com/lovell/sharp/pull/2789.
Reproducer:
```bash
$ vips black x.jpg 858 1
$ vipsthumbnail x.jpg -s 80x
```
Context: https://github.com/lovell/sharp/issues/2653.
=> Ensure vips_thumbnail doesn't send an axis to 0

libvips/foreign/heifload.c
At the moment, unrecoverable errors that occur during HEIF decoding are presented as warnings and subsequent tiles are still requested.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38115 provides an example image that takes minutes to process before ultimately failing. I suspect a few of the other oss-fuzz timeout-related issues might be linked to this too.
By switching to thin strip, the decoding error is detected and handled as soon as possible, however I'm unsure if this is the right way to fix the problem e.g. why is small tile demand not propagating errors?
=> heifload: switch demand to thin strip

libvips/foreign/cgifsave.c, libvips/foreign/pforeign.h, libvips/foreign/quantise.c, libvips/foreign/vipspng.c
Moving the threshold logic from `gifsave` to `quantise`, where we already have all the pixel values in memory, improves the performance of writing GIFs that have an existing alpha channel by ~15%.
Before:
```
63,385,110,223 (36.61%) libimagequant/_build/../libimagequant.c:liq_write_remapped_image_rows [/usr/local/lib/x86_64-linux-gnu/libimagequant.so]
14,773,585,680 ( 8.53%) libvips/conversion/extract.c:vips_extract_band_buffer [/usr/local/lib/libvips.so.42.14.0]
14,768,059,320 ( 8.53%) libvips/conversion/bandjoin.c:vips_bandjoin_buffer [/usr/local/lib/libvips.so.42.14.0]
13,847,368,990 ( 8.00%) /usr/lib/gcc/x86_64-linux-gnu/9/include/xmmintrin.h:nearest_search
10,932,738,351 ( 6.31%) libimagequant/_build/../nearest.c:nearest_search [/usr/local/lib/x86_64-linux-gnu/libimagequant.so]
``` …
=> quantise: support optional thresholding of alpha channel

libvips/foreign/cgifsave.c, test/test-suite/test_foreign.py
This property provides control over the maximum number of colours in the output image palette, making the API more closely match that of `pngsave`.
Given the majority of CPU time when encoding GIF images is spent finding the nearest colour in the palette, lowering the bitdepth from 8 to 7 halves the maximum number of colours from 255 to 127 and reduces encoding time by ~20%.
=> gifsave: expose bitdepth option

.github/workflows/ci.yml, fuzz/mosaic_fuzzer.cc, fuzz/test_fuzz.sh, libvips/colour/scRGB2BW.c, libvips/colour/scRGB2sRGB.c, libvips/conversion/flatten.c, libvips/foreign/heifload.c
As discussed in https://github.com/libvips/libvips/pull/1727#issuecomment-660932493. Commit 81132311674ea54061bb5c2e36db9a2fe8fee19d fixes this error<sup>1</sup>:
```
Running: common_fuzzer_corpus/smartcrop_fuzzer-5687924892368896
mosaic_fuzzer.cc:47:56: runtime error: member access within misaligned address 0x60b0000004c3 for type 'struct mosaic_opt', which requires 2 byte alignment
```
https://travis-ci.org/github/kleisauke/libvips/jobs/709752013#L2599
Commit 1dd6698464584893e0da5e83378799a8b3f58caf fixes this error:
```
Running: common_fuzzer_corpus/sharpen_fuzzer-5678720198639616
scRGB2sRGB.c:114:11: runtime error: 8224 is outside the range of representable values of type 'unsigned char'
```
https://travis-ci.org/github/kleisauke/libvips/jobs/709752013#L2315
Commit …
=> Fix UBSan errors

libvips/iofuncs/image.c, libvips/iofuncs/init.c, libvips/iofuncs/sinkscreen.c
Because atexit() can be called at almost any point during process termination,
including after worker threads have been force-quit, we can't use it for
cleanup.
New policy: use vips_shutdown() explicitly if you need to clean up,
though it's optional. Only use atexit() for leak checking.
=> experiment with removing shutdown from atexit

cplusplus/gen-operators.py, cplusplus/include/vips/VImage8.h, cplusplus/vips-operators.cpp
I think this is clearer, other bindings may need something similar as well.
=> cplusplus: only generate doc comments for non-deprecated args

libvips/foreign/heifload.c, libvips/foreign/nsgifload.c, libvips/foreign/pdfiumload.c, libvips/foreign/popplerload.c
See: https://github.com/lovell/sharp/issues/2890. Reproducer:
```bash
$ curl -LO https://github.com/lovell/sharp/raw/master/test/fixtures/animated-loop-3.gif
$ vipsthumbnail animated-loop-3.gif[page=0,n=1] -s x570 -o x.gif
$ vipsheader x.gif
x.gif: 740x285 uchar, 3 bands, srgb, gifload
$ vipsheader -f n-pages x.gif
2
$ vipsthumbnail animated-loop-3.gif[page=0] -s x570 -o x.gif
$ vipsheader x.gif
x.gif: 740x570 uchar, 3 bands, srgb, gifload
$ vipsheader -f n-pages x.gif
1
```
After this PR:
```bash
$ vipsthumbnail animated-loop-3.gif[page=0,n=1] -s x570 -o x.gif
$ vipsheader x.gif
x.gif: 740x570 uchar, 3 bands, srgb, gifload
$ vipsheader -f n-pages x.gif
1
$ vipsthumbnail animated-loop-3.gif[page=0] -s x570 -o x.gif
$ vipsheader x.gif
x.gif: 740x570 uchar, 3 bands, srgb, gifload
$ …
```
=> Set page height only for multi-page images

libvips/foreign/magick7load.c, libvips/foreign/webp2vips.c
Before:
```
$ curl -LO https://github.com/lovell/sharp/raw/master/test/fixtures/animated-loop-3.webp
$ vipsthumbnail animated-loop-3.webp[page=0] -s x570 -o x.webp
$ vipsheader x.webp
x.webp: 740x285 uchar, 4 bands, srgb, webpload
$ vipsheader -f n-pages x.webp
2
```
After:
```
$ vipsthumbnail animated-loop-3.webp[page=0] -s x570 -o x.webp
$ vipsheader x.webp
x.webp: 740x570 uchar, 3 bands, srgb, webpload
$ vipsheader -f n-pages x.webp
vipsheader: vips_image_get: field "n-pages" not found
```
Note that the WebP loader does not set the `"n-pages"` field for non-animated WebP images, this is different from the libnsgif loader, which seems to always set this field.
=> Incorporate #2506 also in {webp,magick7}load

libvips/foreign/magick7load.c
Introduced in commit f92069b. I probably got confused with the IM 6 loader, which names this variable `read`, see:
https://github.com/libvips/libvips/blob/f92069b0353f3aebbe01793bf49a66895506b444/libvips/foreign/magick2vips.c#L537-L540
=> Fix typo in `magick7load`

libvips/foreign/pngsave.c
It should be possible to set a bitdepth of 16 for PNG output, avoiding the following warning.
```
(process:11191): GLib-GObject-WARNING **: 15:52:12.447: value "16" of type 'gint' is invalid or out of range for property 'bitdepth' of type 'gint'
```
Discovered whilst investigating https://github.com/lovell/sharp/issues/2934
=> pngsave: allow valid bitdepth of 16

libvips/foreign/magick2vips.c, libvips/foreign/magick7load.c
Pick up the imagemagick / graphicsmagick orientation field for libvips.
Tested with graphicsmagick, magick6 and magick7.
see https://github.com/libvips/libvips/issues/2528
=> set libvips orientation on magickload

configure.ac, libvips/foreign/cgifsave.c, libvips/foreign/pforeign.h, libvips/foreign/quantise.c, libvips/foreign/quantise.h, libvips/foreign/vipspng.c
Hey!
I have an image quantization lib named Quantizr that was mentioned in https://github.com/libvips/libvips/issues/2531#issuecomment-966998106. It's not as advanced as libimagequant yet it does its work and it's licensed under MIT. We use it with imgproxy for more than a year, so it's field-tested.
Today I made some improvements, so now it's almost as fast as libimagequant:
Quantizr:
```
$ time vips copy /images/earth.gif[n=-1] x.gif
real	0m1.155s
user	0m0.970s
sys	0m0.066s
```
libimagequant:
```
$ time vips copy /images/earth.gif[n=-1] x.gif
real	0m1.152s
user	0m0.964s
sys	0m0.074s
```
Currently, Quantizr can mimic libimagequant so that we can build libvips with it. Yet this can be easily broken by using a LIQ func that Quantizr doesn't have. Considering this and the fact that Quantizr …
=> Quantizr support

configure.ac
Open for discussion, so only done for 1 library (jxl)
If a library is requested, ie when build using --with-libjxl, --with-libjxl=yes or --with-libjxl=module, and if the library is missing, the configure should fails and not silently (only warning) disable the requested feature
Examples, Auto mode
```
./configure
...
checking for LIBJXL... no
configure: WARNING: libjxl not found; disabling libjxl support
...
JXL load/save with libjxl:              no (dynamic module: no)
```
And, Explicitly required mode
```
./configure --with-libjxl=module
...
checking for LIBJXL... no
configure: error: libjxl not found
```
=> fails if library is requested and missing

.github/workflows/ci.yml, configure.ac, test/test-suite/test_foreign.py
- Remove unused `libgif-dev` dependency from CI.
- Remove no longer relevant comment from testsuite.
- Use yes/no instead of boolean values in `configure.ac`.
=> Minor improvements

cplusplus/VImage.cpp
Spotted this warning when compiling the latest 8.12.
```
VImage.cpp: In member function 'void vips::VImage::write_to_buffer(const char*, void**, size_t*, vips::VOption*) const':
VImage.cpp:736:58: warning: missing sentinel in function call [-Wformat=]
736 |   g_object_get( target.get_target(), "blob", &blob, NULL );
|                                                          ^
```
Low priority, and same fix as https://github.com/libvips/libvips/pull/668 etc.
=> cplusplus: silence missing sentinel warning

libvips/iofuncs/util.c
Calling `vips__set_create_time` with a file descriptor value less than 3 appears to end the process when run on Windows.
Having read https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-170 my understanding is:
* If you pass -1 to `_get_osfhandle` it can crash.
* If you pass 0, 1 or 2 to `_get_osfhandle` it can return a "valid" handle of -2 (note this is not the same as an `INVALID_HANDLE_VALUE` of -1) then `SetFileTime` can crash.
Originally reported at https://github.com/lovell/sharp/issues/2999
=> Windows: don't set create time on invalid/special file descriptors

libvips/histogram/percent.c
A small typo fix on the documenation of `vips_percent`
=> Fix documentation typo

install.md
The dependency name was mentioned as `glib2.0-dev` whereas it was not available in the package repository and the build was failing.
This needed to be `libglib2.0-dev' instead of `glib2.0-dev`. 
It is correctly mentioned in README.md but it is incorrect in install.md in gh-pages branch.
Fixes #2606
=> Fixed package name in required dependency

libvips/foreign/jpeg2vips.c, libvips/iofuncs/source.c
We could sometimes free the VipsSource header cache with unused bytes. This patch delays freeing the header cache until we are certain it is exhausted.
See https://github.com/kleisauke/net-vips/issues/155
=> Fix jpegload pipe

libvips/Vips-8.0.metadata, libvips/include/vips/arithmetic.h, libvips/include/vips/buf.h, libvips/include/vips/connection.h, libvips/include/vips/draw.h, libvips/include/vips/foreign.h, libvips/include/vips/image.h, libvips/include/vips/object.h, libvips/include/vips/operation.h, libvips/include/vips/rect.h, libvips/include/vips/region.h, libvips/iofuncs/image.c
The headers need to be self-contained for the introspection parser
to work correctly. The entry for external users remains vips/vips.h
=> Refine header inclusion to allow better introspection generation

.github/workflows/ci.yml, README.md, fuzz/meson.build, fuzz/test_fuzz.sh, libvips/iofuncs/init.c, suppressions/lsan.supp, test/meson.build, test/test_threading.sh
As discussed in https://gitter.im/libvips/devchat?at=61f6c5059a335454064ac2e0, this PR fixes a small mem leak when the `VIPSHOME` env is not set and the `$libdir/vips-modules-8.13` directory does not exits. It also improves the sanitizer options and suppressions.
This `g_malloc` leak (see CI result of commit f78ce58957cae14e0f2f40e388b4296f213a19d5) was suppressed due to the `libglib-2.0.so` presence in the LSan suppressions. The `fast_unwind_on_malloc=0` wasn't added to the `LSAN_OPTIONS` which caused LSan to fail when unwinding with frame pointers (GLib isn't compiled with `-fno-omit-frame-pointer`) and thus resulted in the error being suppressed.
The last commit (b9d60c196fe66e757542dff48f38b8139d9c24b0) fixes this small leak by avoiding the `vips_strdup` call altogether.
=> LSan improvements and fixes

meson.build
libvips uses g_assert() quite a bit to check things like pointer bounds,
and this can have a large performance impact.
This PR turns off g_assert() (plus some other things) in release mode,
and enables leak checking (and some other things) in debug mode.
I'm not sure if this is the best way to implement this kind of thing.
Does meson have a more offical path for this?
=> set some -Ds depending on the release type

meson.build
And prefer to search for `spng.pc` first, since that one is
generated by Meson.
=> Meson: fix building with `-Dspng=enabled`

meson.build
```
Dependency NIFTI not found: CMake: invalid module NIFTI for NIFTI.
Try to explicitly specify one or more targets with the "modules" property.
Valid targets are:
['NIFTI::znz', 'NIFTI::niftiio', 'NIFTI::nifti1_tool']
Run-time dependency nifti found: NO 
```
=> Meson: ensure NIfTI can be found

libvips/colour/LabQ2sRGB.c, libvips/colour/XYZ2Lab.c, libvips/colour/dE00.c, libvips/colour/pcolour.h, libvips/foreign/dzsave.c, libvips/foreign/heifsave.c, libvips/iofuncs/image.c, libvips/iofuncs/type.c, libvips/iofuncs/vector.c, libvips/resample/interpolate.c
These are only used in the same file, and not exported.
_Split out from #2688._
=> Mark some functions and variables as static

ChangeLog, cplusplus/Doxyfile.in, cplusplus/Makefile.am, cplusplus/VImage.cpp, cplusplus/VRegion.cpp, cplusplus/include/vips/VImage8.h, cplusplus/include/vips/VRegion8.h, cplusplus/include/vips/vips8, cplusplus/meson.build
I happened to have a use case where I needed access to the raw pixel data through regions and discovered that the C++ API was missing support for them. 
I've quickly wired up a VRegion wrapper class based on the existing ones, and added a "region" method on VImage.
=> Add support for regions in the C++ API

.github/workflows/ci.yml, configure.ac, libvips/foreign/cgifsave.c, meson.build
Avoid size issues when resizing GIF animations with a static background. The trick is to restore the original transparency setting after quantization and dithering.
**Background:** Keeping many pixels at the transparency index can reduce the size a lot and is the reason why the original animations in (#2576) are quite small in terms of bytes despite their huge width/height. The current resizing and subsequent color quantization method puts the focus on image quality but can make this transparency optimization less effective.
The suggested fix depends on dloebl/cgif#38 and cgif 0.2.0 to be released:
**Results:**
`$ vipsthumbnail --size 200 city.gif[n=-1] -o vips_city.gif`
`$ vipsthumbnail --size 1400 watch.gif[n=-1] -o vips_watch.gif`
`$ du -h vips_*`
**`2.2M vips_city.gif`
`812K …
=> cgifsave: avoid size issue

libvips/foreign/nsgifload.c
The nsgif_data_scan() call returns an error code that says
if anything was wrong with the source data.
It is not unusual for there to be bad stuff in a GIF, so we
only need to worry if we failed to find any frames.
Fixes #2698.
=> nsgifload: Fix gif decoding issue.

libvips/include/vips/vips7compat.h
nip2 uses the `VIPS_EXEEXT` definition.
```c
main.c:1086:34: error: ‘VIPS_EXEEXT’ undeclared (first use in this function); did you mean ‘IM_EXEEXT’?
1086 |         setenvf( "EXEEXT", "%s", VIPS_EXEEXT );
|                                  ^~~~~~~~~~~
|                                  IM_EXEEXT
```
_Split out from #2688._
=> Ensure compatibility with nip2

libvips/foreign/libnsgif/README.md, libvips/foreign/libnsgif/gif.c, libvips/foreign/libnsgif/nsgif.h, libvips/foreign/libnsgif/test/nsgif.c
A couple of fixes:
- Clipping for frame disposal method of clearing to background colour.
- Frame index limit off-by-one.
=> libnsgif: Update to latest upstream.

libvips/foreign/cgifsave.c, libvips/foreign/libnsgif/gif.c, meson.build
See dloebl/cgif#46 and dloebl/cgif#48.
This fixes cgifsave to make the libvips `loop` property specify the number of iterations instead of the number of times an animation loops. Depends on (the currently unreleased) CGIF version 0.3.0.
=> cgifsave: Make loop counts more accurate

libvips/iofuncs/vips.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46009 (when compiled with debug assertions).
Before:
```
$ vipsheader -a fail.v
(vipsheader:15655): VIPS-WARNING **: 10:35:38.096: error reading vips image metadata: VipsImage: XML parse error
sanity failure: VipsImage (0x558a4f1da330) bad resolution
**
VIPS:ERROR:../libvips/iofuncs/image.c:3619:vips_image_pio_input: assertion failed: (vips_object_sanity( VIPS_OBJECT( image ) ))
Bail out! VIPS:ERROR:../libvips/iofuncs/image.c:3619:vips_image_pio_input: assertion failed: (vips_object_sanity( VIPS_OBJECT( image ) ))
Aborted (core dumped)
```
After:
```
$ vipsheader -a fail.v
vipsheader: VipsImage: invalid resolution
VipsImage: unable to read header for "fail.v"
```
=> vipsload: sanity check resolution

libvips/foreign/libnsgif/README-ns.md, libvips/foreign/libnsgif/README.md, libvips/foreign/libnsgif/gif.c, libvips/foreign/libnsgif/nsgif.h, libvips/foreign/libnsgif/test/nsgif.c, libvips/foreign/nsgifload.c
The main changes are that now clients can control the pixel format that LibNSGIF decodes to, and some internal state has been removed from the GIF info structure.
=> Update to latest libnsgif

libvips/foreign/jpeg2vips.c
Also, pre-increment `num_warnings` to ensure that we really stop
at 100 warnings.
Context: #2749.
=> Add comments to `setjmp` invocations

libvips/foreign/libnsgif/README.md, libvips/foreign/libnsgif/gif.c, libvips/foreign/libnsgif/test/nsgif.c
Includes https://github.com/libvips/libvips/pull/2754 which has been [applied upstream](http://git.netsurf-browser.org/libnsgif.git/commit/?id=aa6e2af43ebb898167f6dc0bb8215eacf0a17389).
=> libnsgif: Update to latest upstream

libvips/foreign/libnsgif/README.md, libvips/foreign/libnsgif/gif.c, libvips/foreign/libnsgif/nsgif.h, libvips/foreign/libnsgif/test/nsgif.c, libvips/foreign/nsgifload.c
This adds access to palette info, as required by #2576.
The upstream test decoder also has a new `-p` option to save images of the palettes.
=> Update LibNSGIF to latest upstream

configure.ac, libvips/foreign/exif.c, meson.build, test/test-suite/test_foreign.py
Make `tag_is_ascii` aware of the EXIF 2.3 ASCII tags that are
available since libexif 0.6.22.
See: https://github.com/kleisauke/net-vips/issues/167
=> Allow to modify/create EXIF 2.3 ASCII tags

libvips/foreign/heifsave.c
Currently an output HEIF image can only have EXIF metadata if the input image also has EXIF metadata. The change in this PR ensures newly-set EXIF is also persisted, bringing the behaviour in line with jpegsave et al.
=> heifsave: ensure added EXIF metadata is persisted

configure.ac, libvips/foreign/exif.c, meson.build
Available since libexif 0.6.23.
Noticed this while working on PR https://github.com/libexif/libexif/pull/85.
Context: https://github.com/libvips/libvips/pull/2795.
=> Allow to modify/create EXIF OffsetTime* tags

libvips/foreign/spngload.c, libvips/foreign/vipspng.c
Hey!
One of imgproxy users gave me a sample of proper PNG with 61 text chunks that expectedly is rejected by vips. First I was going to increase the text chunks limit. But then I thought that we already loaded text chunks at the moment of their number check. So if we have too many text chunks, we can just throw a warning, get the maximum allowed text chunks, and set them to the vips image. It doesn't seem to me that we SHOULD return an error in this case.
WDYT?
=> Don't fail if PNG contains too many text chunks

libvips/foreign/matrixload.c, libvips/foreign/svgload.c
This is similar to commit 5221df224f573653045799fdb98f8fdc19922f2d. Resolves a segfault in `vips_foreign_find_load_source()` when passing a source that returns `-1` during `read()`.
```
Program received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff7c44b20 in vips_strncpy () at /lib64/libvips.so.42
#1  0x00007ffff7ad0a9d in vips_foreign_load_matrix_source_is_a_source () at /lib64/libvips.so.42
#2  0x00007ffff7abe70c in vips_foreign_find_load_source_sub () at /lib64/libvips.so.42
#3  0x00007ffff7c4483d in vips_slist_map2 () at /lib64/libvips.so.42
#4  0x00007ffff7abe66b in vips_foreign_find_load_source () at /lib64/libvips.so.42
```
=> Swap size_t with gint64 to catch read errors

ChangeLog, libvips/foreign/cgifsave.c, libvips/foreign/csvsave.c, libvips/foreign/heifsave.c, libvips/foreign/jp2ksave.c, libvips/foreign/jxlload.c, libvips/foreign/jxlsave.c, libvips/foreign/matrixsave.c, libvips/foreign/pngsave.c, libvips/foreign/ppmsave.c, libvips/foreign/radiance.c, libvips/foreign/spngsave.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vips2webp.c, libvips/foreign/vipspng.c, libvips/foreign/vipssave.c, libvips/include/vips/connection.h, libvips/iofuncs/target.c, libvips/iofuncs/targetcustom.c
since finish did not return an error code
deprecate vips_target_finish
also make sure we don't call target_end from inside _dispose, since that
can't signal error either
see https://github.com/libvips/libvips/issues/2801
=> add vips_target_end

ChangeLog, libvips/foreign/pforeign.h, libvips/foreign/vips2webp.c, libvips/foreign/webpsave.c
We noticed that the `allow_mixed` flag in combination with the `min_size` flag can substantially degrade the encoding time of animated WebP without much improvement on the file size. Allow passing the `allow_mixed` value with a new parameter in `webpsave`.
**Example animation:**
[earth.gif](https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif)
libwebp version: `v1.2.2`
**Old default `min-size=TRUE` behaviour:**
```
$ time vips copy earth.gif[n=-1] min_mixed.webp[min-size=true,mixed=true]
6.743s
```
**New default `min-size=TRUE` behaviour:**
```
$ time vips copy earth.gif[n=-1] min.webp[min-size=true,mixed=false]
0.758s
```
```
$ du -h min_mixed.webp min.webp
256K	min_mixed.webp
256K	min.webp
```
/cc @gurpreetg
=> webpsave: add parameter for mixed encoding

libvips/foreign/jxlload.c, libvips/foreign/jxlsave.c
This was removed via https://github.com/libjxl/libjxl/pull/1337
Technically it has been deprecated, but can be considered as good as gone due to not being included in the official spec.
=> jxl: remove support for never-implemented JXL_TYPE_UINT32

libvips/foreign/pdfiumload.c
Hey again!
Some PDF pages require the background to be transparent to be rendered properly. Luckily, `FPDFPage_HasTransparency` returns `TRUE` for such pages so we can easily determine if we should fill the canvas before rendering. PDFium sample tool does the same check BTW: https://pdfium.googlesource.com/pdfium/+/refs/heads/main/samples/pdfium_test.cc#864.
Also, I used `FPDFBitmap_FillRect` to fill the background of a single page instead of a whole canvas. And I changed `pdf->ink` type so it can be used with `FPDFBitmap_FillRect`, hope it's ok.
Unfortunately, I can't share a sample I have as it was provided by a customer of our customer so I definitely have no right to share it anywhere.
=> Don't paint the background if the PDF has transparency

libvips/colour/icc_transform.c
This ensures child processes do not inherit open file descriptors and will close a small but long-standing bug reported against sharp over five years ago.
https://github.com/lovell/sharp/issues/674
The change to lcms2 to support this is backwards compatible so the flag will be ignored by existing versions.
https://github.com/mm2/Little-CMS/commit/6ae2e99a3535417ca5c95b602eb61fdd29d294d0
The `fopen()` close-on-exec (`e`) flag will soon be part of the POSIX standard, and is already supported in Linux and BSD. macOS currently ignores it but will have to add support soon to remain POSIX compliant. Only Windows has a problem with it, hence the ifdef wrapper.
=> Pass close-on-exec flag to lcms for non-Windows OS

configure.ac, libvips/foreign/svgload.c, meson.build, test/test-suite/test_foreign.py
Rather than defaulting to 1928x1080. Also, prefer to use the
`LIBRSVG_CHECK_VERSION` macro instead of our configure checks.
=> svgload: recognize dimensions for SVGs without width/height

ChangeLog, libvips/foreign/cgifsave.c, libvips/foreign/nsgifload.c
For reference: [2576#comment](https://github.com/libvips/libvips/issues/2576#issuecomment-1121206055)
Reuse the global palette in `gifsave` if it has been attached during `gifload`.
This should both improve the file size and processing time for many GIF -> GIF operations.
@jcupitt **Notes / Questions:**
1. [Quantizing the attached global palette](https://github.com/dloebl/libvips/blob/75b08f3bce9f7a42a60e7859824cabb3c483d549/libvips/foreign/cgifsave.c#L256) to get a `VipsQuantiseResult` feels a bit hacky. Maybe there is a better way to do it?
2. As we probably don't want to enable this new behaviour for any kind of GIF -> GIF operation, should we add a parameter to `gifsave` to enable/disable global palette reuse?
3. Dithering seems to cause colour artifacts with certain GIFs:
$ …
=> cgifsave: reuse global palette, if possible

cplusplus/meson.build, doc/meson.build
It seems that `private_headers` didn't work for out-of-tree builds.
This PR makes it use full paths and adds a few missing files.
Should fix the following errors when building with gtk-doc enabled:
<details>
```
/usr/bin/ld: libvips-scan.o: in function `main':
libvips-scan.c:(.text.startup+0x98): undefined reference to `vips_arithmetic_get_type'
/usr/bin/ld: libvips-scan.c:(.text.startup+0xe0): undefined reference to `vips_bandary_get_type'
/usr/bin/ld: libvips-scan.c:(.text.startup+0xec): undefined reference to `vips_binary_get_type'
/usr/bin/ld: libvips-scan.c:(.text.startup+0x134): undefined reference to `vips_colour_code_get_type'
/usr/bin/ld: libvips-scan.c:(.text.startup+0x140): undefined reference to `vips_colour_difference_get_type'
/usr/bin/ld: …
```
=> doc: add missing files and use full paths

libvips/foreign/cgifsave.c
Hey!
When we make pixels fully transparent in `cgifsave` it's better to fill them with zeroes. This removes nasty artifacts when saving resized GIF with transparency. Also this reduces the number of colors in the image and helps a quantizer to build a better palette.
=> cgifsave: fill transparent pixels with zeroes

libvips/foreign/spngsave.c
Test case:
```bash
$ curl -LO https://github.com/lovell/sharp/raw/main/test/fixtures/expected/embed-4-into-4.png
$ vips copy embed-4-into-4.png x.png[palette]
```
=> spngsave: fix 8bpp palette save with transparency

configure.ac, libvips/create/text.c, meson.build
See: https://gitlab.gnome.org/GNOME/pango/-/issues/551.
Resolves: https://github.com/kleisauke/net-vips/issues/170.
=> text: ensure fontconfig cache of Pango is invalidated

libvips/foreign/cgifsave.c, libvips/foreign/quantise.c, libvips/foreign/quantise.h
Hey!
This is the POC of my approach to generating palettes for `cgifsave`.  How it works:
1. We compute a palette for each frame. The first frame's palette we use as a global one.
2. For each frame except the first we compare the palette computed in step 1 with the global palette and the local palette of the previous frame (if any).
3. If there's a local palette in the previous frame, and the diff between it and the current frame palette is small enough, we use the palette from the previous frame as local for the current frame.
4. Otherwise, if the diff between the global palette and the current frame palette is small enough, we don't use a local palette.
5. Otherwise, we use the palette computed in step 1 as a local palette for the current frame.
With this approach, we mitigate the …
=> cgifsave: palette change POC

configure.ac, libvips/create/text.c, meson.build
> Note that since Pango 1.32.6, the default fontmap is per-thread. Each thread gets its own default fontmap. In this way, PangoCairo can be used safely from multiple threads.
> https://docs.gtk.org/PangoCairo/type_func.FontMap.get_default.html
Depends on: #2847.
=> text: use MT-safe `pango_cairo_font_map_get_default`

libvips/foreign/csvload.c, libvips/foreign/fitsload.c, libvips/foreign/fitssave.c, libvips/foreign/heifload.c, libvips/foreign/heifsave.c, libvips/foreign/jp2kload.c, libvips/foreign/jpegload.c, libvips/foreign/jxlload.c, libvips/foreign/magick6load.c, libvips/foreign/magick7load.c, libvips/foreign/matrixload.c, libvips/foreign/niftiload.c, libvips/foreign/niftisave.c, libvips/foreign/nsgifload.c, libvips/foreign/openslideload.c, libvips/foreign/pdfiumload.c, libvips/foreign/pngload.c, libvips/foreign/popplerload.c, libvips/foreign/ppmload.c, libvips/foreign/ppmsave.c, libvips/foreign/radload.c, libvips/foreign/spngload.c, libvips/foreign/svgload.c, libvips/foreign/tiffload.c, libvips/foreign/vips2magick.c, libvips/foreign/vipsload.c, libvips/foreign/webpload.c, libvips/iofuncs/system.c, libvips/resample/thumbnail.c
Use the bitwise OR assignment operator to ensure that derived
classes does not overwrite the flags from the base class. Also,
move the flags from `openslideload_source` to its base class.
=> Prefer to use `flags |=` everywhere

libvips/foreign/popplerload.c
`pdfload` using PDFium is continuously fuzzed by OSS-Fuzz, but Poppler not.
=> Mark Poppler as untrusted

cplusplus/meson.build, libvips/meson.build, meson.build
By setting the correct compatibility/current version.
<details>
Before:
```bash
$ otool -L /usr/local/lib/libvips.42.dylib
/usr/local/lib/libvips.42.dylib:
/usr/local/lib/libvips.42.dylib (compatibility version 42.0.0, current version 42.0.0)
```
https://github.com/kleisauke/libvips/runs/6845286445#step:15:15
After:
```bash
$ otool -L /usr/local/lib/libvips.42.dylib
/usr/local/lib/libvips.42.dylib:
/usr/local/lib/libvips.42.dylib (compatibility version 58.0.0, current version 58.0.0)
```
https://github.com/kleisauke/libvips/runs/6845516339#step:15:15
Autotools:
```bash
$ otool -L /usr/local/lib/libvips.42.dylib
/usr/local/lib/libvips.42.dylib:
/usr/local/lib/libvips.42.dylib (compatibility version 58.0.0, current version 58.0.0)
``` …
=> Meson: maintain autotools compatibility on macOS

libvips/foreign/cgifsave.c, libvips/foreign/quantise.c
And fix a few memory errors and leaks with `reoptimise`.
Speed seems the same. 
```
$ valgrind vipsthumbnail 3198.gif[n=-1] -o vips-13.gif --size 224
$ valgrind vipsthumbnail 3198.gif[n=-1] -o vips-13.gif[reoptimise] --size 224
```
Both pass cleanly. You can use `--vips-info` to get a bit of debugging output:
```
$ time vips copy sample.gif[n=-1] x.gif[reoptimise] --vips-info
VIPS-INFO: 18:17:19.094: cgifsave: 301 frames
VIPS-INFO: 18:17:19.094: cgifsave: 215 unique palettes
real	0m17.583s
user	0m24.593s
sys	0m0.477s
```
=> try to make cgifsave easier to read

configure.ac, libvips/colour/icc_transform.c, libvips/conversion/conversion.c, libvips/include/vips/deprecated.h, libvips/iofuncs/connection.c, libvips/iofuncs/sbuf.c, libvips/iofuncs/source.c, libvips/iofuncs/sourcecustom.c, libvips/iofuncs/sourceginput.c, libvips/iofuncs/target.c, libvips/iofuncs/targetcustom.c, meson.build, tools/vips.c, tools/vipsedit.c
- Remove `HAVE_LCMS` definition in favor of `HAVE_LCMS2`.
- Remove `HAVE_WINDOWS_H` definition in favor of `G_OS_WIN32`.
- Remove stray `vips_text_get_type` in `conversion.c`.
- Remove duplicated `unistd.h` include.
- Remove redundant `strcasecmp` definition, we use `g_ascii_strcasecmp` everywhere.
- Remove unnecessary header checks in `configure.ac` and `meson.build`.
- Ensure `unistd.h` include is guarded with `HAVE_UNISTD_H`.
- Fail early when `-Dfontconfig=enabled` and `pangoft2` is not found.
=> Minor cleanups

.github/workflows/ci.yml, suppressions/lsan.supp, test/test_formats.sh
- Compile with GCC 11 and Clang 14.
- Remove redundant PPAs.
- Use system provided Meson.
- Update LeakSanitizer suppressions.
Note that this GitHub Actions runner is still in beta phase, so we might have to wait.
=> CI: upgrade runner to Ubuntu 22.04

libvips/foreign/cgifsave.c
By reusing `cgif->palette_rgb`, this ensures that `pLocalPalette`
doesn't become indeterminate when it reaches `cgif_addframe`.
=> cgifsave: fix stack-use-after-scope

libvips/foreign/cgifsave.c
See commit https://github.com/ImageOptim/libimagequant/commit/f3842644bc4120e7bda31e7c7be45ee34a0ae350.
Test cases:
```bash
$ vips black x.gif 23171 23171
$ vips black x.gif 23170 23170
$ vips black x.gif 65535 1
$ vips black x.gif 1 65535
```
=> cgifsave: reject images that exceed the pixel limit of libimagequant

libvips/resample/thumbnail.c
Test case:
```bash
$ vips black x.webp 100 100
$ vipsthumbnail x.webp -s 16384x
```
Context: https://github.com/lovell/sharp/issues/3262.
=> thumbnail: avoid upsizing via libwebp

libvips/foreign/cgifsave.c
Hey!
This PR fixes a few regressions introduced in #2853.
e4271e16de1f5ee75c27d3115edbe951597db3da: My original approach intent picking the best suitable palette. But after #2835 it picks the global palette if it is good enough even if the previous local palette is better.
c33d2a2766fe542856e2bcaf766ca5cd018c4505: #2835 changed palette comparison and `interpalette_maxerror` of 40 became too high. Also, `int` is not prcisive enough for this new method and `double` should be used.
4a9c96a6a49443522f7fca2a9edc74e2493cd81d: only changed pels should be copied to `cgif->previous_frame`.
The first two commits fix #2864.
=> cgifsave: remove regressions from 2853

libvips/foreign/cgifsave.c
Limit the maximum number of colours to 255, so we always leave one index free for the transparency.
Avoids the artefact mentioned here: https://github.com/libvips/libvips/issues/2852#issuecomment-1153728379
=> cgifsave: limit max number of colours to 255

doc/Makefile.am
Since that is also used by Meson (when configuring with `-Dgtk_doc=true`
and when pandoc is available).
=> doc: ensure `pandoc-docbook-template.docbook` is distributed

cplusplus/Doxyfile.in
Now that IE is finally gone, all the main browsers support this, which
provides higher quality and smaller sizes.
Inspired by commit https://github.com/libexif/libexif/commit/4a7ab4cc1332afbc63c44a8a96c93421d6aa07a0.
=> Doxygen: use SVG for the call graph images

configure.ac, cplusplus/meson.build
Fixes the build with `-Ddoxygen=true --fatal-meson-warnings`:
```
cplusplus/meson.build:48: WARNING: Project targeting '>=0.56' but tried to use feature deprecated since '0.56.0': meson.source_root. use meson.project_source_root() or meson.global_source_root() instead.
cplusplus/meson.build:47:17: ERROR: Fatal warnings enabled, aborting
```
=> Meson: avoid using deprecated feature

cplusplus/VConnection.cpp, cplusplus/VError.cpp, cplusplus/VImage.cpp, cplusplus/VInterpolate.cpp, cplusplus/VRegion.cpp
Since these files doesn't use any i18n features. This makes it easier for downstream projects to consume these files without having to define `GETTEXT_PACKAGE`, see: https://github.com/lovell/sharp/pull/3230#issuecomment-1163484509.
I also thought about guarding this include with `HAVE_CONFIG_H` throughout the codebase. However, that causes compiler errors when individual files are compiled that uses macros from this include directive, for example:
```bash
gcc -S libvips/foreign/exif.c -DGETTEXT_PACKAGE=\"vips8.13\" -DHAVE_EXIF -Ilibvips/include `pkg-config vips --cflags --libs` -lexif
```
(which could be handy to check the assembler output)
=> cplusplus: remove i18n include

libvips/foreign/svgload.c
See: https://gitlab.gnome.org/GNOME/librsvg/-/issues/853.
=> svgload: use `rsvg_handle_get_geometry_for_element` instead

meson.build
This is already controlled by the `b_lundef` built-in option, which defaults to `true`.
=> Meson: remove redundant `--no-undefined` link argument

configure.ac, libvips/Makefile.am, libvips/meson.build, meson.build
See: https://github.com/libvips/php-vips-ext/pull/44
=> Link the main library with `-Wl,-z,nodelete` to prevent unloading

.github/workflows/ci.yml
The GLib utilities, including `glib-mkenums`, is split into its own
`glib-utils` formula, see:
https://github.com/Homebrew/homebrew-core/pull/103916
=> CI: fix macOS build

meson.build
ImageMagick 7.x uses the `<MagickCore/MagickCore.h>` include
directive instead of `<magick/api.h>`.
=> Fix detection of  `ImportImagePixels` and `ImagesToBlob` for IM7

libvips/conversion/extract.c
The `*_class_intern_init` functions have already been patched within wasm-vips to include the missing `class_data` member, see: https://github.com/kleisauke/wasm-vips/blob/v0.0.3/build/patches/glib-function-pointers.patch#L2661-L2680
So, this adapter function was not needed.
As an aside, I'm investigating integrating the necessary WebAssembly patches of GLib upstream. Although, GLib has a hard requirement with function pointer conversions, which will not work on WASM, see:
https://gitlab.gnome.org/GNOME/glib/-/blob/2.73.2/docs/toolchain-requirements.md#function-pointer-conversions
https://stackoverflow.com/a/14044244
Hopefully they will loosen that requirement.
=> Remove unneeded adapter function for Emscripten

.github/workflows/ci.yml
ninja runs as many parallel jobs as there are available CPU cores
by default. So, there's no need to set this environment variable.
=> CI: remove redundant JOBS env

libvips/foreign/jxlsave.c
It's required to close the input, otherwise the encoder can't
know what the last frame is, resulting in an improper codestream.
Resolves: #2987.
=> jxlsave: correctly mark frame as last

configure.ac, libvips/foreign/jxlsave.c, meson.build
The upcoming libjxl 0.7 has deprecated a number of functions.
=> jxlsave: avoid using deprecated functions

libvips/foreign/cgifsave.c, meson.build, test/test-suite/test_foreign.py
cgif >= [v0.3.0](https://github.com/dloebl/cgif/releases/tag/V0.3.0) supports writing interlaced (progressive) GIFs. Add support for interlaced GIF write in libvips.
**Note:** As of now, cgif requires more memory for writing interlaced GIFs (tracked by https://github.com/dloebl/cgif/issues/52).
=> cgifsave: add support for interlaced GIF write

README.md
Just a quick suggestion to make it more clear how the `libjpeg` dependency works.
The most important change is recommending `mozjpeg`, because it is the package that will give you access to the most features and the best compression. Before, it seemed like `libjpeg-turbo` was the best option.
Another little detail I put in there, is just to make it clear that you can use any lib which supports the standard IJG JPEG library interface. As a new user, I was confused by the original wording, and thought I had to use the IJG library.
=> Mention mozjpeg as the best libjpeg option

ChangeLog, libvips/foreign/dzsave.c
By implementing `GsfOutfileStdio` ourselves. This allows users to
write to a pre-existing directory on libgsf prior to version 1.14.29.
Resolves: #3007.
=> dzsave: improve compatibility with libgsf < 1.14.29

ChangeLog, libvips/foreign/jpeg.h, libvips/foreign/jpeg2vips.c, libvips/foreign/tiff2vips.c, libvips/foreign/vips2jpeg.c, libvips/include/vips/memory.h
Most time in TIFF read is spent in decompression. If we move this
outside the lock, we can get a useful speedup.
This commit adds the machinery to move the lock to before decompress, so
jp2k decompression is now threaded.
Before:
```
$ vips copy wtc.jpg x.tif[tile,compression=jp2k]
$ time vips avg x.tif
117.249845
real	0m15.085s
user	0m16.155s
sys	0m0.109s
```
After:
```
$ time vips avg x.tif
117.249845
real	0m1.207s
user	0m18.384s
sys	0m0.369s
```
=> move tiff decompress outside lock

.github/workflows/ci.yml
The GLib utilities, which was split into its own `glib-utils`
formula has been merged back into `glib`, see:
https://github.com/Homebrew/homebrew-core/pull/108307
This reverts commit a846de017d9f369ea3cdd1b0f5510bebbb71b5c7.
=> CI: remove redundant glib-utils dependency

libvips/foreign/dzsave.c
=> dzsave: add missing include directive for errno/EEXIST

libvips/foreign/pngsave.c, libvips/foreign/spngsave.c
This PR ensures the logic matches the comment and, I think, intended behaviour. (It also fixes comment indentation.)
It targets the 8.13 branch as this appears to be a bug introduced in v8.13.1 via commit https://github.com/libvips/libvips/commit/198920398509465ab00e7c6f5584fd345bda20e7
Reported downstream at https://github.com/lovell/sharp/issues/3357
=> pngsave: ensure 8-bit palette images can be created

libvips/foreign/nsgifload.c
The context
When we process animated images in imgproxy, we split them into frames with `vips_extract_area`. `vips_webpsave` basically does the same: https://github.com/libvips/libvips/blob/v8.13.0/libvips/foreign/vips2webp.c#L359-L361
The problem
In `vips_nsgifsave`, libvips sets `tile-height` of `vips_sequential` to 16. When the GIFs page height is not dividable by 16, this leads to decoding multiple pages when we try to cut out a single page. This happens because the first tile of the page often contains pixels of the previous page and the list tile contains pixels of the nest page. And this leads to the situation when nsgif has to start decoding from the start. If we turn on debug messages we'll see the following:
```
nsgif_frame_decode(0) = 0
nsgif_frame_decode(1) = 0 …
```
=> nsgifload: choose tile-height based on page height

libvips/foreign/tiff2vips.c
Required since commit https://github.com/libvips/libvips/commit/a7e754162abf8bed28a8ca50c8bb8e42dac97955
```
../libvips/foreign/tiff2vips.c: In function ‘rtiff_decompress_jpeg_run’:
../libvips/foreign/tiff2vips.c:1890:9: error: unknown type name ‘uint32_t’; did you mean ‘u_int32_t’?
1890 |         uint32_t tables_len;
```
=> tiff2vips: ensure stdint.h is included for uint32_t type

libvips/foreign/vips2tiff.c
This ensures that subifd pyramid layers are correctly tagged as reduced-image subfile type and not as pages when creating a multi-page image stack. With the previous tag writing order, the reduced-image subfile type was being over-written.
=> Inverted order of TIFF tag writing when saving multi-page subifd pyramids

libvips/foreign/jxlsave.c
Ensures the quality to distance conversion is continuous at 30.
See:
https://github.com/libjxl/libjxl/commit/ea5fa8074d0146ec0f4388f52990d428ea3b67c3
=> jxlsave: sync quality to distance calculation with libjxl

libvips/convolution/convi.c, libvips/resample/reducev.cpp
The performance degradation mentioned in the comment wasn't reproducible here. On x86 with the SSE2 instruction set this will result in:
```c
// convsuswb
d1 = _mm_packus_epi16( sum, sum );
```
instead of:
```c
// maxsw
sum = _mm_max_epi16( sum, _mm_set1_epi16( 0 ) );
// minsw
sum = _mm_min_epi16( sum, _mm_set1_epi16( 255 ) );
// convwb
sum = _mm_slli_epi16( sum, 8 );
sum = _mm_srli_epi16( sum, 8 );
d1 = _mm_packus_epi16( sum, sum );
```
So, it saves a few instructions.
=> convi/reducev: use convsuswb in Orc path

libvips/convolution/convi.c, libvips/iofuncs/vector.c, libvips/resample/reducev.cpp
Instead of adding to the sum during the clip, we could just intialize the sum with the addition. This avoids an Orc opcode, so I expect it to be slightly faster.
I also added a couple of comments to magic numbers in `vector.c`.
=> convi/reducev: initialize the sum with the addition

libvips/foreign/vips2tiff.c
For images that are smaller than the tile size, empty SubIFD offsets get added resulting in corrupted TIFF files
=> SubIFD offsets should only be added if smaller pyramid layers actually exist

libvips/foreign/tiff2vips.c
Since that could terminate the application in debug builds. Also, add the missing case clause for `PHOTOMETRIC_MINISWHITE`, see:
https://gitlab.com/libtiff/libtiff/-/blob/4c3ddd99b6efbdca9d0f2e91a53671edb0656fd7/libtiff/tif_jpeg.c#L1706-1731
Resolves: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51013.
=> tiff2vips: avoid `g_assert_not_reached` in the default clause

ChangeLog, libvips/foreign/spngsave.c
The PNG spec requires that the iCCP chunk has a profile name with a minumum length of 1 (we use the same "icc" name as pngsave).
http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.iCCP
https://github.com/libvips/libvips/blob/4176ab21061f425b4ee274f7f9c6634dacf5ca7c/libvips/foreign/vipspng.c#L1113-L1115
Targets the 8.13 branch as this is a bug fix.
Originally reported at https://github.com/lovell/sharp/issues/3390
=> spngsave: ensure ICC profiles have a name

libvips/foreign/webpsave.c
Switch from `g_malloc()` to `g_try_malloc()` to avoid that `g_malloc()` aborts the program on error.
**Before:**
```
$ vips black out.webp 10000000 10000000
(vips:27126): GLib-ERROR **: 14:44:37.810: ../glib/gmem.c:136: failed to allocate 300000000000000 bytes
zsh: trace trap (SIGTRAP) vips black out.webp 10000000 10000000
```
**With 0adc6687418803aa86d3b59d62a319aa3b5569e9:**
```
$ vips black out.webp 10000000 10000000
webpsave: out of memory
error buffer: webpsave: out of memory
```
I also added a check for the dimensions limit of WebP (16383 x 16383) with 263476275319844118d8729228a2253c4b06ab16, so that we get a nicer looking error message in this case:
```
$ vips black out.webp 10000000 10000000
webpsave: image too large
error buffer: webpsave: image too large
```
=> webpsave: switch to g_try_malloc() and limit WebP output dimensions

libvips/foreign/spngsave.c, libvips/foreign/vipspng.c
i.e. after setting the metadata and phyiscal pixel dimensions, since quantisation will overwrite the image.
Before:
```bash
$ vips copy fruit-g236fa3733_1920.png x.png[palette]
$ vipsheader -f xres x.png
1
$ vipsheader -f icc-profile-data x.png
vipsheader: vips_image_get: field "icc-profile-data" not found
```
After:
```bash
$ vips copy fruit-g236fa3733_1920.png x.png[palette]
$ vipsheader -f xres x.png
2.835
$ vipsheader -f icc-profile-data x.png
<base64-encoded binary data>
```
Targets the 8.13 branch as this is a bug fix.
Originally reported at https://github.com/lovell/sharp/issues/3392.
=> spngsave: ensure quantisation occurs last

libvips/foreign/spngsave.c
Fixes https://github.com/lovell/sharp/issues/3395
LIQ may not sort the palette by alpha properly so the current way of filling `trns` may not work in some cases. This PR makes libvips fill `trns.type3_alpha` for every palette entry but update `trns.n_type3_entries` only when the palette entry has transparency. Thus we don't care if the palette is sorted by alpha or not.
=> spngsave: fix transparency

ChangeLog, libvips/colour/icc_transform.c
This seems to export to 6clr CMYK correctly. We'll need something fancier for import, and for more generic N colour profiles.
See https://github.com/libvips/libvips/discussions/3045 for a sample 6 clr profile.
=> add suport for N colour ICC profiles

ChangeLog, libvips/foreign/exif.c
It looks like some newer Apple devices are attaching EXIF to images without the `Exif\0\0` prefix, however libexif still requires it due to JPEG/JFIF/APP1 marker heritage.
There's an upstream issue about this at https://github.com/libexif/libexif/issues/58
Originally reported at https://github.com/lovell/sharp/issues/3412
Before:
```
exif-data: 2402 bytes of binary data
exif-ifd0-XResolution: 72009/1000 (72.009, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 72009/1000 (72.009, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd2-ExifVersion: Exif Version 2.1 (Exif Version 2.1, Undefined, 4 components, 4 bytes)
exif-ifd2-FlashpixVersion: FlashPix Version 1.0 (FlashPix Version 1.0, Undefined, 4 components, 4 bytes) …
```
=> exif: ensure prefix is present before parsing

libvips/foreign/spngsave.c
Hey!
The commit https://github.com/libvips/libvips/commit/ca2796aa7ff75c5bb5a74a1f3a4de9538bb9c45e have broken saving paletted PNGs with low bit-depth (< 8). This happens because palette indexes can't be larger than `1 << bitdepth`, so shifting makes all of them zeroes.
Fixes https://github.com/imgproxy/imgproxy/issues/1013
=> spngsave: Don't shift indexed pixels

test/test_cli.sh, test/test_connections.sh, test/test_stall.sh, test/variables.sh.in
There are two types of tests that are implemented here:
- Some tests have an if block, and only run the entire test if some single prerequisite condition is available. This is a simple fix, because the tests are already skipped, but they don't say so. Make these `exit 77` so they are marked as having been skipped.
- Some tests use `bc`, and fail if that is not installed. Make this a bit nicer, and abort the test, marking it as skipped. Oftentimes, `bc` is not installed.
=> skip some skippable tests

libvips/foreign/webpsave.c
<details>
```
../libvips/foreign/webpsave.c:1153:16: error: unknown type name 'VipsImage'
vips_webpsave( VipsImage *in, const char *filename, ... )
^
../libvips/foreign/webpsave.c:1159:11: warning: implicit declaration of function 'vips_call_split' is invalid in C99 [-Wimplicit-function-declaration]
result = vips_call_split( "webpsave", ap, in, filename );
^
../libvips/foreign/webpsave.c:1199:23: error: unknown type name 'VipsImage'
vips_webpsave_buffer( VipsImage *in, void **buf, size_t *len, ... )
^
../libvips/foreign/webpsave.c:1202:2: error: use of undeclared identifier 'VipsArea'
VipsArea *area;
^
../libvips/foreign/webpsave.c:1202:12: error: use of undeclared identifier 'area'; did you mean 'free'?
VipsArea *area;
^~~~
free
/usr/include/stdlib.h:555:13: …
```
=> Fix build with `-Dwebp=disabled`

libvips/foreign/exif.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52606
This was exposed by me in https://github.com/libvips/libvips/pull/3100, sorry.
=> Ensure EXIF is at least 4 bytes before inspection

libvips/foreign/libnsgif/README-ns.md, libvips/foreign/libnsgif/README.md, libvips/foreign/libnsgif/gif.c, libvips/foreign/libnsgif/nsgif.h, libvips/foreign/libnsgif/test/nsgif.c, libvips/foreign/libnsgif/update.sh, libvips/foreign/nsgifload.c
This allows libnsgif to distinguish between awaiting more data, and a broken truncated GIF. In the latter case we can display what we have.
Using libnsgif's test utility with the sample truncated GIF from https://github.com/libvips/libvips/issues/3134 was failing:
```
test_nsgif -i ~/Downloads/bad-truncated.gif 
gif:
width: 575
height: 800
max-loops: 1
frame-count: 0
global palette: yes
background:
red: 0xb2
green: 0xb2
blue: 0xb2
frames:
nsgif_frame_prepare failed: Frame can't be displayed
```
Now we get:
```
test_nsgif -i ~/Downloads/bad-truncated.gif
gif:
width: 575
height: 800
max-loops: 1
frame-count: 1
global palette: yes
background:
red: 0xb2
green: 0xb2
blue: 0xb2
frames:
- frame: 0
local palette: no
disposal-method: Unspecified
transparency: yes
display: yes
delay: 0
rect:
x: 0 …
```
=> Update to latest upstream libnsgif and call nsgif_data_complete

libvips/foreign/dzsave.c
It can return `NULL` when it exceeds the path limits.
Resolves: https://github.com/kleisauke/net-vips/issues/184.
=> dzsave: add error handling for `vips_gsf_path()`

libvips/foreign/heifload.c, libvips/foreign/nsgifload.c, libvips/foreign/webp2vips.c, libvips/iofuncs/mapfile.c, libvips/iofuncs/source.c, libvips/meson.build, meson.build, test/meson.build, test/test_descriptors.c, test/test_descriptors.sh
Since it's not reliable on Windows, this corresponds to what is done in the PPM and WebP loaders. Previously on Windows, it somehow caused an "access denied"-error when trying to delete the GIF file after processing it.
While we're at it, improve `test_descriptors.c` by printing all the leaked paths, if there's a leak (previously it only printed the file passed as the first argument, which is not necessarily the case).
Context: https://github.com/libvips/libvips/discussions/3185.
=> nsgifload: avoid minimise after mapping 

doc/Examples.md, doc/Examples.xml, doc/How-it-opens-files.md, doc/How-it-opens-files.xml, doc/How-it-works.md, doc/How-it-works.xml, doc/Making-image-pyramids.md, doc/Making-image-pyramids.xml, doc/Using-vipsthumbnail.md, doc/Using-vipsthumbnail.xml, doc/binding.md, doc/binding.xml, doc/libvips-from-C++.md, doc/libvips-from-C++.xml
Note that I recently became aware that `bash` is not the correct keyword for shell commands. You have to use `console` for that to ensure that syntax highlighting doesn't match on output. For example:
```bash
$ for i in {1..1000}; do cp x.tif test/$i.tif; done
for i in {1..1000}; do cp x.tif test/$i.tif; done
```
(i.e., triple backtick `bash`)
```console
$ for i in {1..1000}; do cp x.tif test/$i.tif; done
for i in {1..1000}; do cp x.tif test/$i.tif; done
```
(i.e., triple backtick `console`, much nicer)
Unfortunately DocBook (or Pandoc?) does not support that, so commit bed04b85d24ee43005bbe37d89489771b76e883c removes the bash highlighting on output where this is a issue.
_Split out from #3125._
=> Minor doc improvements

.github/workflows/ci.yml
It might be the cause of the intermittent ASan failures on CI.
This workaround should be safe, since it has been adopted by many projects, e.g. [Chromium](https://github.com/chromium/chromium/commit/536f57c0fd998ebb788a668544e721fa87d0fd74), [Node.js](https://github.com/nodejs/node/commit/347000ccf8c4705721ff60717b234c75e72183cd) and others.
See: https://github.com/google/sanitizers/issues/1322
=> CI: disable `__tls_get_addr` interception in ASan

ChangeLog, libvips/foreign/jxlsave.c, meson.build
This partially reverts commit 0029b3c4.
See: https://github.com/libvips/libvips/commit/0029b3c416de8f520e6282ad5085403a9648a2a7#commitcomment-92398283 and the previous discussion in PR #2539.
=> Allow libjxl 0.6

ChangeLog, libvips/foreign/foreign.c, libvips/foreign/heifsave.c, libvips/include/vips/foreign.h
[libheif](https://github.com/strukturag/libheif) supports various backends: For instance `aom`, `svt` and `rav1e` for AV1 encoding.
As of now, we use the first encoder we find (default encoder). However, in some cases it's useful to force [libheif](https://github.com/strukturag/libheif)  to use a different encoder (e.g. `svt` instead of `aom`).
Make it possible to specify the encoder to use (e.g. `aom`, `svt` etc).
**Question to the reviewer:**
~~Do we want to add a list of encoders to libvips or is it fine to just pass a string to libheif directly (as in this PR with the `encoder` parameter)?~~
=> heifsave: make it possible to use a specific encoder

suppressions/valgrind.supp
It looks like the internal implementation of `pthread_create` in newer versions of glibc has altered the call stack slightly.
With glibc 2.35 I see:
```
fun:calloc
fun:allocate_dtv
fun:_dl_allocate_tls
fun:allocate_stack
fun:pthread_create@@*
```
The frame-level wildcard additions in this PR should allow the suppression to match both ("it works on my machine" :tm: ).
=> Ensure pthread_create suppression stack also matches newer glibc

doc/meson.build, meson.build, test/meson.build
Allowing libvips to be compiled on RHEL 7 (and its derivatives). Tested with:
```console
$ pip3 install meson==0.55.0
$ meson setup full_build -Ddoxygen=true -Dgtk_doc=true -Dvapi=true
$ meson compile -Cfull_build
$ meson install -Cfull_build
```
See: https://github.com/libvips/libvips/issues/2879#issuecomment-1368742798.
=> Lower Meson version requirement to 0.55.x

libvips/create/create.c, libvips/create/meson.build
Found when generating the TypeScript declaration file of wasm-vips.
=> Minor GIR fixes

libvips/conversion/premultiply.c, libvips/conversion/unpremultiply.c, libvips/include/vips/util.h, meson.build
This rather neat compiler feature requires gcc 6+ or clang 14+ as well as glibc 2.23+ at build time, hence this PR adds feature detection. It slightly increases binary size so is best to use sparingly.
It works well for functions with inner loops that are already auto-vectorised. I happen to know vips_(un)premultiply falls into this category, and was pleased to discover this feature provides a ~10% performance improvement on AVX+ CPUs (premultiply is a regularly used code path e.g. when resizing and compositing RGBA images).
I also tested these functions with an AVX2-specific clone but that provided no further benefits over AVX.
There will probably be a few other relatively hot functions that are "low hanging fruit" for this feature, but I wanted to start small.
Some stats gathered via …
=> Introduce support for target_clones attribute, apply to (un)premultiply for ~10% perf improvement

ChangeLog, libvips/foreign/tiff2vips.c
TIFF tile dimensions must be a multiple of 16 ~~and no larger than the image to which they belong (AFAIK, TIFF files don't have a "viewport" concept)~~.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55036 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55148
We might want to backport this to 8.14 also.
=> tiffload: increase sanity checks on tile dimensions

libvips/include/vips/dbuf.h
Hi,
I'm trying to write a libvips binding for deno, so have to map all functions.
the following declaration in `dbuf.h` is present 2 times:
```C
VIPS_API
void vips_dbuf_destroy( VipsDbuf *dbuf );
```
that the only duplicate exported C API.
=> remove duplicated vips_dbuf_destroy declaration in headers,

libvips/create/text.c
Use a private fontmap in `vips_text()` to avoid clashes with other pangocairo users in the same process.
See https://github.com/libvips/libvips/issues/3275
This is against 8.14, but maybe should be master? Or not. It needs a changelog note too, and I guess a version bump somewhere.
=> Private fontmap

ChangeLog, libvips/foreign/tiff2vips.c
Trivial backport of #3287 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport #3287 to 8.14

ChangeLog, libvips/foreign/foreign.c, libvips/foreign/heifload.c, libvips/foreign/heifsave.c, libvips/module/heif.c, meson.build
See: https://github.com/strukturag/libheif/issues/758
=> Ensure compatibility with libheif > 1.14.2

libvips/convolution/meson.build, meson.build
Looks like a copy-paste error (i.e. `orc-0.4` has this minimal version). In-line with the previous Autotools build system, see commit: 0617165c669e94eb3fa0f7b56516f0074089461a.
=> Fix minimum libheif version

meson.build
In-line with the previous Autotools build system, see:
https://github.com/libvips/libvips/blob/d3a1d4df1b5bf22b193280ad4e6cbca6c390a98d/configure.ac#L802
=> Fix minimum OpenEXR version

ChangeLog, libvips/foreign/fits.c
We mustn't write most FITS header keywords more than once. Something like `vips add a.fits b.fits x.fits` was duplicating header keywords.
See https://github.com/libvips/libvips/issues/3273
=> Dedupe fits header

ChangeLog, libvips/conversion/bandjoin.c, libvips/conversion/extract.c
Such images are common and using these two functions for single channel remove/add is also common.
Removing the inner `z` loop allows the compiler to auto-vectorise the outer `x` loop.
Here are some `callgrind` stats for extracting a single channel from a 3 channel 1.4 megapixel image:
Before:
```
28,466,438 (19.51%)  ../libvips/conversion/extract.c:vips_extract_band_buffer [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
After:
```
8,568,560 ( 6.80%)  ../libvips/conversion/extract.c:vips_extract_band_buffer [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
...and some stats for joining a channel to the same 3 channel image:
Before:
```
71,131,060 (36.56%)  ../libvips/conversion/bandjoin.c:vips_bandjoin_buffer [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
After: …
=> Add fast path to extract_band and bandjoin for single uchar, up to ~60% faster for 1 and 3 channels

test/test-suite/test_foreign.py
Resolves these assertion failures:
```
assert 121.0 <= 120
assert 30282.0 <= 30000
```
Targets the 8.14 branch, since Homebrew will probably distribute libjxl 0.8.0 soon.
=> Update lossy `jxlsave` thresholds for libjxl 0.8.0

test/test-suite/test_foreign.py
resvg is slightly stricter regarding SVG parsing and requires that SVG images to have the `xmlns="http://www.w3.org/2000/svg"` namespace, see:
https://github.com/RazrFalcon/resvg/issues/192#issuecomment-569467534
This was noticed on the wasm-vips testsuite. The upcoming v0.0.5 release would likely ship with optional/experimental SVG load support via resvg, see:
https://github.com/kleisauke/wasm-vips/pull/40
https://github.com/kleisauke/libvips/pull/2
=> test: allow `svgload` suite to be run with resvg

ChangeLog, libvips/colour/XYZ2Lab.c
The XYZ to LAB conversion is most commonly used for colour difference calculations and is often their bottleneck. It is also used for the smartcrop and sharpen operations. ICC profile transforms can use LAB as the connection space, although XYZ is usually fast/good enough.
Before:
```
127,870,765 (55.01%)  ../libvips/colour/XYZ2Lab.c:vips_XYZ2Lab_line [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
After:
```
115,085,981 (52.39%)  ../libvips/colour/XYZ2Lab.c:vips_XYZ2Lab_line.avx.0 [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
This adds up to ~4KB to the binary size (debug build, worst case).
This PR also moves the `GOnce` status to live in same scope as the lookup table it protects, which helps provide a small speed-up as its status no longer has to be checked for …
=> colour: add AVX-specific XYZ2Lab implementation, ~10% faster

libvips/foreign/tiff2vips.c
This PR ensures we call `jpeg_calc_output_dimensions()` to populate the `cinfo` struct with dimensions before calling `jpeg_start_decompress()`, like jpegload already does, to prevent libjpeg from allocating memory based on untrusted input.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55111
I haven't added an entry to the changelog yet as we might want to backport this to 8.14.
=> tiffload: sanitise JPEG dimensions before decompression

ChangeLog, libvips/colour/scRGB2XYZ.c
Even at `-O3` it looks like gcc will not inline the call to `vips_col_scRGB2XYZ()`, which I think is due to the function being part of the external/public API, plus is defined in a separate source file.
By manually "inlining" the logic, the performance of almost all RGB colour transformations involving an ICC profile should be improved as XYZ is commonly used for the connection space.
Before:
```
46,873,827 (20.74%)  ../libvips/colour/LabQ2sRGB.c:vips_col_scRGB2XYZ [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
24,180,156 (10.70%)  ../libvips/colour/scRGB2XYZ.c:vips_scRGB2XYZ_line [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
After:
```
33,794,761 (18.18%)  ../libvips/colour/scRGB2XYZ.c:vips_scRGB2XYZ_line [/usr/local/lib/x86_64-linux-gnu/libvips.so.42.17.0]
```
As an …
=> colour: manually inline vips_col_scRGB2XYZ logic, ~2x faster

libvips/colour/CMYK2XYZ.c, libvips/colour/UCS2LCh.c, libvips/colour/XYZ2CMYK.c, libvips/colour/XYZ2scRGB.c, libvips/colour/Yxy2XYZ.c, libvips/colour/scRGB2XYZ.c
These are only used in the same file, and not exported.
Noticed while reviewing PR #3310.
=> colour: mark `->process_line` functions as static

ChangeLog, libvips/foreign/tiff2vips.c
Trivial backport of #3311 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport #3311 to 8.14

libvips/foreign/radiance.c
This PR started with resolving these Clang warnings (commit 5d925edf9257ae298e2eea324769d21348924082):
```
../libvips/foreign/radiance.c:429:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
resolu2str(buf, rp)             /* convert resolution struct to line */
^
../libvips/foreign/radiance.c:446:1: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
str2resolu(rp, buf)             /* convert resolution line to struct */
^
2 warnings generated.
```
But then I realised that these sources were actually bundled. So, I also cleaned up the unused macros/externs (commit …
=> radiance: clean-up and update

.github/workflows/ci.yml, test/test-suite/test_foreign.py
Remove the ICC profile after the image is converted to 16-bit.
Ensures that pixels are correctly interpreted and that the maximum absolute difference remains consistent across different colour management software (i.e. lcms and skcms).
=> CI: fix test failure on macOS

fuzz/meson.build, fuzz/oss_fuzz_build.sh
Tested on the [`libvips-upstream-build-script`](https://github.com/kleisauke/oss-fuzz/tree/libvips-upstream-build-script) branch using:
```console
$ python infra/helper.py build_fuzzers --sanitizer address libvips > build_log.txt
$ mkdir -p tmp
$ python infra/helper.py run_fuzzer --corpus-dir=$PWD/tmp/ libvips jpegsave_buffer_fuzzer
```
See: https://github.com/google/oss-fuzz/issues/9660.
=> Import and simplify OSS-Fuzz build script

ChangeLog, libvips/arithmetic/find_trim.c
disables the median filter to make handling vector art more accurate
see https://github.com/libvips/libvips/discussions/2076
=> add "vector" switch to find_trim

ChangeLog, cplusplus/VImage.cpp, cplusplus/include/vips/VImage8.h
I added two missing functions to the cplusplus wrapper.
Question: Besides `inplace` which I use for pixel modifications afterwards the c++ wrapper is missing methods for functions like `vips_draw_circle1` (with focus on the 1 versions). Would it be okay if I implemented overloads for circle, ... similar to `ifthenelse`. For example 
```
void draw_circle( ... )
{
draw_circle( to_vector( ink), ... ); 
}
```
=> Improve cpp wrapper

.github/workflows/ci.yml
=> CI: switch from libjpeg-turbo to mozjpeg on macOS

fuzz/meson.build, fuzz/oss_fuzz_build.sh
Trivial backport of #3330 to [`8.14`](https://github.com/libvips/libvips/tree/8.14). This allows CIFuzz to run on PRs targeting this branch.
=> Backport #3330 to 8.14 

ChangeLog, libvips/foreign/fits.c
Trivial backport of #3282 to [`8.14`](https://github.com/libvips/libvips/tree/8.14). Corresponds to the backport in Debian:
https://tracker.debian.org/media/packages/v/vips/changelog-8.14.1-3
/cc @ewelot
=> Backport #3282 to 8.14

ChangeLog, libvips/foreign/webpsave.c
Trivial backport of 6715108a2dc45c04634ab0ed545ccac6a63e7592 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport commit 6715108 to 8.14

fuzz/mosaic_fuzzer.cc
Since it's a lot easier in terms of implementation and extracting the image that causes a fuzzer bug. For example:
```bash
$ truncate -s -9 clusterfuzz-testcase-minimized-mosaic_fuzzer
```
Instead of:
```bash
$ dd bs=1 skip=9 if=clusterfuzz-testcase-minimized-mosaic_fuzzer of=mosaic_fuzzer-image
```
=> fuzz: extract the mosaic configuration from the tail

README.md
libheif > 1.14.2 sets those pkg-config variables always to 'yes'.
See: https://github.com/strukturag/libheif/commit/a71e0ee5bac2c0e3373ade9a957ea4f1125c0b80
---
This depends on commit https://github.com/strukturag/libheif/commit/ae0b60fcebddc29b153ae66642aad22dd2bd7fc2 and https://github.com/strukturag/libheif/commit/0c679eaef242f9feecfcbe8a076ca8087a2ecc2e, released in libheif v1.15.1.
=> Update libheif section in README.md

.github/workflows/ci.yml
See: https://github.com/actions/runner-images/pull/7125
=> CI: ensure pkg-config is installed on macOS

ChangeLog, libvips/foreign/heifload.c, libvips/foreign/jp2kload.c, libvips/foreign/jxlload.c, libvips/foreign/magick2vips.c, libvips/foreign/magick7load.c, libvips/foreign/nsgifload.c, libvips/foreign/spngload.c, libvips/foreign/tiff2vips.c, libvips/foreign/vipspng.c, libvips/include/vips/header.h, libvips/iofuncs/header.c, test/test-suite/test_foreign.py
Implements https://github.com/libvips/libvips/discussions/3321
- I added a `VIPS_META_BITS_PER_SAMPLE` flag which contains the bits per pixel of each channel. Hope you are okay with the name. Alternative would be `VIPS_META_BITS_PER_CHANNEL` or `VIPS_META_BITS_PER_BITDEPTH`. Avoided the latter because it is unclear whether it is per channel or the total color depth.
- Support for tiffs via `TIFFTAG_BITSPERSAMPLE`. According to [libtiff reference](https://www.awaresystems.be/imaging/tiff/tifftags/bitspersample.html) a tiff file could contain different bits per sample for each channel but libtiff does not support that, so it is okay to only read the tag once. 
- Support for libpng and libspng. [libpng reference](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-TrialUse/LSB-TrialUse/libpng1 …
=> Bits per sample

ChangeLog, libvips/foreign/webpsave.c, test/meson.build, test/test_timeout_webpsave.c
Trivial backport of #3333 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport #3333 to 8.14

libvips/colour/icc_transform.c
See: https://en.wikipedia.org/wiki/Illuminant_D65#Color_Temperature
=> colour: D65 uses a temperature of 6504K

ChangeLog, libvips/resample/thumbnail.c
i.e. if the image needs to transformed with a pair of ICC profiles.
Resolves: #3159.
=> thumbnail: skip colourspace conversion when needed

ChangeLog, libvips/colour/icc_transform.c
This restores the `vips_image_expected_bands` function and matching logic (which had been removed in commit 1297f2c) to almost its original state.
See: #3361.
=> colour: fix ICC handling of RGB images w/ a monochrome profile

ChangeLog, libvips/colour/icc_transform.c, test/test-suite/test_colour.py
Avoids the need to pack the buffer of floats into lcms's fixed-point formats and ensures full precision internally in lcms.
Resolves: #3150.
Supersedes: #3368.
=> colour: use floating-point APIs of lcms

libvips/foreign/exif.c, libvips/foreign/heifload.c, libvips/foreign/matlab.c, libvips/foreign/nsgifload.c, libvips/foreign/ppmload.c, libvips/foreign/spngload.c, libvips/foreign/vipspng.c, libvips/iofuncs/source.c, libvips/iofuncs/target.c, meson.build
Fixes the specific problems mentioned in #3378 plus a few others I found, and adds a compiler flag (for clang/gcc) to help catch this in the future. Targets the 8.14 branch.
=> Prevent use of void pointer arithmetic

ChangeLog, libvips/foreign/openslideload.c
Before this PR I see:
```
$ vips copy CMU-1.svs[associated=label] x.png
Segmentation fault (core dumped)
```
I suppose the recent refactoring broke this case.
This should probably be cherry-picked for 8.14 as well.
openslideload could use a mild rewrite -- it's still split into two parts.
=> Fix openslide associated

ChangeLog, libvips/foreign/openslideload.c
Trivial backport of #3384 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport #3384 to 8.14

ChangeLog
A few bugfixes since 8.14.1:
- use a private fontmap in vips_text() [jcupitt]
- increase sanity checks on TIFF tile dimensions [lovell]
- ensure compatibility with libheif > 1.14.2 [kleisauke]
- minor doc fixes [jcupitt]
- sanitise dimensions in JPEG-compressed TIFF images [lovell]
- fix target pnm write [ewelot]
- dedupe FITS header write [ewelot]
- fix `strip` parameter in webpsave [jcupitt]
- earlier abort of webpsave on kill [dloebl]
- fix thumbnail of CMYK images with an embedded ICC profile [kleisauke]
- fix ICC handling of RGB images with a monochrome profile [kleisauke]
- ensure ICC transforms keep all precision [kleisauke]
- fix openslideload associated=XXX load [jcupitt]
- fix compatibility with MSVC [SpaceIm]
---
Note to myself: after this PR lands, a release tarball will be …
=> v8.14.2 release proposal

libvips/foreign/tiff2vips.c
Fixes #3403 by doubling the longest overall image edge before rounding up max tile edge to nearest multiple of 256. Also slightly lowers the (still arbitrary) upper limit to 8192 as that is a commonly-used multiple of 16.
EDIT: Should we should commit this to the `master` branch first and let fuzz testing do its thing before backporting?
=> tiffload: slightly relax tile size sanity check

ChangeLog, libvips/foreign/vips2tiff.c
`TIFFClose()` could still use the target after it had been unreffed.
Resolves: #3411.
=> tiffsave: fix use-after-free during pyramid save

libvips/iofuncs/cache.c
This flag could be set during `_build()`.
https://github.com/libvips/libvips/blob/1e1c5ff108d285c5563e126985037f06705eb724/libvips/foreign/foreign.c#L1062-L1068
Before:
```console
$ VIPS_TRACE=1 vips copy x.jpg[access=sequential] x.png
vips cache+: jpegload filename="x.jpg" out=((VipsImage*) 0x1e79010) flags=((VipsForeignFlags) VIPS_FOREIGN_SEQUENTIAL) access=((VipsAccess) VIPS_ACCESS_SEQUENTIAL) -
...
```
After:
```console
$ VIPS_TRACE=1 vips copy x.jpg[access=sequential] x.png
vips cache : jpegload filename="x.jpg" out=((VipsImage*) 0x1b76010) flags=((VipsForeignFlags) VIPS_FOREIGN_SEQUENTIAL) access=((VipsAccess) VIPS_ACCESS_SEQUENTIAL) -
...
```
=> Ensure `load->nocache` is honored

ChangeLog, libvips/conversion/smartcrop.c, test/test-suite/test_conversion.py
This will be useful for sharp, hopefully others, where the input image to crop is already premultiplied.
I've added a couple of new tests for the smartcrop operation when using images with an alpha channel as this wasn't previously covered.
(The context is that I discovered sharp is currently premultiplying twice when using smartcrop, which is making it slower and less accurate.)
=> Add premultiplied option to smartcrop

.github/workflows/ci.yml, README.md, fuzz/oss_fuzz_build.sh, libvips/meson.build, meson.build, meson_options.txt
Avoids having to explicitly disable introspection support if GOI is not installed.
Also, disable it by default for cross builds unless the option was explicitly enabled by the user.
=> Change introspection option to feature type

test/meson.build, test/test_descriptors.c
`/proc/self/fd` might still be available when running on some BSD variants or under emulation. This also ensures that the user will be aware that the test is skipped when not supported.
=> Skip descriptors test at runtime instead

ChangeLog, libvips/foreign/pdfiumload.c
Resolves: #3455.
Used https://pdfium.googlesource.com/pdfium/+/main/samples/simple_no_v8.c as reference, without implementing the additional-action calls:
```
FORM_OnAfterLoadPage
FORM_DoPageAAction
FORM_OnBeforeClosePage
FORM_DoDocumentAAction
```
(which is apparently optional?)
=> pdfiumload: add support for forms

ChangeLog, libvips/deprecated/format.c
We were not registering the vips7 PNG loader when built against libspng.
See https://github.com/libvips/libvips/issues/3466
=> fix vips7 PNG support with libspng

fuzz/oss_fuzz_build.sh
libheif has removed the Autotools build system in favor of CMake.
=> OSS-Fuzz: build libheif with CMake

test/test_descriptors.c
=> test: fix compilation of `test_descriptors.c` on win32

libvips/foreign/pngsave.c, libvips/foreign/spngsave.c
pngsave introspection lists 0 as the default value for bitdepth, but this value does not work:
```
$ vips pngsave
save image to png file
...
bitdepth     - Write as a 1, 2, 4, 8 or 16 bit image, input gint
default: 0
min: 0, max: 16
...
$ vips pngsave k2.jpg x.png --bitdepth 0
(vips:1393285): VIPS-WARNING **: 13:15:09.883: Invalid bit depth in IHDR
(vips:1393285): VIPS-WARNING **: 13:15:09.883: Invalid IHDR data
vips2png: unable to write to target x.png
```
Instead, set the default value to 8. This will be overridden in _build() if bitdepth has not been set.
=> Don't use 0 as a default for pngsave bitdepth

suppressions/lsan.supp
Since https://github.com/strukturag/libheif/commit/8f9ac3d6db58d91ebb36f68244cdc534253b889b libheif creates static conversion tables on initialisation. We rely on libheif implicitly calling `heif_init` for us, so `heif_uninit` is never called and these tables will appear to leak.
Should silence https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58618
=> lsan: suppress leak warnings from libheif

fuzz/oss_fuzz_build.sh
Ensures the 'static' conversion tables are properly cleaned up.
Might resolve https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58618
---
I'm not sure if this will work, as I could not reproduce that issue. I tried:
```console
$ python infra/helper.py build_fuzzers libvips > build_log.txt
$ mkdir -p tmp
$ python infra/helper.py run_fuzzer --corpus-dir=$PWD/tmp/ libvips pngsave_buffer_fuzzer -- -max_total_time=1800
```
(i.e. run the fuzzer for 30 minutes without pressing CTRL+C)
=> OSS-Fuzz: mark `heif_deinit()` as dtor

fuzz/oss_fuzz_build.sh
Alternative to PR #3489, which didn't work since LSan performs the leak check within an `atexit()` handler, which is called prior to any destructors referenced in the `.dtors` ELF section.
<details>
```cpp
#include <stdio.h>      /* puts */
#include <stdlib.h>     /* atexit */
void DoLeakCheck() {
puts("DoLeakCheck()");
}
/* Reference:
* https://github.com/llvm/llvm-project/blob/llvmorg-16.0.4/compiler-rt/lib/lsan/lsan.cpp#L103
* https://github.com/llvm/llvm-project/blob/llvmorg-16.0.4/compiler-rt/lib/lsan/lsan_posix.cpp#L96-L99
*/
void __lsan_init() {
atexit(DoLeakCheck);
}
__attribute__((destructor))
void heif_deinit()
{
puts("heif_deinit()");
}
int main()
{
__lsan_init();
return 0;
}
```
```console
$ clang++ test.cpp
$ ./a.out
DoLeakCheck()
heif_deinit()
``` …
=> OSS-Fuzz: suppress leak warnings from libheif

libvips/resample/templates.h
The current implementation of `signed_fixed_round` returns `-1` for `0` while it seems like it should return `0`. This PR fixes this behavior.
=> Fix signed_fixed_round( 0 )

libvips/foreign/spngsave.c, libvips/foreign/vipspng.c, test/test-suite/test_foreign.py
EXIF support for the PNG writers was added via https://github.com/libvips/libvips/pull/3168 but the `if( vips_image_get_typeof( in, VIPS_META_EXIF_NAME ) ) ...` guard means input must already contain `VIPS_META_EXIF_NAME` for PNG output to also contain EXIF.
This change removes the check, bringing the behaviour of the PNG saver in line with others e.g. JPEG, as well as adding a test cased that would previously have failed.
https://github.com/libvips/libvips/blob/16aeae9e76999d5bd8ac2fb2c4f356bd84b6f7cb/libvips/foreign/vips2jpeg.c#L718-L724
Originally reported at https://github.com/lovell/sharp/issues/3676
=> pngsave: ensure EXIF can be added to PNG output

ChangeLog, libvips/colour/CMYK2XYZ.c, libvips/colour/XYZ2CMYK.c, libvips/colour/icc_transform.c
i.e. when using `vips_colourspace()`. This corresponds to what is stated in the docs:
https://github.com/libvips/libvips/blob/1d29a12d7cb25cfe97676ddd73ce0a079c9e0146/libvips/colour/CMYK2XYZ.c#L206-L208
---
Using the provided image from #3159, this ensures these commands will produce the same image:
```console
$ vips colourspace cmyk.jpeg cmyk-colourspace.jpeg srgb
$ vips icc_import cmyk.jpeg cmyk-icc.jpeg --pcs xyz
$ sha256sum cmyk-{colourspace,icc}.jpeg
06d8fedf015be0dfb55e7476691ea79bb67eba1dce40419db9e81bcdf8bc3fcb  cmyk-colourspace.jpeg
06d8fedf015be0dfb55e7476691ea79bb67eba1dce40419db9e81bcdf8bc3fcb  cmyk-icc.jpeg
```
=> colour: ensure CMYK conversion uses the embedded ICC profile

ChangeLog, libvips/colour/LabQ2sRGB.c, libvips/colour/icc_transform.c
When converting between white points, a chromatic adaptation is required to compensate for a shift in warmness/coolness that would otherwise occur. Use the Bradford transformation method for this purpose.
Resolves: #3479
---
Test case:
```console
$ vipsheader x.v
x.v: 1x1 float, 3 bands, xyz
$ vips getpoint x.v 0 0
77.8137 92.0897 21.2633
$ vips icc_export x.v x2.v --output-profile srgb --pcs xyz
$ vips getpoint x2.v 0 0
255 253 80
$ transicc -d0 -t3 -i '*XYZ' -o libvips/colour/profiles/sRGB.icm
LittleCMS ColorSpace conversion calculator - 5.1 [LittleCMS 2.15]
Copyright (c) 1998-2023 Marti Maria Saguer. See COPYING file for details.
Enter values, 'q' to quit
X? 77.8137
Y? 92.0897
Z? 21.2633 
R=254.9992 G=253.0000 B=80.0025
```
=> colour: ensure chromatic adaptation from/to D50

libvips/foreign/cgifsave.c
Hey there 👋
The current implementation of `vips_foreign_save_cgif_set_transparent` makes every pixel that is the same in the previous frame transparent. This approach is not very optimal.
The main purpose of making pixels transparent is to create sequences of identical indexes that are well compressed with LZW. But when we put a transparent index in the middle of a sequence of identical opaque pixels, we regrade compression instead of improving it.
The approach in this PR improves two things:
– Ensures that all sequences of transparent indexes are at least 2 indexes long. Single transparent pixels do not improve the compression.
– Ensures that sequences of identical indexes aren't broken with transparent indexes. The longer the sequence of identical pixels, the better the compression.
I …
=> Optimize vips_foreign_save_cgif_set_transparent

suppressions/tsan.supp
I noticed that these ThreadSanitizer suppressions were a bit out of sync while investigating issue https://github.com/lovell/sharp/issues/3677 (which I cannot reproduce locally, with or without TSan).
=> tsan: update suppressions

libvips/foreign/jpeg2vips.c
Hey everyone!
I noticed that `vips_jpegload_buffer` copies data to an intermediate buffer even though we already have all the data in memory. This PR checks if the source is mappable to memory, and if so sets its data right to `next_input_byte` eliminating the need to copy. It also replaces the `init_source` and `fill_input_buffer` functions with stubs as we don't need to do anything if we already have all data in `next_input_byte`. And it sets a special implementation of `skip_input_data` that considers that we already read all the data (which we actually did).
=> Avoid copying data in vips_jpegload_buffer

libvips/include/vips/type.h, libvips/iofuncs/type.c
These macros are available since GLib 2.26.
=> type: prefer use of `G_DEFINE_*` macros

libvips/deprecated/im_convsub.c, libvips/deprecated/im_line.c, libvips/deprecated/im_slice.c, libvips/deprecated/im_thresh.c, libvips/foreign/magick7load.c, libvips/iofuncs/buf.c, libvips/iofuncs/init.c, meson.build
Fix a few warnings from clang. With this PR, libvips builds cleanly on macOS and on Ubuntu in debug and release mode, and pytest passes.
=> Fix clang warnings

libvips/iofuncs/init.c, libvips/meson.build
Should be safe, we no longer depend on `G_MODULE_SUFFIX`.
=> Use `.dylib` as dynamic module extension on macOS

README.md, meson.build
I've had a few users forget to enable release mode and then have performance issues. meson defaults to a debug build, so it's an easy mistake to make.
This PR makes meson default to a release build.
=> Release build by default

ChangeLog, libvips/colour/icc_transform.c
=> colour: improve ICC compatibility check for CMYK images

ChangeLog
This will be the last 8.14.x release barring unforeseen circumstances.
List of changes since 8.14.2:
- fix ICC handling of greyscale images with a incompatible profile [kleisauke]
- fix use-after-free during tiff pyramid save [kleisauke]
- fix vips7 PNG load and save when using libspng [jcupitt]
- tiffload: slightly relax tile size sanity check [lovell]
- heifsave: limit dimensions to a maximum edge of 16384 [lovell]
- colourspace: ensure CMYK conversion uses the embedded ICC profile [kleisauke]
- ensure chromatic adaptation during icc_{im,ex}port() [kleisauke]
- improve ICC compatibility check for CMYK images [kleisauke]
Changes to the Windows binaries:
- Produce debug info in PDB format by default.
- Reintroduce support for dzsave via libarchive …
=> v8.14.3 release proposal 

libvips/foreign/magick.c
This image format uses the standard TIFF header, so a special sniffer is needed to prevent *magick from trying to load the buffer through its TIFF loader.
=> Add a magick sniffer for CR2

ChangeLog, libvips/foreign/svgload.c
`g_utf8_find_next_char()` might return NULL when called with a non-NULL second argument, indicating that the end of the string has been reached.
=> svgload: fix null-pointer dereference

ChangeLog, libvips/resample/shrinkh.c, libvips/resample/shrinkv.c, test/test-suite/test_create.py
shrinkv used to always fetch single lines from the input image. This kept memuse low, but could cause severe overcomputation if earlier pipeline stages performed coordinate transforms.
This PR makes it fetch in larger chunks, up to the tile height, or more for very large shrinks. Larger tiles means less upstream overcomputation.
See https://github.com/libvips/libvips/issues/3600
=> Better shrinkv chunking

ChangeLog, libvips/foreign/heifload.c, libvips/foreign/heifsave.c
This would prevent a `NULL` string from being printed with `vsnprintf` in case of a write error.
See: #3588.
=> heif{load,save}: guard against `NULL` strings

ChangeLog, libvips/foreign/pdfiumload.c
Hey there 👋
Long story short 🙂
Here's a PDF file containing multiple pages of different sizes: https://img.darthsim.me/R2rprQ86Q6.pdf.
Here's how vips renders it: https://img.darthsim.me/mJ8SkNJb_m.png
As you can see, the pages after the first one are rendered incorrectly. That's because vips sets a tile size equal to the first page size and renders a full page in each tile. Also, there are leftovers from the previous pages because vips doesn't clear the region before rendering pages in it.
Luckily, despite what comments in `pdfiumload.c` say, PDFium allows rendering a part of the page.
This PR fixes the `pdfiumload` behavior to work in sequential mode and render part of a page in each tile. Also, I added resetting of the output region to remove previous pages' leftovers.
Here's how vips …
=> pdfiumload: fix rendering multiple pages with different sizes

libvips/foreign/pdfiumload.c
Followup for https://github.com/libvips/libvips/pull/3594
Test PDF: https://img.darthsim.me/R2rprQ86Q6.pdf
Test command: `vips copy /images/pdf8.pdf[dpi=150] /images/pdf8.png`
Current result: https://img.darthsim.me/VGXJUWOj56.png
Fixed result: https://img.darthsim.me/H_E5_4O7GJ.png
=> pdfiumload: fix forms rendering

cplusplus/VImage.cpp, doc/binding.md, doc/binding.xml, libvips/colour/profile_load.c, libvips/conversion/copy.c, libvips/foreign/dzsave.c, libvips/foreign/niftiload.c, libvips/foreign/niftisave.c, libvips/include/vips/object.h, libvips/iofuncs/cache.c, libvips/iofuncs/header.c, libvips/iofuncs/object.c, libvips/iofuncs/operation.c, libvips/iofuncs/sourcecustom.c, libvips/iofuncs/targetcustom.c, libvips/iofuncs/thread.c, libvips/iofuncs/threadpool.c, libvips/iofuncs/type.c, libvips/iofuncs/vips.c
These macros are available since GLib v2.30 and v2.32, respectively.
=> Prefer use of `G_VALUE_INIT` / `G_PRIVATE_INIT`

cplusplus/VImage.cpp
Regressed since commit 873ae7305f07a3a1493249148c1d0f0a0407f797.
=> cplusplus: ensure `operator-` is not no-op

ChangeLog, libvips/foreign/jxlsave.c, libvips/foreign/magick2vips.c, libvips/foreign/magick7load.c
Some versions of GraphicsMagick can report rgb colourspace for some mono BMPs. In turn, this can trigger a crash in jxlsave.
See https://github.com/libvips/libvips/issues/3619
@kleisauke this is against master, though since it's a crash (under some circumstances) maybe it should be cherrypicked for 8.14?
=> Fix a crash in jxlsave

fuzz/oss_fuzz_build.sh
This became redundant after strukturag/libheif#891.
=> OSS-Fuzz: remove redundant sed replacement

ChangeLog, libvips/colour/icc_transform.c, meson.build, test/test-suite/test_create.py
The ICC import and export line process functions were using `SIZEOF_PEL` on the input and output images, but the image they actually handle may have had alpha removed. This could cause SEGVs with formats like CMYKA.
This PR makes them use the band count that LCMS will see.
Also bump version, and fix a test fail.
See https://github.com/libvips/libvips/discussions/3640
=> fix crash with alpha handling for icc import and export

libvips/foreign/heifload.c, libvips/foreign/heifsave.c, libvips/foreign/pforeign.h, meson.build
a little safer, and helps libvips work with some versions of libheif
=> call heif_init on heif startup

ChangeLog, libvips/foreign/jxlsave.c, libvips/foreign/magick2vips.c, libvips/foreign/magick7load.c
Trivial backport of #3620 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
=> Backport #3620 to 8.14

ChangeLog
A few bugfixes since 8.14.4:
- fix a crash with alpha plus icc_import and icc_export [jcupitt]
- fix a crash in jxlsave [jcupitt]
=> v8.14.5 release proposal

ChangeLog, libvips/colour/XYZ2scRGB.c, libvips/colour/sRGB2scRGB.c, libvips/colour/scRGB2BW.c, libvips/colour/scRGB2XYZ.c, libvips/colour/scRGB2sRGB.c, libvips/conversion/bandjoin.c, libvips/conversion/composite.cpp, libvips/conversion/flatten.c, libvips/conversion/premultiply.c, libvips/conversion/unpremultiply.c, libvips/include/vips/header.h, libvips/iofuncs/header.c, test/test-suite/test_colour.py
Hey there 👋
This PR changes the alpha range of scRGB to `0.0 - 1.0` as discussed here https://github.com/libvips/libvips/issues/3621#issuecomment-1691925346
=> Use alpha range of 0.0-1.0 for scRGB

ChangeLog, libvips/foreign/tiff2vips.c
Hey there 👋
This PR adds support for 16-bit float TIFFs. I didn't use `_Float16` because it's not generally available.
Here are some test images: [tiff3_f16_f32.zip](https://github.com/libvips/libvips/files/12442891/tiff3_f16_f32.zip)
=> tiffload: add 16-bit float support

libvips/foreign/dzsave.c, libvips/iofuncs/type.c, libvips/iofuncs/vips.c, meson.build
Hey there 👋
libvips checks UTF-8 string validity using `g_utf8_validate` in several places and ignores invalid strings or replaces them with `<invlaid utf-8 string>`. This leads to cases where the whole string is ignored or replaced because of a single invalid character. Instead, we could use the `g_utf8_make_valid` function introduced in GLib 2.52 to replace invalid characters.
GLib 2.52 was released 6 years ago (even Debian Buster has GLib 2.58) so increasing the minimum required version to 2.52 shouldn't be a problem.
=> Fix invalid UTF-8 strings instead of ignoring them

libvips/foreign/pforeign.h, libvips/iofuncs/init.c, libvips/iofuncs/thread.c
The minimum required GLib version was raised to 2.52, making these guards unnecessary.
=> Remove a couple of redundant GLib version guards

libvips/foreign/vips2tiff.c, libvips/iofuncs/object.c
`g_slist_sort()` uses the same implementation as `g_slist_sort_with_data()` within GLib; hence, the function's signature must align with that of `GCompareDataFunc`.
Helps wasm-vips, where function pointer cast issues fails at runtime.
---
SO answer https://stackoverflow.com/a/14044244 might be relevant here.
=> vips2tiff: fix function pointer cast issue

libvips/foreign/archive.c
On POSIX-compliant operating systems (e.g. Linux, macOS), there is no difference between binary mode and text mode, but Windows transforms line feeds ("\n") to "\r\n" sequences during write operations, resulting in corrupted images.
```console
$ pngcheck -v x_files/10/0_0.png
File: 0_0.png (41180 bytes)
File is CORRUPTED.  It seems to have suffered Unix->DOS conversion.
ERRORS DETECTED in 0_0.png
```
---
Regressed since commit 00e4047ff9a223132adfdf874f723139e399c6f2 for non-images (e.g. XML/JSON files), corrupted images were written since commit 7ac29928123a276e126c803147db75966afb49c4 (prior to that, `VIPS_FOREIGN_DZ_CONTAINER_FS` images were written using `vips_image_write_to_file()`).
=> archive: ensure files are written in binary mode

README.md
Hey there 👋
I just noticed that one of the most popular tools that uses libvips–imgproxy–is not enlisted in README. I believe this should be fixed 😅
=> Mention imgproxy in README

ChangeLog, libvips/include/vips/thread.h, libvips/iofuncs/sinkdisc.c, libvips/iofuncs/sinkscreen.c, libvips/iofuncs/threadpool.c
It's in the headers already, just not in the library binary. I'd like to use it in vipsdisp for background workers.
Does this have any consequences? I think it's pretty safe, and these functions are already documented.
=> add threadset to the public API

libvips/foreign/heifsave.c, libvips/foreign/spngsave.c, libvips/foreign/vipspng.c, libvips/foreign/webpsave.c
Test cases:
```console
$ vips copy x.jpg x.webp[profile=none]
Segmentation fault (core dumped)
$ vips copy x.jpg x.png[profile=none]
Segmentation fault (core dumped)
$ VIPS_LEAK=1 vips copy x.jpg x.avif[profile=libvips/colour/profiles/sRGB.icm]
vips_threadset_free: peak of 15 threads
1 VipsArea alive
0x7f6648001260 count = 1, bytes = 480
memory: high-water mark 25.69 MB
```
Regressed since commit 32ddfe702de0617eaaf390ac240e1caf40ba7217. This bug did not affect any released versions.
=> Guard against `NULL`-blobs during `*_add_custom_icc`

libvips/resample/presample.h, libvips/resample/reduceh.cpp, libvips/resample/reducev.cpp, libvips/resample/templates.h
- De-duplicate `n_points` calculations.
- Extract the various filters in inline functions.
- Merge the `calculate_coefficients*` functions into a single one.
- Simplify `reduce_sum()`.
Split from: #3532.
=> reduce{h,v}: simplify coefficients handling

libvips/resample/reduceh.cpp, libvips/resample/reducev.cpp, libvips/resample/templates.h
This PR ensures that `reduce{h,v}_notab` is in-line with `reduce{h,v}_float_tab`, i.e. no rounding. 
`vips_reduce_make_mask()` needed a slight refactor, since the `*_notab` functions requires a `long double` intermediate instead of a `double`. Additionally, as part of the process, I consolidated the `calculate_coefficients_*` functions into a single function.
See commit https://github.com/kleisauke/pyvips-issue-148/commit/c6d0049686b97f97feb5a8a5ade14aa2ad905e73 for the ResampleScope difference.
Supersedes: #3501.
=> reduce{h,v}: remove rounding from the double paths

fuzz/oss_fuzz_build.sh
libheif removed `-lstdc++` from their pkg-config file with commit: https://github.com/strukturag/libheif/commit/27097a655d5e36bd57361207910cb6ba883256bc
---
See build logs at https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libvips for why this is necessary.
```diff
--- a/oss-fuzz-log-10-10-2023.txt
+++ b/oss-fuzz-log-10-11-2023.txt
@@ -15649,8 +15643,8 @@ Step #21 - "compile-libfuzzer-address-x86_64": Run-time dependency libhwy
Step #21 - "compile-libfuzzer-address-x86_64": WARNING: Static library 'pdfium' not found for dependency 'pdfium', may not be statically linked
Step #21 - "compile-libfuzzer-address-x86_64": Run-time dependency pdfium found: YES 4901
Step #21 - "compile-libfuzzer-address-x86_64": Run-time dependency libheif found: YES 1.16.2
-Step #21 - …
```
=> OSS-Fuzz: adapt sed replacement for libheif

fuzz/oss_fuzz_build.sh, meson.build
libheif is a C++ library that exposes a C API. When it's built statically, the linker must also link with the C++ stdlib, which is done automatically when using a C++ compiler.
Prior to commit strukturag/libheif@27097a6, libheif included libstdc++ in the `Libs.private` field of their .pc file. This meant it was exposed in the case of static linking, enabling a build system for a C application to link against libstdc++ as needed. However, this was not portable as libstdc++ is specific to the GNU toolchain, when using Clang, you can optionally use libc++.
This PR aims to find symbols in libheif using a C++ compiler, ensuring that Meson can confirm their availability at link-time, even when libheif is statically built.
=> Ensure libheif symbols are found when built statically

ChangeLog
A test release for 8.15.
Changes for this release:
- add support for target_clones attribute [lovell]
* use with (un)premultiply for ~10% perf gain on AVX CPUs
* use with XYZ to LAB colourspace conversion for ~10% perf gain on AVX CPUs
- add fast path to extract_band and bandjoin for uchar images [lovell]
- reduce `vips_sharpen` max `sigma` to 10 [lovell]
- inline scRGB to XYZ colourspace conversion, ~2x faster [lovell]
- set "interlaced=1" for interlaced GIF images [kleisauke]
- add @line_art to find_trim [miltoncandelero]
- improve C++ binding [MathemanFlo]
* add `inplace()` / `VImage::new_from_memory_copy()`
* add overloads for `draw_*()` / `VImage::thumbnail_buffer()`
- allow negative line spacing in text [donghuikugou]
- add VIPS_META_BITS_PER_SAMPLE metadata, deprecate the …
=> v8.15.0-rc1 release proposal

meson.build
This reverts commit da5cb2206ad25edd5d6f5a6ffa9352f7ae807f5f.
This allow build on RHEL-7 and RHEL-8
=> Revert "raise librsvg minver to 2.48 (#3574)"

libvips/foreign/heifsave.c, meson.build
Discovered whilst testing https://github.com/libvips/libvips/issues/3718, targets the 8.15 branch.
As of commit https://github.com/strukturag/libheif/commit/c95ed71a67003a49ddfe2e1bf810bfc96e61d333 libheif requires errors, including _"Ceci n'est pas une erreur"_, to have a message.
As of commit https://github.com/strukturag/libheif/commit/bea5f4b47def81a669f1bc0c1415f02a8b9f595b libheif provides a new `heif_error_success` API as the canonical way to represent _"Ceci n'est pas une erreur"_.
=> heifsave: errors must have a message in libheif 1.17.0+

libvips/foreign/dzsave.c, test/test-suite/test_foreign.py
See for context #3718, targets the 8.15 branch.
<details>
<summary>Test cases</summary>
Commit a3d88a326d83192bcfbcecb7881e95e922944ce3:
```bash
$ vips black x.png 1000 1000
$ vips dzsave x.png x.dzi --suffix=".jpeg[Q=100]"
$ ls x.dzi_files/0/
'0_0.jpeg[Q=100]'
$ ls x.dzi_files/0/
0_0.jpeg
```
Commit 94e80e1cd27ad71a4fc490eb896c5eaf30bead6f:
```bash
$ vips black x.png 1000 1000
$ vips dzsave x.png x.dzi --imagename hello
$ [ -e "hello_files/0/0_0.jpeg" ] && echo "OK" || echo "FAIL"
FAIL
$ [ -e "hello_files/0/0_0.jpeg" ] && echo "OK" || echo "FAIL"
OK
```
Commit bdeda2bcbd01c9a88c3dae51bff6ab78b0974b5f:
```bash
$ vips black x.v 1000 1000
$ vips embed x.v x.png 1000 1000 2000 2000 --extend white
$ vips dzsave x.png x.dzi --skip-blanks 0
$ [ -e "x.dzi_files/11/0_0.jpeg" ] && echo "FAIL" || …
```
=> dzsave: fix a couple of minor bugs

libvips/foreign/magick.c, meson.build
This makes our magick sniffer aware of the various magic signatures defined with the `MagickCoderHeader` macro in ImageMagick.
See for context #3734, targets the 8.15 branch.
=> magick: prefer use of `GetMagicInfo()`

ChangeLog
A test release for 8.15. This release candidate will likely be last or next-to-last before the formal 8.15.0 release.
Changes since -rc1:
https://github.com/libvips/libvips/compare/v8.15.0-rc1...66ee9f1
=> v8.15.0-rc2 release proposal

libvips/conversion/composite.cpp
Curiously, this only seems to happen with `-std=c++11` (commit 5482ead701b29cbfd3eeab6e91603d972b3b8850 / c264c54b351c8faac8e6f2db42413226a8428e16), it compiles fine when that's omitted.
Resolves: #3749.
=> composite: ensure compilation on i386

ChangeLog
Release notes:
https://www.libvips.org/2023/10/10/What's-new-in-8.15.html
Changes for this release:
- add support for target_clones attribute [lovell]
* use with (un)premultiply for ~10% perf gain on AVX CPUs
* use with XYZ to LAB colourspace conversion for ~10% perf gain on AVX CPUs
- add fast path to extract_band and bandjoin for uchar images [lovell]
- reduce `vips_sharpen` max `sigma` to 10 [lovell]
- inline scRGB to XYZ colourspace conversion, ~2x faster [lovell]
- set "interlaced=1" for interlaced GIF images [kleisauke]
- add @line_art to find_trim [miltoncandelero]
- improve C++ binding [MathemanFlo]
* add `inplace()` / `VImage::new_from_memory_copy()`
* add overloads for `draw_*()` / `VImage::thumbnail_buffer()`
- allow negative line spacing in text [donghuikugou]
- add …
=> v8.15.0 release proposal 

libvips/foreign/heifsave.c
Hey there 👋
Some AVIF encoders in libheif support the `threads` parameter. Its default value is `4` by default but it's almost never optimal. This PR sets it to the `vips_concurrency_get()` since it is the level of parallelism a Vips user wants.
On my machine (Apple M1, 10 cores), this speeds up the conversion of a 7360x4912 JPEG to AVIF from 11s to 6s.
=> heifsave: set `threads` to vips_concurrency_get()

ChangeLog, libvips/resample/reduceh_hwy.cpp
Hey there 👋
`TableLookupBytes` doesn't work on SSE2 targets. `TableLookupBytesOr0` is a wrapper over `TableLookupBytes`. On targets higher than SSE2, it just calls `TableLookupBytes`, so there's no speed loss. On SSE2, it adds some code for zeroing. https://github.com/google/highway/blob/1.0.7/hwy/ops/x86_128-inl.h#L1590-L1602
Fixes https://github.com/imgproxy/imgproxy/issues/1223
=> reduceh: fix HWY path on SSE2

libvips/foreign/jxlload.c, libvips/foreign/jxlsave.c
Hey there 👋
Apple added JPEG XL support to macOS, iOS, and Safari, and lots of people want to try it. Unfortunately, JPEG XL support in libvips is pretty limited right now, and this PR fixes this.
JPEG XL has two file formats:
1. A "naked" codestream that contains only image/animation data without any additional metadata.
2. An ISOBMFF-based container that may contain additional metadata like EXIF and XMP.
Currently, `jxlload` doesn't extract EXIF/XMP from the container format, and `jxlsave` doesn't save files JXL in the container format. This PR adds extracting EXIF/XMP from ISOBMFF boxes and saving it to ISOBMFF boxes.
Currently, `jxlload` fails when meets the end of input. But in some cases, libjxl tries to read while the input is opened. So instead of returning an error on the end of …
=> Improve JPEG XL support

ChangeLog, libvips/foreign/jxlload.c, libvips/foreign/jxlsave.c, meson.build, test/test-suite/test_foreign.py
See https://github.com/libjxl/libjxl/blob/v0.9.x/CHANGELOG.md
> ```md
> ### Removed
>  - decoder API: the signature of `JxlDecoderGetColorAsEncodedProfile`,
>    `JxlDecoderGetICCProfileSize`, and `JxlDecoderGetColorAsICCProfile`
>    changed: a deprecated unused argument was removed.
> ```
While we're here, prefer use of `JxlEncoderDistanceFromQuality`.
> ```md
> ### Added
>  - encoder API: new function `JxlEncoderDistanceFromQuality` for convenience to
>    calculate a `distance` given a `quality`
> ```
And backport commit 4caf924b153b4cc329c931b8dd46f8faaa05216a.
=> Fix build with upcoming libjxl 0.9

libvips/include/vips/meson.build, meson.build
I often find myself checking the version number of detected packages, it might be useful to have this in the summary.
Sample output:
```
enable RAD load/save              : YES
enable Analyze7 load/save         : YES
enable PPM load/save              : YES
enable GIF load                   : YES
Optional external packages
use fftw for FFTs                 : YES 3.3.10
SIMD support with highway         : YES 1.0.7
accelerate loops with ORC         : NO NO
ICC profile support with lcms     : YES 2.14
zlib                              : YES 1.2.13
text rendering with pangocairo    : YES 1.51.0
font file support with fontconfig : YES 2.14.2
EXIF metadata support with libexif: YES 0.6.24
External image format libraries
JPEG load/save with libjpeg       : YES 2.1.5
JXL load/save with libjxl …
```
=> try putting version numbers into the meson summary

libvips/foreign/pdfiumload.c
Currently annotations are not rendered, this is very unexpected behavior as with other tools (imagemagick) or dependencies (poppler) it will be drawn. 
The flag `FPDF_ANNOT` enables render of annotations, this results in the same behavior as with poppler.
I used the annotation example files from pdfium to test it: https://pdfium.googlesource.com/pdfium_tests/+/refs/heads/main/pdfium/annots/
=> fix(pdfium): render pdf annotations

README.md
There shouldn't be a space in front of a colon. This practice even has a name ("Plenken"), see: https://en.m.wikipedia.org/wiki/Plenken
=> fix: punctuation in readme

libvips/resample/thumbnail.c
Sorry for another tiny PR, I missed it in the last one.
This sentence was missing a verb.
=> fix: typo (missing verb)

ChangeLog, libvips/resample/thumbnail.c, test/test-suite/test_resample.py
After #f807d7b, `icc_export` and `icc_transform` would keep 16 bit images as 16-bit images. We didn't make a matching change to `thumbnail`, so 8.15 started making 16-bit thumbnails of 16-bit images, with no way to request 8 bits.
This PR adds `depth 8` to all `icc_*()` to make the behaviour match 8.14 (and tries to improve line breaks).
See https://github.com/libvips/libvips/issues/3830
=> thumbnail should always export as 8 bit

ChangeLog, libvips/foreign/pdfiumload.c, libvips/foreign/popplerload.c, libvips/foreign/svgload.c, test/test-suite/test_foreign.py
Trivial backport of #3827 to [`8.15`](https://github.com/libvips/libvips/tree/8.14). 
While doing this, I noticed that `webpload` and `resize` just uses `0.0` as minimum scale factor:
https://github.com/libvips/libvips/blob/3fb194893d0d4a37b5646e70da7b57fa4aabab01/libvips/foreign/webpload.c#L191-L196
https://github.com/libvips/libvips/blob/3fb194893d0d4a37b5646e70da7b57fa4aabab01/libvips/resample/resize.c#L328-L333
Which might be a bit simpler, so I also included commit  62eaf9db377cd0da682b42067a209c5ed16c9eb0 in this backport, which applies the same change to `pdfload` as well.
=> Backport #3827 to 8.15

ChangeLog, libvips/foreign/heifload.c, libvips/include/vips/util.h
Since this message is emitted during an AVIF roundtrip, its severity does not warrant a warning. So, let's downgrade it to a `g_info()`.
See: #2734 and kleisauke/wasm-vips#62.
=> heifload: don't warn on images with nclx profiles

ChangeLog, libvips/iofuncs/sbuf.c, test/test-suite/test_foreign.py
Fixes https://github.com/libvips/libvips/issues/3842 and adds the provided example as a test case.
=> ppmload: ensure multi-line comments are skipped

libvips/foreign/jp2ksave.c, libvips/foreign/jxlsave.c
There's currently an error in the documentation for `vips jxlsave`:
```
save image in JPEG-XL format
usage:
jxlsave in filename [--option-name option-value ...]
where:
in           - Image to save, input VipsImage
filename     - Filename to load from, input gchararray
```
"Filename to load from" should be "Filename to save to", just like with `pngsave`.
=> Fix jxlsave.c description

ChangeLog, libvips/conversion/arrayjoin.c, libvips/conversion/insert.c, libvips/foreign/foreign.c, libvips/include/vips/internal.h, libvips/iofuncs/sinkdisc.c
If the operation before arrayjoin was something that just forwarded a pointer, we could be left with dangling memory references in some cases.
Also some tiny comment adjustment and formatting changes.
thanks TheEssem
see https://github.com/libvips/libvips/issues/3835
=> fix arrayjoin with some pipelines

.github/workflows/ci.yml
The brew meson might not be using the same python as the rest of brew, so installing it that way can conflict. Instead, install meson with pip so we get a version for our python.
=> don't install meson with brew

libvips/convolution/convi_hwy.cpp, libvips/resample/reduceh_hwy.cpp, libvips/resample/reducev_hwy.cpp, meson.build
Commit 4246c062f290f1c02b54dfd769b37254b4a6f843 removes the restriction of not crossing the 128-bit block boundaries on RVV/SVE (as mentioned in https://github.com/libvips/libvips/pull/3618#discussion_r1345598849).
Commit 4c32343894c15e2132cb354ce018f2757a2c56c5 prefers use of `Dup128VecFromValues` instead of `LoadDup128` to improve the codegen on some targets.
Both improvements are conditionally guarded for Highway 1.1.0 to avoid having to bump our minimum required version.
=> Highway improvements

libvips/foreign/webpsave.c
Adds the ability to configure whether or not the "auto-filter" feature from libwebp is used when encoding lossy WebPs, This is put behind a new optional argument/toggle called/named "smart_deblock" in libvips.
It's described by Google as doing the following: "This algorithm will spend additional time optimizing the filtering strength to reach a well-balanced quality."
Note this process is quite slow for the quality gains it achieves.
Also a warning I must give that I apologize for is I am not in a proper position to actually compile libvips and test it with this new code, however this all seems straight forward enough and anyone who is able to can confirm if this works by checking the outputs when changing the `smart_deblock` boolean.
If there's anything I missed or concerns about details …
=> WebP Save: add argument for using "auto-filter"/"smart_deblock" encoding feature.

ChangeLog, libvips/include/vips/connection.h, libvips/iofuncs/target.c
On MSVC, `off_t` and `lseek()` are limited to signed 32-bit offsets, which limits their capability to handle files larger than 2GB.
To support saving TIFF files that exceed this size, replace their use with `gint64` and `vips__seek()`, where the latter uses `_lseeki64()` internally.
See: https://github.com/conan-io/conan/issues/15578.
=> tiffsave: ensure large file support (>2GB) on MSVC

ChangeLog, libvips/foreign/magick.c
Some files types are very slow to detect in imagemagick, and not very useful. Block them.
Example:
```
$ /usr/bin/time -f %M:%e vipsheader frank.avi 
frank.avi: 720x576 uchar, 3 bands, srgb, magickload
10691072:16.09
```
10gb of memory and 16s of wall clock time.
See https://github.com/libvips/libvips/issues/3838
=> add an imagemagick blocklist

ChangeLog, libvips/include/vips/image.h, libvips/include/vips/vips.h, libvips/iofuncs/init.c, libvips/iofuncs/util.c, test/test_cli.sh
and bump the default to 100m
see https://github.com/libvips/libvips/issues/3865
thanks @AKlaus
Usage:
```
$ VIPS_MAX_COORD=120 vips black x.v 1000 1000
```
Will fail with a range of terrible errors. You can use unit dimensions in the size, for example:
```
$ VIPS_MAX_COORD=1g vips black x.v 1000 1000
```
Or use:
```
$ vips black x.v 1000 1000 --vips-max-coord 1g
```
=> make MAX_COORD configurable

ChangeLog, meson.build
Fixes https://github.com/libvips/libvips/issues/3876
This allows libvips to be built with buggy versions of LLVM where the compiler but not linker supports this feature, and therefore prevents an "undefined symbol: __cpu_model" error at link time.
CI before:
- Linux/gcc: Checking if "Has target_clones attribute" compiles: YES 
- Linux/clang14: Checking if "Has target_clones attribute" compiles: YES 
- macOS/xcode14: Checking if "Has target_clones attribute" compiles: NO 
CI after:
- Linux/gcc: Checking if "Has target_clones attribute" : links: YES 
- Linux/clang14: Checking if "Has target_clones attribute" : links: YES 
- macOS/xcode14: Checking if "Has target_clones attribute" : links: NO 
=> Check linker supports target_clones attribute

.github/workflows/ci.yml, ChangeLog, libvips/conversion/byteswap.c, libvips/foreign/foreign.c, libvips/foreign/ppmload.c, libvips/foreign/ppmsave.c, libvips/include/vips/util.h, libvips/iofuncs/target.c, test/test-suite/helpers/helpers.py, test/test-suite/test_foreign.py, test/test_formats.sh, test/variables.sh.in
Saving a scrgb image as `x.pfm` ought to save as scrgb.
Referring issue https://github.com/libvips/libvips/issues/3885
See also https://github.com/libvips/libvips/pull/3623 for when we improved scrgb for `tiffsave`.
=> Improve scrgb handling for ppmsave

ChangeLog, libvips/conversion/addalpha.c, libvips/conversion/bandjoin.c, libvips/conversion/conversion.c, libvips/conversion/meson.build, test/test-suite/test_conversion.py
This PR turns `vips_addalpha` into a fully-fledged VipsOperation so that bindings may call it using the same mechanisms they use to call other operations. See https://github.com/libvips/lua-vips/pull/46#issuecomment-1983202875 for a discussion as to why this may be desired.
I'm largely new to C and the GObject system, so I'm not sure whether this is the correct (let alone the best) way to implement this change. For example, I'm not sure whether the new operation should subclass VipsBandary or VipsConversion — on one hand, it is an operation of the same type as the other bandary operations (it simply manipulates bands); on the other, it doesn't use any of the machinery defined by VipsBandary and subclassing VipsConversion would be sufficient.
=> Make `vips_addalpha` a VipsOperation

libvips/foreign/jpegload.c
Hello,
The `jpegload` doc displayed in CLI states that the max shrink value is 16
```bash
shrink       - Shrink factor on load, input gint
default: 1
min: 1, max: 16
```
Trying to put a shrink factor > 8 and <= 16 triggers a `error buffer: VipsFormatLoadJpeg: bad shrink factor 16`
From other parts of the doc, it seems that the max shrink factor should be 8.
=> Jpegload, put the max shrink value to 8 instead of 16

fuzz/oss_fuzz_build.sh
In favor of libspng, which is preferred by libvips.
Targets the 8.15 branch to ensure that CIFuzz continues to work after PR https://github.com/google/oss-fuzz/pull/11772 is merged.
=> OSS-Fuzz: remove redundant libpng build

libvips/convolution/convi_hwy.cpp, libvips/resample/reducev_hwy.cpp
On AVX2 and AVX3 architectures, for vectors of 32 bytes or larger, the semantics of the `InterleaveWhole{Lower,Upper}` operations do not align with the non-whole variants.
https://github.com/google/highway/blob/1.1.0/hwy/ops/generic_ops-inl.h#L392-L399
Ensure we only use `InterleaveWhole*` on RVV/SVE.
This partially reverts commit 9924904cc3146bdd41bfcd2a3beaf075c4f76966.
=> convi/reducev: fix HWY >= 1.1.0 paths on AVX2/AVX3

libvips/foreign/exif.c
Hey there 👋
Some of our users showed us AI-generated images that have pretty large EXIF data (around 4 Mb). All-in-all the images are ok, and their EXIF can be decoded successfully with higher limits, so I'd offer to increase the EXIF size limit to 32 Mb.
=> Increase EXIF size limit to 32Mb

ChangeLog, libvips/foreign/spngload.c, libvips/foreign/vipspng.c
The condition was inverted for spng, also sync libpng load while we are here.
=> pngload: disable ADLER32/CRC checking in non-fail mode

fuzz/gifsave_buffer_fuzzer.cc, fuzz/jpegsave_buffer_fuzzer.cc, fuzz/jpegsave_file_fuzzer.cc, fuzz/mosaic_fuzzer.cc, fuzz/pngsave_buffer_fuzzer.cc, fuzz/sharpen_fuzzer.cc, fuzz/smartcrop_fuzzer.cc, fuzz/thumbnail_fuzzer.cc, fuzz/webpsave_buffer_fuzzer.cc
This reverts commit cb1634dd31866bdb6cf3554bbc87e01f87f49f25 since https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24383 was fixed with commit df26bd1e46c67ed7745996627ca0d83e5a6d678d instead.
---
Note that timeouts and OOMs are only reported once per fuzz target, so this may cause duplicate reports.
https://google.github.io/oss-fuzz/faq/#how-do-you-handle-timeouts-and-ooms
=> Revert "block fuzz data over 100kb"

ChangeLog, libvips/foreign/vips2jpeg.c, libvips/foreign/vips2tiff.c
Unless saving with a quality setting of 90 or higher, or when chroma subsampling is explicitly disabled (`subsample_mode=off`).
This ensures compatibility with jpegli, which uses 4:4:4 by default.
See: https://github.com/libvips/libvips/issues/3922.
=> jpegsave: explicitly use 4:2:0 subsampling by default

cplusplus/include/vips/vips8
Hi!
Currently, when including libvips in a Qt-Using C++ project, you may get errors like:
``` 
/usr/include/glib-2.0/gio/gdbusintrospection.h:155:24: error: expected ‘;’ at end of member declaration
GDBusSignalInfo     **signals;
^
/usr/include/glib-2.0/gio/gdbusintrospection.h:155:32: error: expected ‘:’ before ‘;’ token
GDBusSignalInfo     **signals;
^
``` 
This is due to Qt enabling special keywords which GLib uses as variable names. It can easily worked around with some preprocessor magic, but it's a bit jarring and also forces the addition of either a custom header to include VIPS, or to disable keywords entirely for the Qt project.
With this patch, libvips detects Qt when the C++ header is used and temporarily disables the keyword, just to enable it again after inclusion. It should …
=> cpp: Fix build in Qt-using projects without changes

meson.build
Diff when building a full-fat version of libvips with modules enabled:
```diff
@@ -30,6 +30,12 @@ vips 8.16.0
libopenjp2                        : 2.5.2
libhwy                            : 1.1.0
niftiio                           : 3.0.1
+    MagickCore                        : 7.1.1
+    openslide                         : 4.0.0
+    libheif                           : 1.17.5
+    libjxl                            : 0.8.2
+    libjxl_threads                    : 0.8.2
+    poppler-glib                      : 24.02.0
Build options
enable debug                      : NO
@@ -67,7 +73,7 @@ vips 8.16.0
PDF load with poppler-glib        : YES (dynamic module: YES)
SVG load with librsvg-2.0         : YES
EXR load with OpenEXR             : YES
-    WSI load with openslide           : YES
+    WSI …
```
=> List module dependency versions in the build summary

ChangeLog, doc/function-list.xml, doc/gen-function-list.py, libvips/foreign/foreign.c, libvips/foreign/rawsave.c, libvips/include/vips/foreign.h
=> Rework rawsave and add rawsave_target

fuzz/oss_fuzz_build.sh
For the same reason as mentioned in PR #3929:
https://oss-fuzz-build-logs.storage.googleapis.com/log-ba5392d5-fe65-462a-b134-e6b38c228b08.txt
~~Uses a patch from: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/756.~~
=> OSS-Fuzz: disable build of cruft

libvips/foreign/pdfiumload.c
related to: https://github.com/libvips/libvips/pull/3790
Rendering all annotations is also required `FPDF_ANNOT` flags at FPDF_RenderPageBitmap.
Ref: https://pdfium.googlesource.com/pdfium/+/main/public/fpdfview.h#899
=> fix(pdfium): render annotations

ChangeLog, man/vipsheader.1, tools/vipsheader.c
With this PR you can use many "-f" arguments, for example:
$ vipsheader -f width -f height k2.jpg
1450
2048
See https://github.com/libvips/libvips/issues/467
=> support mutiple "-f" args to vipsheader

ChangeLog
The `don't build loaders as modules by default` change was reverted with commit 7ddce5a1c9fe3e648b86badef4592d0c3c9db1ee, update the ChangeLog to reflect this.
=> Revise ChangeLog

meson.build
Specifically for those created with `declare_dependency()`, which do not have a version number or name.
Diff when building with libnifti found without pkg-config (i.e. `-Dnifti-prefix-dir=/usr`).
```diff
@@ -29,7 +29,6 @@ vips 8.16.0
OpenEXR                           : 3.1.10
libopenjp2                        : 2.5.2
libhwy                            : 1.1.0
-    dep139870032254528                     : 8.16.0
MagickCore                        : 7.1.1
openslide                         : 4.0.0
libheif                           : 1.17.5
@@ -75,7 +74,7 @@ vips 8.16.0
EXR load with OpenEXR             : YES
WSI load with openslide           : YES (dynamic module: YES)
Matlab load with matio            : YES
-    NIfTI load/save with dep139870032254528: YES
+    NIfTI load/save with libnifti …
```
=> Improve build summary for internal dependencies

meson.build
```console
$ cat reduced.c
static int __attribute__((target_clones("default,avx")))
has_target_clones(void) {
return 0;
}
int main(void) {
int (*func)(void) = has_target_clones;
return func();
}
$ cc reduced.c -o repro -Wl,-z,now,-z,relro
$ ./repro
[1]   Segmentation fault (core dumped) ./repro
$ uname -mrs
NetBSD 10.0 amd64
```
Resolves: #3977
Upstream issue: https://gnats.netbsd.org/57792
=> Ensure `target_clones` support is checked at runtime

libvips/foreign/jxlload.c
Both `tps_denominator` and `tps_numerator` will be zero for non-animated images.
Found by UBSan:
https://github.com/kleisauke/libvips/actions/runs/9486292772/job/26140300986#step:14:327
Diff is best viewable with the `Hide whitespace changes` option.
=> jxlload: guard against NaN values

.github/workflows/ci.yml
This resolves the current CI failure caused by GitHub Actions installing a non-Homebrew Python into the Homebrew prefix. On `macos-14` runners, which use Apple Silicon/ARM, this issue does not occur because Homebrew uses `/opt/homebrew` as its install prefix on these systems.
=> CI: upgrade macOS runner to version 14 (Sonoma)

suppressions/lsan.supp
https://github.com/libvips/libvips/actions/runs/9530033062/job/26269434074#step:14:488
=> lsan: suppress leak warnings from libimagequant

ChangeLog, libvips/iofuncs/util.c, meson.build
- vsnprintf() detection with meson was not working on windows
- the vips_vsnprintf() fallback was not threadsafe
This PR changes the fallback to g_vsnprintf() and improves detection in meson.
See https://github.com/libvips/libvips/issues/4003 and https://github.com/libvips/libvips/issues/4001
Thanks Julianiolo
=> fix vips_vsnprintf()

.github/workflows/ci.yml
I'm not sure why this was needed, but I suspect it's no longer needed after commit fa6c034.
=> CI: remove `dlclose()` workaround

ChangeLog, libvips/deprecated/package.c, libvips/foreign/rawsave.c, libvips/include/vips/internal.h, libvips/include/vips/util.h, libvips/iofuncs/generate.c, libvips/iofuncs/image.c, libvips/iofuncs/target.c, libvips/iofuncs/util.c, libvips/iofuncs/vips.c, tools/vipsheader.c
write() on windows uses int for byte counts, leading to errors with very wide (more than 1.5m pixels wide) images.
libvips was assuming posix:
```C
ssize_t write(int fd, const void buf[.count], size_t count);
```
But windows has:
```C
int _write(int fd, const void *buffer, unsigned int count);
```
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/write?view=msvc-170
We probably have some other int32 limits still :( we should make some test cases and do more investigation, especially on windows.
Referring discussion:
https://github.com/libvips/libvips/discussions/3918#discussioncomment-9125646
=> fix some int32 limits on windows

.github/workflows/ci.yml
This should resolve the current CI failures.
It's unclear why this is now necessary, as `libheif-plugin-aomenc` is a "recommended dependency" of [`libheif1`](https://packages.ubuntu.com/noble/libheif1). Therefore, it should be installed automatically since we don't use the `--no-install-recommends` flag.
=> CI: install libheif-plugin-aomenc on the Ubuntu runner

cplusplus/include/vips/vips8, libvips/arithmetic/meson.build, libvips/create/meson.build, libvips/include/vips/basic.h, meson.build
Always define `VIPS_CPLUSPLUS_API` as `_VIPS_PUBLIC`, since this is usually built with Meson.
Resolves: #3975.
=> cplusplus: simplify symbol visibility

libvips/foreign/jxlload.c
- Commit fd18fd071a524edd7ab7531c904ba6a256035995 removes the deprecated `JXL_DEC_NEED_DC_OUT_BUFFER` and `JXL_DEC_DC_IMAGE` events to ensure compilation when building with `-DDEBUG`.
- Commit ac28876af1491073d097ab03fcff96f87a962f63 ensures animation frames are skipped more efficiently by using `JxlDecoderSkipFrames()`.
- Commit aac68afb92f0c1892c49aac4ef19e978e82a3282 always set the frame delays metadata, similar to the GIF and WebP loader.
```console
$ vipsheader -f delay x.gif
50 20 20 20 20 20 20 20 20 40 20 20 20 20 20 20 20 20 50 20 20 20 20 20 20 20 20 40 20 20 20 20 20 20 20 20 
$ vipsheader -f delay x.webp
50 20 20 20 20 20 20 20 20 40 20 20 20 20 20 20 20 20 50 20 20 20 20 20 20 20 20 40 20 20 20 20 20 20 20 20 
$ vipsheader -f delay …
```
=> jxlload: various improvements

libvips/foreign/radiance.c
The reason for this PR is that Radiance appears to be adopting a license similar to the more permissive BSD-3-Clause license, and has therefore removed these two paragraphs:
```markdown
3. The end-user documentation included with the redistribution,
if any, must include the following acknowledgment:
"This product includes Radiance software
(http://radsite.lbl.gov/)
developed by the Lawrence Berkeley National Laboratory
(http://www.lbl.gov/)."
Alternately, this acknowledgment may appear in the software itself,
if and wherever such third-party acknowledgments normally appear.
[...]
5. Products derived from this software may not be called "Radiance",
nor may "Radiance" appear in their name, without prior written
permission of Lawrence Berkeley National Laboratory.
```
=> radiance: sync with version 5.4

.gitattributes
Ensure we distribute only files that are relevant for a dist tarball, excluding any Git/IDE specific files.
Tested with:
```console
$ meson setup release_build -Ddoxygen=true -Dgtk_doc=true -Dvapi=true
$ meson compile -Crelease_build
$ meson dist -Crelease_build
$ ls release_build/meson-dist
vips-8.16.0.tar.xz  vips-8.16.0.tar.xz.sha256sum
$ tar -tf release_build/meson-dist/vips-8.16.0.tar.xz | grep -q ".git" || echo ".git not found in dist tarball"
.git not found in dist tarball
```
=> Clean up dist tarball

libvips/deprecated/vips7compat.c, libvips/foreign/exif.c, libvips/foreign/radiance.c, libvips/iofuncs/sbuf.c, libvips/iofuncs/util.c, tools/vipsedit.c, tools/vipsthumbnail.c
Should be a non-functional change, except that `g_ascii_isspace()` returns `FALSE` for vertical tab (`\v`), see:
https://bugzilla.gnome.org/show_bug.cgi?id=59388#c5
Resolves: #4015.
=> Migrate to GLib-provided `g_ascii_is*` functions

libvips/foreign/heifsave.c, meson.build, test/test-suite/test_foreign.py
Resolves: #4051.
Context: https://github.com/strukturag/libheif/pull/1039#issuecomment-1866023028.
=> heifsave: set `matrix_coefficients=0` by default in lossless mode

ChangeLog, libvips/foreign/heifsave.c, libvips/iofuncs/header.c, meson.build, test/test-suite/test_foreign.py
Trivial backport of 117c554, #3760 and #4052 to [`8.15`](https://github.com/libvips/libvips/tree/8.15).
=> Backport 117c554, #3760 and #4052 to 8.15

libvips/foreign/heifsave.c, test/test-suite/test_foreign.py
In accordance with commit https://github.com/strukturag/libheif/commit/136cf0173ffb52a92842736fec47c83e69475327.
However, it still requires libheif >= 1.13.0 for true lossless, so update `test_avifsave_lossless` accordingly to fix CI on the 8.15 branch (which still uses Ubuntu 22.04 as the runner image).
=> heifsave: ensure true lossless with libheif < v1.17.2

ChangeLog, libvips/conversion/composite.cpp
The dest-atop blend mode should function like atop, but with the drawing operations reversed. Therefore, t1 must be `1 - aB`.
Found using this test script:
```python
import pyvips
base = (pyvips.Image.black(120, 90)
.copy(interpretation='srgb')
.new_from_image([179, 0, 0, 204])
.embed(0, 0, 160, 120))
overlay = (pyvips.Image.black(120, 190)
.copy(interpretation='srgb')
.new_from_image([0, 0, 230, 204])
.embed(40, 30, 160, 120))
im = base.composite2(overlay, 'dest-atop')
im.write_to_file('vips.png')
```
| Expected image | Actual image |
| :--: | :--: |
| ![vips](https://github.com/user-attachments/assets/ea7c788d-c743-4b12-87ef-fb7d77d0015d) |![vips-before](https://github.com/user-attachments/assets/cfbad025-f215-450a-9575-c84be5a370e9) |
=> composite: fix dest-atop blend mode

fuzz/oss_fuzz_build.sh
This matches the default behavior of libFuzzer, which adjusts the input size based on the largest file in the corpus. If no seed corpus is provided or if all files are smaller than 4096 bytes, it uses a minimum limit of 4096 bytes.
```
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
```
Found this while working on PR https://github.com/google/oss-fuzz/pull/12256.
=> OSS-Fuzz: increase max file size limit of seed corpus

ChangeLog, libvips/iofuncs/source.c
Use `vips_source_pipe_read_to_position()` only for pipes; otherwise, a zero-length memory or file source may cause an assertion failure.
Test program:
```c
#include <vips/vips.h>
int
main(int argc, char *argv[])
{
VipsSource *source;
const void *buf;
size_t len;
if (VIPS_INIT(argv[0]))
return -1;
if (argc != 2)
vips_error_exit("usage: %s in-file", argv[0]);
if (!(source = vips_source_new_from_file(argv[1])))
vips_error_exit("unable to load from %s", argv[1]);
/* Map the whole source into memory.
*/
if (!(buf = vips_source_map(source, &len))) {
g_object_unref(source);
vips_error_exit("unable to map %s", argv[1]);
}
g_object_unref(source);
return 0;
}
```
Before:
```console
$ gcc -g -Wall test-source.c `pkg-config vips --cflags --libs` -o test-source
$ touch empty.jpg
$ ./test-source …
```
=> Fix vips_source_map for zero-length sources

test/test-suite/test_iofuncs.py
```
==================================== ERRORS ====================================
________________ ERROR at setup of TestIofuncs.test_revalidate _________________
Error evaluating 'skipif': you need to specify reason=STRING when using booleans as conditions.
```
https://github.com/libvips/libvips/actions/runs/10123138814/job/27996075308#step:14:671
=> Fix CI failures

libvips/foreign/matrixsave.c
The integer file descriptors associated with the streams stdin, stdout, and stderr are 0, 1, and 2, respectively.
=> matrixsave: ensure `matrixprint` will write to stdout

libvips/conversion/tilecache.c
Avoids an unnecessary call to `g_hash_table_{steal,insert}()` when creating a new tile.
=> tilecache: only call `vips_tile_move()` when reusing a tile

fuzz/oss_fuzz_build.sh
After PR #4092, the buffer save fuzzers source file was generalized, so we need to ensure that the seed corpus remains correctly linked to each individual fuzz target.
=> OSS-Fuzz: fix seed corpus link

fuzz/oss_fuzz_build.sh
For introspector builds using LTO, memory usage can become quite heavy. To prevent potential OOM errors, limit Ninja to use no more than 4 processes for linking.
Might fix the introspector build after PR #4092.
Context: https://github.com/google/oss-fuzz/issues/12213#issuecomment-2306951820.
=> OSS-Fuzz: limit link jobs to 4

ChangeLog, libvips/foreign/heifsave.c
Reproducer:
```console
$ vips copy test/test-suite/images/favicon.ico x.avif[bitdepth=1]
Segmentation fault (core dumped)
```
=> heifsave: fix crash when passing an invalid bitdepth

fuzz/generic_buffer_fuzzer.cc, fuzz/jpegsave_file_fuzzer.cc, fuzz/mosaic_fuzzer.cc, fuzz/sharpen_fuzzer.cc, fuzz/smartcrop_fuzzer.cc, fuzz/thumbnail_fuzzer.cc
Non-functional change, previously the initialization occurred in `LLVMFuzzerTestOneInput()` automatically via `vips_check_init()`.
=> fuzz: add missing `vips_init()` call

fuzz/oss_fuzz_build.sh
See: https://github.com/google/oss-fuzz/issues/12167.
<details>
```diff
@@ -11,16 +11,15 @@ C compiler for the host machine: clang (clang 18.0.0 "clang version 18.0.0 (http
C linker for the host machine: clang ld.gold 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
-Compiler for C supports function attribute visibility:hidden: NO 
-Header "time.h" has symbol "gmtime_r" : NO 
-Header "time.h" has symbol "gmtime_s" : NO 
+Compiler for C supports function attribute visibility:hidden: YES 
+Header "time.h" has symbol "gmtime_r" : YES 
Dependency libjpeg skipped: feature jpeg disabled
Dependency libtiff-4 skipped: feature tiff disabled
-Checking if "supports SSE2 intrinsics" compiles: NO 
+Checking if "supports SSE2 intrinsics" compiles: YES 
Library m …
```
=> OSS-Fuzz: fix Meson compile tests in introspector builds

ChangeLog, libvips/foreign/heifsave.c
```
Done 6822012 runs in 7201 second(s)
=================================================================
==8==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 6812 byte(s) in 131 object(s) allocated from:
#0 0x560f6e1998ee in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
#1 0x560f6f16b7c4 in color_profile_nclx::alloc_nclx_color_profile() /src/libheif/libheif/nclx.cc:294:45
#2 0x560f6e316319 in vips_foreign_save_heif_write_page /src/libvips/build/../libvips/foreign/heifsave.c:299:16
#3 0x560f6e316319 in vips_foreign_save_heif_write_block /src/libvips/build/../libvips/foreign/heifsave.c:470:8
#4 0x560f6e1f3999 in wbuffer_write /src/libvips/build/../libvips/iofuncs/sinkdisc.c:174:25
#5 0x560f6e1f3999 in wbuffer_write_thread …
```
=> heifsave: ensure NCLX profile is freed in lossless mode

suppressions/lsan.supp
This reverts commit 62f68fc136e9bc65ef005c9395c165e049ce4a41, as it became redundant after strukturag/libheif#891 (libheif v1.17.0).
=> Revert "lsan: suppress leak warnings from libheif (#3481)"

libvips/foreign/heifsave.c
Context: https://github.com/libvips/libvips/pull/4110#issuecomment-2308786358, hence let's reuse this existing changelog entry:
https://github.com/libvips/libvips/blob/4f26536730f9d6cfb7b9a4a30fe4844f00264a94/ChangeLog#L4
=> heifsave: limit bitdepth to supported values

suppressions/lsan.supp, suppressions/ubsan.supp
Avoid suppressing shared libraries, as this could mask actual leaks.
=> lsan: revise suppressions

tools/vipsheader.c
<details>
```console
[371/416] Compiling C object tools/vipsheader.p/vipsheader.c.o
../tools/vipsheader.c:229:8: warning: variable 'image' is used uninitialized whenever '||' condition is true [-Wsometimes-uninitialized]
229 |                         if (!(source = vips_source_new_from_descriptor(0)) ||
|                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../tools/vipsheader.c:241:7: note: uninitialized use occurs here
241 |                 if (image &&
|                     ^~~~~
../tools/vipsheader.c:229:8: note: remove the '||' if its condition is always false
229 |                         if (!(source = vips_source_new_from_descriptor(0)) ||
|                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> Silence a clang warning

libvips/iofuncs/buffer.c, libvips/iofuncs/gate.c, libvips/iofuncs/thread.c, libvips/iofuncs/threadpool.c
Revise the code to move the initialisation to the global file scope, aligning with the example outlined in the GLib documentation: https://docs.gtk.org/glib/func.PRIVATE_INIT.html
This should be considered a non-functional change, at least on Linux, on Windows I'm not sure how thread-local storage should be initialised, so it targets the 8.15 branch just to be sure.
=> Simplify `GPrivate` initialisation

.github/workflows/ci.yml
In line with commit 23998b42ce25987714e117d480bb30d718767529. This is pre-installed only on `macos-12` and `ubuntu-22.04`. Newer images no longer include it due to maintenance concerns, see:
https://github.com/actions/runner-images/issues/7899#issuecomment-1632115075
Context: https://github.com/libvips/libvips/pull/4128#issuecomment-2317374277.
=> CI: build without *magick

README.md
Noticed this while working on https://src.fedoraproject.org/rpms/vips/pull-request/9.
=> Migrate to SPDX license in README

ChangeLog, meson.build
Plain builds are typically used by distro builds; make sure to disable GLib cast checks and assertions there as well, see: https://gitlab.gnome.org/GNOME/glib/-/commit/61a843564de7a4727b9707f205649f848125ba91
=> Disable GLib cast checks and asserts for plain builds

libvips/iofuncs/init.c
Non-functional change to appease static analysis tools: in musl, `pthread_attr_destroy()` is a no-op, while in glibc, it only frees the thread's CPU affinity mask if it was previously allocated via `pthread_attr_setaffinity_np()` or `pthread_getattr_np()`.
=> init: explicitly call `pthread_attr_destroy()`

libvips/iofuncs/reorder.c
glib 2.82 renamed g_qsort_with_data() as g_sort_array()
=> fix a warning with latest glib

.github/workflows/ci.yml, .github/workflows/cifuzz.yml, .github/workflows/codespell.yml, .github/workflows/lint.yml
Trivial backport of #3825 to [`8.15`](https://github.com/libvips/libvips/tree/8.15) to fix CIFuzz, see:
https://github.com/libvips/libvips/actions/runs/10833100876/job/30059048453
=> Backport #3825 to 8.15

libvips/iofuncs/generate.c, libvips/iofuncs/util.c
This fixes #4088.
Replacing `ssize_t` with `gint64` should be a straigtforward solution and avoid problems with msvc.
=> replace ssize_t with gint64 to fix msvc build #4088

ChangeLog, libvips/foreign/vips2tiff.c
JPEG in TIFF compression needs the jpeg encoding colourspace set to match the enclosing tiff file.
fixes regression in 8.15.3 from https://github.com/libvips/libvips/pull/3924
see https://github.com/libvips/pyvips/issues/490
reproduce error with
```
vips copy x.jpg x.tif[compression=jpeg,Q=90,pyramid]
```
thanks nahilsobh
=> call jpeg_set_colorspace for jpeg in tiff

README.md
The OSS-Fuzz issue tracker has moved to a new location, see: https://github.com/google/oss-fuzz/issues/12508.
=> Update link to OSS-Fuzz issue tracker in README

.github/workflows/ci.yml
This step was consolidated with the next one in commit 52698b8, but re-introduced due to the merge in commit 12dc3b4.
=> CI: remove redundant step

libvips/foreign/vips2jpeg.c, libvips/foreign/vips2tiff.c
Non-functional change.
Context: https://github.com/libvips/libvips/pull/4164#issuecomment-2365133761.
=> Polish JPEG chroma subsampling handling

libvips/foreign/tiffsave.c, libvips/foreign/vips2tiff.c
There is currently no way to set the deflate compression level (through the TIFFTAG_ZIPQUALITY tag) when saving to TIFF. All deflate-encoded TIFFs, therefore, are compressed using the default level of 6.
This pull requests allows the existing `level` parameter, which is currently only used for zstd to also be usable for deflate.
If this parameter is not set, the compression level defaults to the libtiff default of 6 for Deflate and 9 for Zstd.
=> Added ability to specify Deflate (zlib) compression level through 'level' parameter

ChangeLog, libvips/include/vips/internal.h, libvips/iofuncs/threadset.c
The previous implementation was prone to race conditions under rare circumstances.
Context: #4069.
=> threadset: revise/simplify on top of `GAsyncQueue`

ChangeLog, libvips/iofuncs/generate.c, libvips/iofuncs/util.c
Trivial backport of #4153 to [`8.15`](https://github.com/libvips/libvips/tree/8.15).
=> Backport #4153 to 8.15

cplusplus/gen-operators.py, cplusplus/include/vips/VImage8.h
The now deprecated `VImage::cache()` function is still preserved to ensure ABI compat.
=> Update C++ binding

cplusplus/VImage.cpp, cplusplus/include/vips/VImage8.h
Add a C++ compat function for `vips_rawsave_fd()` after the GObject class removal in commit 067b9f5.
The `abi-compliance-checker` results are available at:
https://kleisauke.nl/compat_reports/vips-cpp/8.15.5-rc1_to_rawsave_fd-compat/compat_report.html
https://kleisauke.nl/compat_reports/vips-cpp/8.15.5-rc1_to_master/compat_report.html
FWIW, I'm not sure if we could do anything about `VImage::new_from_memory_steal`, according to https://stackoverflow.com/a/5083976 changing to a const-qualified version would _not_ break ABI/API, at least in C99.
=> cplusplus: add `VImage::rawsave_fd` compat function

cplusplus/VImage.cpp, cplusplus/include/vips/VImage8.h
See: #4193.
The `abi-compliance-checker` results are available at:
https://kleisauke.nl/compat_reports/vips-cpp/8.15.5-rc1_to_issue-4193/compat_report.html
https://kleisauke.nl/compat_reports/vips-cpp/8.15.5-rc1_to_master/compat_report.html
=> cplusplus: add `VImage::new_from_memory_steal` compat function

libvips/foreign/heifsave.c, meson.build
Should fix https://github.com/libvips/libvips/issues/4192
=> heifsave: check availability of heif_encoder_parameter_get_valid_integer_values

cplusplus/include/vips/VImage8.h, libvips/foreign/foreign.c, libvips/foreign/heifsave.c
I realise we don't want to expose every single possible underlying encoder feature, however given the relatively poor encoding times of AVIF images this one feels like the most useful addition to libaom I've seen in a while.
The `auto_tiles` property allows the aom encoder to determine the optimum tile count based on the output dimensions and available threads, which in my testing seriously improves multi-core utilisation. Elapsed time is almost halved in some cases. There are claims it reduces memory usage but I've not found much evidence of this yet. The cost of all this is very slightly increased file sizes, mostly from the additional metadata.
The upstream PR for this was https://github.com/strukturag/libheif/pull/1330 (requires libaom v3.10.0+ and the forthcoming libheif v1.18.3+).
=> heifsave: expose libheif/aom auto_tiles feature

libvips/include/vips/almostdeprecated.h
In https://github.com/libvips/libvips/issues/4193#issuecomment-2407195135
> almostdeprecated.h cannot be included directly
=> avoid direct include of almostdeprecated.h

libvips/include/vips/vips7compat.h
Regressed since 71d356b.
See: https://github.com/libvips/libvips/actions/runs/11304572685/job/31443113383
<details>
```
In file included from /usr/include/orc-0.4/orc/orcprogram.h:7,
from /usr/include/orc-0.4/orc/orc.h:6,
from ../libvips/resample/reducev.cpp:80:
/usr/include/orc-0.4/orc/orcexecutor.h:42:8: error: redefinition of ‘struct _OrcExecutor’
42 | struct _OrcExecutor {
|        ^~~~~~~~~~~~
In file included from ../libvips/include/vips/vips.h:139,
from ../libvips/resample/reducev.cpp:71:
../libvips/include/vips/vips7compat.h:1665:16: note: previous definition of ‘struct _OrcExecutor’
1665 | typedef struct _OrcExecutor {
|                ^~~~~~~~~~~~
In file included from /usr/include/orc-0.4/orc/orc.h:6,
from ../libvips/resample/reducev.cpp:80: …
```
=> Fix build with orc

libvips/foreign/jpeg.h, libvips/foreign/jpeg2vips.c, libvips/foreign/tiff2vips.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vips2tiff.c
Use the "add-on" message table to ensure compatibility with jpegli, which lacks its own message codes and table.
https://github.com/google/jpegli/blob/13dfbac5dc10b86b75a22a2bba293d8f974f43b9/lib/jpegli/error.cc#L93-L98
Resolves: #4206.
<details>
<summary>Test case</summary>
```console
$ vips copy ~/Downloads/2d3c8299-5a81-4e01-abe1-f2879d76bef2.JPG x.jpg
(vips:12329): VIPS-WARNING **: 12:06:37.041: read gave 1 warnings
(vips:12329): VIPS-WARNING **: 12:06:37.041: VipsJpeg: premature end of JPEG image
$ LD_PRELOAD=/opt/jpegli/lib64/libjpeg.so.62.4.0 vips copy ~/Downloads/2d3c8299-5a81-4e01-abe1-f2879d76bef2.JPG x.jpg
(vips:12349): VIPS-WARNING **: 12:06:38.874: read gave 1 warnings
(vips:12349): VIPS-WARNING **: 12:06:38.874: VipsJpeg: premature end of JPEG image
```
</details>
=> jpeg: implement custom message codes and table

libvips/include/vips/vips7compat.h
Remove the confusing `OrcProgram` and `OrcExecutor` stubs to avoid conflicts with `orc.h`. Should be safe, the deprecated `VipsVector` and `VipsExecutor` APIs was tightly coupled to liborc and became no-op after the adoption of Highway.
While this is a potential ABI break, this API was likely not used outside libvips. The same ABI break could also occur in versions prior to 8.15 when a binary was built with `-Dorc=disabled` instead of `-Dorc=enabled`.
<details>
```c
#include <orc/orc.h>
#include <vips/vips.h>
int main(void)
{
return 0;
}
```
```console
$ gcc test-orc-vips.c `pkg-config vips orc-0.4 --cflags --libs` -o test-orc-vips
In file included from /usr/include/vips/vips.h:139,
from test-orc-vips.c:5:
/usr/include/vips/vips7compat.h:45:16: error: …
```
=> vips7compat.h: remove `OrcProgram` and `OrcExecutor` stubs

libvips/include/vips/vips.h
Via the `VIPS_DISABLE_COMPAT` definition. 
See: https://github.com/libvips/libvips/issues/4190#issuecomment-2422526756.
<details>
<summary>Test case</summary>
`test-deprecated.c`:
```c
#include <vips/vips.h>
int
main(void)
{
char version[256];
vips_snprintf(version, 256, "%d.%d.%d",
VIPS_MAJOR_VERSION, VIPS_MINOR_VERSION, VIPS_MICRO_VERSION);
printf("%s\n", version);
return 0;
}
```
```console
$ gcc test-deprecated.c `pkg-config vips --cflags --libs` -o test-deprecated
test-deprecated.c: In function ‘main’:
test-deprecated.c:8:9: warning: ‘vips_snprintf’ is deprecated: Use 'g_snprintf' instead [-Wdeprecated-declarations]
8 |         vips_snprintf(version, 256, "%d.%d.%d",
|         ^~~~~~~~~~~~~
In file included from /usr/include/vips/vips7compat.h:1771,
from /usr/include/vips/vips.h:139, …
```
=> Add option to opt-out of `vips7compat.h` inclusion

libvips/foreign/foreign.c
The arguments were reversed, likely due to confusion with `g_str_has_prefix()`. Ensures all metadata is removed when saving with `keep=none`.
See: #4224.
=> Fix `vips_isprefix()` argument order

ChangeLog, libvips/foreign/jxlload.c, libvips/foreign/jxlsave.c, meson.build
Multipage JXL images are just animations with the duration field set to 0xffffffff. This PR detects animations with this magic value for all frames and represents them as libvips multipage images (no duration metadata).
A matching change in jxlsave sets duration to 0xffffffff for multipage images.
There's no API change, and this looks pretty safe, so I think it'd be OK for 8.16.
=> add support for multipage jxl

index.md
Adds the vips-ffm Java bindings to the website, to help folks discover them. I stuck the link at the end of the list, but do let me know if you'd like a different ordering.
=> Add Java bindings to the website

libvips/include/vips/meson.build
Dependencies created using `declare_dependency()` does not have a version number or name.
Mirrors commit ec432a5.
Diff when building with libnifti found without pkg-config (i.e. `-Dnifti-prefix-dir=/usr`).
```diff
@@ -27,7 +27,7 @@ SVG load with librsvg-2.0: true
EXR load with OpenEXR: true
WSI load with openslide: true (dynamic module: true)
Matlab load with matio: true
-NIfTI load/save with dep140163777216928: true
+NIfTI load/save with libnifti: true
FITS load/save with cfitsio: true
GIF save with cgif: true
Magick load/save with MagickCore: true (dynamic module: true)
```
=> Improve `--vips-config` for internal dependencies

libvips/arithmetic/maxpair.c, libvips/arithmetic/minpair.c
These macros are faster and more accurate than VIPS_MAX() and VIPS_MIN for float values, since they will call `builtin_fmax()` if possible.
See https://github.com/libvips/libvips/pull/4243
=> use VIPS_FMAX()/FMIN() in maxpair/minpair

ChangeLog, libvips/morphology/morph.c, libvips/morphology/morph_hwy.cpp
Context: https://github.com/lovell/sharp/pull/4243.
<details>
<summary>Test case</summary>
```console
$ cat <<EOT > 3x3.mat
3 3 1 0
0 0 0
0 0 0
0 0 0
EOT
$ curl -LO https://github.com/qpincon/sharp/raw/main/test/fixtures/dot-and-lines.png
$ vips morph dot-and-lines.png erode.png 3x3.mat erode --vips-novector
$ vips morph dot-and-lines.png dilate.png 3x3.mat dilate --vips-novector
```
</details>
=> morph: fix regressions after Highway implementation

libvips/resample/templates.h
Trivial backport of #4243 to [`8.16`](https://github.com/libvips/libvips/tree/8.16).
=> Backport #4243 to 8.16

ChangeLog, libvips/iofuncs/init.c
Use `g_log_writer_default_set_debug_domains()` since resetting `G_MESSAGES_DEBUG` at runtime has no effect for GLib >= 2.80.
Also, remove any checks for the old `G_MESSAGES_DEBUG` env variable and overwrite it directly instead. This means the `--vips-info` CLI flag and the `VIPS_INFO=1` env variable now take precedence over `G_MESSAGES_DEBUG`.
See: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3710.
=> Fix `--vips-info` CLI flag with GLib >= 2.80

ChangeLog, libvips/foreign/heifsave.c, libvips/foreign/jp2ksave.c
i.e. always disable chroma subsampling when saving lossless.
See: #4232.
=> Make `subsample-mode=on` and `lossless=true` mutually exclusive

libvips/iofuncs/init.c
```
../libvips/iofuncs/init.c:367: Error: Vips: identifier not found on the first line:
* Equivalent to setting the `G_MESSAGES_DEBUG=VIPS` environment variable.
^
```
=> Fix GIR error after #4251

libvips/foreign/dzsave.c, libvips/foreign/ppmsave.c
For example, this ensures that `[no_strip=false]` or `[squash=false]` is properly handled.
Targets the 8.16 branch without a changelog entry, as these arguments are already deprecated.
=> Avoid using `vips_object_argument_isset()` to check for flags

libvips/foreign/heifload.c, libvips/foreign/jpegload.c, libvips/foreign/pngload.c, libvips/foreign/spngload.c, libvips/foreign/svgload.c, test/test-suite/test_foreign.py
The load-specific `unlimited` flag is known to be fuzzing-unfriendly.
Targets the 8.16 branch to prevent CIFuzz from fuzzing this flag as well.
=> Disable `unlimited` flag in fuzzing builds

.github/workflows/ci.yml
The macOS CI jobs are failing due to the current GitHub Action runner images containing `pkg-config`, which conflicts with https://github.com/Homebrew/homebrew-core/pull/194885
```
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
```
This PR allows CI to install dependencies, compile and run most of the tests, however one of the tests will still fail on macOS due to https://github.com/strukturag/libheif/issues/1389
=> CI: Homebrew has switched from pkg-config to pkgconf

ChangeLog, libvips/foreign/heifsave.c
Helps ensure AVIF encoding time is more predictable and consistent, fixes https://github.com/libvips/libvips/issues/2983
Remains backwards/forwards compatible with or without the upstream change at https://github.com/strukturag/libheif/pull/1408 as it will fail gracefully when the parameter is unavailable.
We might want consider exposing this as an option, either now or later.
=> heifsave: prevent use of AV1 intra block copy feature

.github/workflows/ci.yml
See https://github.com/actions/runner-images/pull/11015
Relates to https://github.com/libvips/libvips/pull/4285
=> CI: macOS runners no longer include deprecated pkg-config

libvips/foreign/heifsave.c
The previous name was not part of any published release so this isn't a breaking change.
Relates to https://github.com/libvips/libvips/pull/4284#issuecomment-2502346704
Upstream libheif commit https://github.com/strukturag/libheif/commit/8c82e2eb8b0bfa8dd0306289c2632ad31815965e
=> heifsave: rename intrabc parameter to match upstream

ChangeLog, libvips/iofuncs/threadpool.c
Turn the exit flag back into a proper count.
Fixes a regression introduced in commit 27229aa.
Context: #4276.
=> threadpool: improve cooperative downsizing

libvips/resample/shrinkh.c, libvips/resample/shrinkv.c
- Commit 4395dd0a098ac626bef5b8f1673272e18fa3010c is a revert of commit 9b968491d366a68ea1008ed29a74f7293501e4c4. See https://gist.github.com/kleisauke/dcf24beb95cdf2b3037ff63f71b7f9bd for the rationale behind this.
- Commit e1698911402a2f3caac7131e37a8e438e1ab0827 takes a similiar approach as PR #3052 in `shrinkh`.
- Commit 77e8451f13c0aeb949648b299a4148eaec2584a9 removes the `shrinkv` sum buffer in favor of a local, ~7% faster. In line with commit 2e5880b69cf79715ac84abb28b8482aefe7df532.
- Commit 3d28a9222fcf8cd4b49f5b20e716096e60c22b38 uses `gint64` as accumulator type for the uint/int paths. In line with PR #3514.
- Commit 2d8f1c6a1b31e3cb6aef2282f83ce0f66d66778a adds a fixed-point arithmetic path for uchar images, ~9% faster.
<details>
<summary>Test script</summary>
Test image: …
=> shrink{h,v}: improve performance

ChangeLog, libvips/colour/colour.c
The colour functions were not shifting alpha channels, just casting them, so
operations which changed depth, like `icc_transform --depth 8` on a
16-bit image, could have an incorrectly scaled alpha.
See https://github.com/libvips/libvips/issues/4301
Thanks frederikrosenberg
=> fix alpha shift during colourspace conversion

ChangeLog, libvips/foreign/tiff.c, libvips/foreign/tiff.h, libvips/foreign/tiff2vips.c, libvips/foreign/tiffload.c, libvips/foreign/vips2tiff.c, meson.build, test/test-suite/test_foreign.py
Adds a compile-time test for libtiff `OpenOptions` feature, when present sets the use of new, re-entrant error and warning handlers.
Defining these (and having them `return 1`) prevents the default behaviour of libtiff to call global, not thread-safe handlers shared between all users.
The handlers also support user data, so `tiffload` can now start to respect the `fail_on` option. Homebrew currently provides libtiff 4.7.0 so we can test for this on macOS.
I also investigated the various new memory limit safety features of `OpenOptions` discussed in https://github.com/libvips/libvips/discussions/3892 but these only cover libtiff allocations e.g. parsing headers, and exclude allocations in its dependencies. Newer versions of libtiff already introduce more sanity checks around these anyway …
=> tiff: add thread-safe warning/error handlers, requires libtiff 4.5.0+

ChangeLog, libvips/foreign/heifsave.c, meson.build
There's previously been some confusion around HEIF and orientation so https://github.com/libvips/libvips/pull/1681 made the sensible decision to let libheif deal with this on the input side.
More recently, commit https://github.com/strukturag/libheif/commit/4d9f13b8e00220193dc3e0b2bcd655ca0e9fa02d has added support for a similar feature to the output side, which this PR takes advantage of.
Originally reported at https://github.com/lovell/sharp/issues/4289, which includes a sample image.
```
$ vipsheader --field=orientation in.jpg 
8
$ vips copy in.jpg out.avif
```
Before:
```
$ heif-info out.avif 
MIME type: image/avif
main brand: avif
compatible brands: avif, mif1, miaf
image: 810x1080 (id=1), primary
colorspace: YCbCr, 4:2:0
bit depth: 8
color profile: rICC
alpha channel: no 
depth …
```
=> heifsave: set image orientation using irot and imir transformations

libvips/resample/shrinkv.c
Always use `VIPS_REGION_LSKIP()` to move down one line, as regions may have non-contiguous scanlines.
Test case:
```python
#!/usr/bin/env python3
import pyvips
im = pyvips.Image.new_from_file("alpha-layer-2-ink.jpg")
im = im.crop(873, 554, 727, 727)
im = im.shrink(2, 2)
im.write_to_file("x.jpg")
```
Regressed since commit 77fdf1b0f84022463dbcf4c2fa3b9f8a5f802ab5. This bug did not affect any released versions.
=> shrinkv: fix region stride handling

ChangeLog, libvips/deprecated/im_tiff2vips.c, libvips/foreign/pforeign.h, libvips/foreign/tiff.c, libvips/foreign/tiff.h, libvips/foreign/tiff2vips.c, libvips/foreign/tiffload.c, libvips/foreign/vips2tiff.c, meson.build
Adds a default limit of 20MB for total maximum ("cumulated") memory allocation during tag processing, which should be enough for hundreds if not thousands of tags. I could easily be persuaded to reduce this default limit.
Given libtiff is rather over-zealous in the number of times it reallocates memory, an image containing many thousands of tags can quickly lead to fragmentation. Attempting to process the <1MB sample image at https://issues.oss-fuzz.com/issues/42531230 *with* this memory limitation in place still results in an RSS of ~1GB (the OSS Fuzz issue should auto-close after this PR is merged).
Builds on https://github.com/libvips/libvips/pull/4313 and implements https://github.com/libvips/libvips/discussions/3892 for inclusion in 8.17.
=> tiffload: add support for unlimited flag, requires libtiff 4.7.0+

README.md
`carrierwave-vips` has not been updated in over 5 years, so its usage is not recommended.
However, [`CarrierWave` now supports a method to directly integrate with `libvips`](https://github.com/carrierwaveuploader/carrierwave#using-vips).
Therefore, I replaced `carrierwave-vips` with `CarrierWave` in README.md.
=> Replace carrierwave-vips with CarrierWave in README.md

ChangeLog, libvips/colour/XYZ2Yxy.c
Before this PR, converting to Yxy could leave -nan in pixels, eg.:
$ vips colourspace k2.jpg x.v yxy
$ vips avg x.v
(vips:231364): GLib-GObject-CRITICAL **: 16:02:54.674: value "-nan" of type 'gdouble' is invalid or out of range for property 'out' of type 'gdouble'
avg: parameter out not set
This PR adds a check for 0 before divide.
=> Fix divide by zero in xyz2yxy

libvips/arithmetic/complex.c
fix #4330.
* Fix cross-phase operation when Y1 == 0 and Y2 == 0.
* Workaround to stop MSVC raising C2124 error. By putting Y1 and Y2 values into variable first, MSVC compiler somehow no longer finds division by zero.
=> workaround C2124 error on MSVC

ChangeLog, libvips/foreign/tiff2vips.c
As discussed in https://github.com/libvips/libvips/issues/4324
I also added a changelog note about the previously-added `fail_on` flag.
Tested with the sample image in https://github.com/libvips/libvips/issues/4317
Before:
```
$ vips avg error_tiff.tif 
...
(vips:183630): tiff2vips-WARNING **: 10:18:21.846: Premature EOL at line 7212 of strip 0 (got 0, expected 9600)
vips:183630): VIPS-WARNING **: 10:18:21.846: error in tile 0 x 7200
tiff2vips: read error
```
After:
```
$ vips avg error_tiff.tif 
...
(vips:185249): tiff2vips-WARNING **: 10:22:38.083: Premature EOF at line 7212 of strip 0 (x 0)
(vips:185249): tiff2vips-WARNING **: 10:22:38.083: Premature EOL at line 7212 of strip 0 (got 0, expected 9600)
233.888096
```
```
$ vips avg error_tiff.tif[fail_on=warning] 
...
(vips:187702): …
```
=> tiffload: use fail_on to determine outcome of scanline read fail

ChangeLog, libvips/foreign/exif.c
Enumerated EXIF entries are often 1 byte in length but when represented as a string are up to around 30 chars in length.
This PR ensures support for this fairly common case by, when calculating the maximum length of the string, reducing the multiplier and adding a constant.
Fixes https://github.com/libvips/libvips/issues/4336 and also tested with the original image from https://github.com/libvips/libvips/issues/3857
Before:
```
exif-ifd2-SceneType: Dire (Dire, Undefined, 1 components, 1 bytes)
exif-ifd3-GPSAltitudeRef: Sea  (Sea , Byte, 1 components, 1 bytes)
```
After:
```
exif-ifd2-SceneType: Directly photographed (Directly photographed, Undefined, 1 components, 1 bytes)
exif-ifd3-GPSAltitudeRef: Sea level (Sea level, Byte, 1 components, 1 bytes)
```
=> exif: ensure enum entries can be converted to string

libvips/foreign/foreign.c
The pointer ```class->suffs``` is dereferenced later in the function.
```
for (p = class->suffs; *p; p++)
if (vips_iscasepostfix(filename, *p))
return save_class;
```
I added ```return NULL``` to prevent NULL dereference.
=> Fix null pointer dereference

libvips/foreign/tiff2vips.c
It's too dangerous to ignore a `-1` return code from `TIFFReadRawTile` as we're responsible for decoding the data.
Partially reverts commit 7b47b07
Found by https://issues.oss-fuzz.com/issues/387317434
=> tiffload: respect TIFFReadRawTile return code

ChangeLog, libvips/foreign/cgifsave.c, libvips/iofuncs/sinkdisc.c, test/meson.build, test/test_timeout_gifsave.c
Whilst investigating https://github.com/lovell/sharp/issues/4257 I discovered that `vips_sink_disc` appears to always return zero during `vips_foreign_save_cgif_build` even when `vips_foreign_save_cgif_sink_disc` returns a non-zero return code. It feels like a bit of a race condition, and I think this is because we need to have the entire input in memory before the CPU-intensive quantisation takes place.
This PR adds a new `aborted` property to track any non-zero return code, which then allows for things like an `eval` callback. The call to `vips_image_eval` occurs for each frame just after the image is remapped to the new palette as this is the most CPU-intensive section. I'd be happy to move the `vips_image_eval` call to a different location if required, or perhaps it might be better to …
=> gifsave: ensure return code is propagated

ChangeLog, libvips/foreign/vips2tiff.c, libvips/iofuncs/target.c
See: https://github.com/kleisauke/net-vips/issues/245.
Test case:
```console
$ curl -LO https://github.com/weserv/images/raw/5.x/test/api/fixtures/PalaisDuLouvre.tif
$ TMPDIR=/doesnotexist vips copy PalaisDuLouvre.tif x.tif[pyramid]
```
=> tiffsave: honor disc threshold during pyramid save

ChangeLog, libvips/colour/icc_transform.c, libvips/include/vips/colour.h, test/test-suite/test_resample.py
When the requested rendering intent is not supported by the profile, fallback to the profile's suggested intent. An error will only be raised if the suggested intent is also unsupported.
Resolves: #3475.
=> colour: use suggested rendering intent as fallback

libvips/iofuncs/cache.c
On a operation cache hit, we were only touching the hit itself.
As a result, after some operations on a loaded image, the image itself could be forced out by the operations that had been performed on it, even though the underlying image was still being used.
This PR makes cache touches also update the timestamps on all upstream operations, since the upstream operations are also being used (indirectly).
=> improve operation cache touch

libvips/arithmetic/find_trim.c, libvips/colour/icc_transform.c, libvips/foreign/magick7load.c, libvips/foreign/webpload.c, libvips/resample/thumbnail.c
Found in the https://github.com/libvips/libvips/compare/HEAD...kleisauke:parameters-constify changeset.
<details>
```
../libvips/arithmetic/find_trim.c: In function ‘vips_find_trim_build’:
../libvips/arithmetic/find_trim.c:96:39: error: assignment of read-only member ‘background’
96 |                 find_trim->background = vips_array_double_newv(1,
|                                       ^
../libvips/colour/icc_transform.c: In function ‘vips_icc_export_build’:
../libvips/colour/icc_transform.c:1003:26: error: assignment of read-only member ‘pcs’
1003 |                 icc->pcs = VIPS_PCS_XYZ;
|                          ^
../libvips/foreign/magick7load.c: In function ‘vips_foreign_load_magick7_build’:
../libvips/foreign/magick7load.c:313:28: error: assignment of …
```
=> Add missing FIXMEs

ChangeLog, libvips/morphology/morph.c
It looks like we haven't been limiting the maximum number of constants, as we do in `convi`. Regressed since commit b32cb5ec4dce696672218a3aeca9292c08ca23e7, previously this was handled in `vips_vector_full()`.
Resolves: #4363.
=> morph: fix Orc path with large masks

ChangeLog, libvips/colour/icc_transform.c, libvips/include/vips/colour.h
Via the `VIPS_INTENT_AUTO` enum value.
Resolves: #3475.
=> colour: add support for auto-selecting the rendering intent

libvips/colour/icc_transform.c, libvips/conversion/copy.c, libvips/create/text.c, libvips/foreign/cgifsave.c, libvips/foreign/exif.c, libvips/foreign/foreign.c, libvips/foreign/jpeg2vips.c, libvips/foreign/jxlload.c, libvips/foreign/magick.c, libvips/foreign/ppmsave.c, libvips/foreign/spngsave.c, libvips/foreign/tiff2vips.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vips2tiff.c, libvips/foreign/vipspng.c, libvips/iofuncs/generate.c, libvips/iofuncs/memory.c, libvips/mosaicing/global_balance.c, po/de.po, po/en_GB.po, po/malkovich.po, tools/vips.c, tools/vipsthumbnail.c
The recommended approach (a.k.a. "policy") is to not provide translations for warning messages.
I've manually removed only a subset of unused entries from the .po files to keep the diff clean. Once this PR is merged I'll do a follow-up to fully refresh the rest of the translation files e.g. remove all other no longer used entries, update line numbers etc.
Fixes https://github.com/libvips/libvips/issues/3210
=> Ensure g_warning messages use consistent i18n approach

libvips/foreign/foreign.c, libvips/foreign/magick.c, libvips/foreign/ppmsave.c, libvips/foreign/vips2tiff.c, po/de.po, po/en_GB.po, tools/vips.c, tools/vipsthumbnail.c
Mostly-automated:
- Apply `git clang-format` to commit da5803e
- Remove empty/outdated/non-automated headers from translation files
- Run `meson compile vips8.17-update-po` to automagically update translation files
=> i18n: refresh translations

ChangeLog, libvips/foreign/matrixload.c
matrixload is_a could fail to detect files like this:
```
2 2
0 0
1 1
```
The header parser was not stopping at EOL and thought that this file had scale 0, which it would then reject.
=> fix matrixload sniff for some matrix files

ChangeLog, libvips/create/invertlut.c
If the measurements filled the entire x range, we were not writing the final value.
For example:
```
2 2
0 0
1 1
```
```
$ vips invertlut linear.mat x2.v
$ vips getpoint x2.v 255 0
-nan
```
With this PR you get 1, as expected.
=> fix invertlut in some cases

ChangeLog, libvips/foreign/radiance.c
Ensure PRIMARIES and COLORCORR have expected number of components.
=> radload: improve sanity check of colour-related headers

ChangeLog, libvips/foreign/svgload.c, meson.build, test/test-suite/test_foreign.py
This PR exposes a new `stylesheet` option for custom User Origin CSS to apply when rendering SVG images. This feature requires librsvg version 2.48.0 or later.
The underlying `rsvg_handle_set_stylesheet` method will accept strings of CSS containing `NULL` but doing so is probably a bad idea and isn't supported by this PR. More importantly, by not allowing this, we can use `g_utf8_validate` and friends to sanitise the input.
Closes https://github.com/libvips/libvips/discussions/4333 and https://github.com/libvips/libvips/issues/4334
=> svgload: add support for custom CSS via stylesheet option

ChangeLog, libvips/resample/meson.build, libvips/resample/presample.h, libvips/resample/shrinkh.c, libvips/resample/shrinkh_hwy.cpp, libvips/resample/shrinkv.c, libvips/resample/shrinkv_hwy.cpp
This PR optimizes the `shrink{h,v}` operations by using portable SIMD/vector instructions via Highway.
On my AMD Ryzen 9 7900 workstation, this implementation shows a noticeable speed improvement, ranging from ~25% to ~32% times faster, while maintaining identical output to the C implementations (verified on various targets in [this gist](https://gist.github.com/kleisauke/1f28a9fc156c753bcb1239b6fc1a2e62)). See the benchmark results at:
https://github.com/kleisauke/vips-microbench/blob/master/results/shrink-highway.md
=> shrink{h,v}: improve performance using Highway

ChangeLog, libvips/foreign/heifload.c, libvips/foreign/heifsave.c
i.e. when the `unlimited` flag is set (> 16384x16384).
See: https://github.com/libvips/libvips/pull/4266#discussion_r1856394879.
=> heifload: prevent possible int overflow for large images

ChangeLog, libvips/foreign/tiff.c
We weren't looping on `vips_source_read()` in tiffload, which could cause failures when reading from pipes.
Resolves: #4400.
Note that I couldn't find any documentation for this callback, but I noticed that `TIFFOpen*()` behaves similarly, see:
https://gitlab.com/libtiff/libtiff/-/blob/v4.7.0/libtiff/tif_unix.c#L68-95
=> tiffload: add missing read loop

test/test_timeout_gifsave.c
On my AMD Ryzen 9 7900 workstation, the `gifsave_timeout` test consistently fails with:
```console
$ meson test -C build --print-errorlogs
...
8/12 gifsave_timeout          FAIL             2.46s   exit status 1
――― ✀ ―――
expected error return from vips_gifsave_buffer()
――――――――――
```
I suspect the image gets quantized/remapped within 2 seconds, so we can't guarantee that it always returns an error. The best we could do is `g_assert(is_killed)`, which is a no-op in release builds.
=> test: reduce severity of `gifsave_timeout`

ChangeLog, libvips/iofuncs/type.c
Nothing serious as this is was in debugging logic, but worth moving all the same.
=> Prevent possible use-after-free when debugging via --vips-leak flag

libvips/colour/HSV2sRGB.c, libvips/colour/LCh2Lab.c, libvips/colour/LCh2UCS.c, libvips/colour/Lab2LCh.c, libvips/colour/Lab2LabQ.c, libvips/colour/LabQ2Lab.c, libvips/colour/LabQ2sRGB.c, libvips/colour/UCS2LCh.c, libvips/colour/XYZ2Lab.c, libvips/colour/Yxy2XYZ.c, libvips/colour/dE76.c, libvips/colour/icc_transform.c, libvips/colour/sRGB2HSV.c, libvips/colour/scRGB2XYZ.c, libvips/create/eye.c, libvips/create/grey.c, libvips/create/mask.c, libvips/create/perlin.c, libvips/create/point.c, libvips/create/sdf.c, libvips/create/sines.c, libvips/create/worley.c, libvips/create/zone.c, libvips/foreign/ppmload.c, libvips/foreign/radiance.c, libvips/foreign/tiff2vips.c, libvips/morphology/nearest.c
Found with clang-tidy 19.1.7, see:
https://gist.github.com/kleisauke/9025c3564d3aec17496bd21d675908fb
Context: https://github.com/libvips/libvips/pull/3935#issuecomment-2081489038.
=> clang-tidy: avoid narrowing conversions

ChangeLog, libvips/convolution/convi.c
The `CONV_FLOAT` inner loop macro is used for both `float` and `double` images so the type of `sum` should probably match.
I've not had a chance to performance test this change but it has the possibility of making integer convolution of float images a tiny bit faster.
=> convi: ensure double sum precision for floats

libvips/foreign/dzsave.c
Originally reported at https://github.com/lovell/sharp/issues/4346 - the sample image of 39125x34708 split into 1024x1024 tiles correctly generated 7 levels in the IIIF pyramid but it looks like the `scaleFactors` calculation was only considering the first 6.
=> dzsave: ensure IIIF scaleFactors includes all levels

ChangeLog, libvips/colour/icc_transform.c
Some LCMS versions (i.e. before commit https://github.com/mm2/Little-CMS/commit/f3f6b7bceb629bc4b6f1dea3e45b44dc3f8674af or https://github.com/mm2/Little-CMS/commit/6223d3d3c8339eadba2230a0112cdeaca72c080e) would fail on corrupted ICC profiles.
<details>
<summary>Test case</summary>
```c
/* Compile with:
* gcc -g -Wall test-lcms2.c `pkg-config lcms2 --cflags --libs`
*/
#include <lcms2.h>
int main(int argc, char *argv[]) {
if (argc != 2) {
printf("usage: %s input\n", argv[0]);
return 1;
}
printf("LittleCMS %2.2f\n", cmsGetEncodedCMMversion() / 1000.0);
cmsHPROFILE profile;
if (!(profile = cmsOpenProfileFromFile(argv[1], "r"))) {
printf("corrupt profile\n");
return 1;
}
cmsUInt32Number intent = cmsGetHeaderRenderingIntent(profile);
printf("cmsGetHeaderRenderingIntent = %u\n", intent); …
```
=> Improve guard against corrupt ICC profiles

ChangeLog, libvips/foreign/heifload.c
Ensures we check both the `old_position` and `result` for a possible error when seeking.
Fixes https://issues.oss-fuzz.com/issues/404288018
=> heifload: improve detection of seek beyond EOF

ChangeLog, libvips/iofuncs/sinkscreen.c
In the old model, there was a single rendering thread that moved between
the active sink_screen tasks by priority. If a thumbnail and a main
image window both needed updating, the thumbnail render (which can take
a long time since it is effectively single-threaded) could block
all high-priority updates.
This PR adds private threadpools for low priority vips_sink_screen()
rendering tasks. Now all thumbnails will update in the background as
single-threaded tasks, and will not block foreground updates.
=> Private threadpool

libvips/iofuncs/threadset.c
Track the number of threads that haven't reached their entry point to prevent thread oversubscription, which could occur on Wasm.
This issue likely did not affect other environments, where thread spawning is usually instant.
See: https://github.com/kleisauke/wasm-vips/issues/92.
=> threadset: prevent possible thread oversubscription on Wasm

libvips/foreign/openslideload.c, meson.build
OpenSlide 3.4.0 was released in January 2014.
=> openslideload: drop support for OpenSlide 3.3.x

libvips/include/vips/internal.h, libvips/iofuncs/init.c
Alternatively, we could make `vips__openslideconnection_leak()` always available, just like:
https://github.com/libvips/libvips/blob/dbc3b86054208b2d9915e5ebdf7a0c3d022013e0/libvips/include/vips/internal.h#L102-L105
But I'm not sure if that's worth it, since this logic is only for `VIPS_LEAK`.
=> openslideconnection: fix link failure with modules enabled

doc/file-format.md, doc/libvips-header.md, libvips/iofuncs/header.c
Ensure methods such as `vips_image_get()` can be referenced as `[method@Image.get]` instead of `[method@Image.image_get]`.
=> doc: remove a couple of redundant `(method)` overrides

libvips/colour/XYZ2scRGB.c, libvips/colour/colour.c, libvips/colour/scRGB2XYZ.c
We were changing the interpretation in icc_import and icc_export, but we were not rescaling the alpha. As a result, 16-bit RGBA images had a alpha of 65535 in PCS, not 255.
This PR moves alpha channel scaling into the base VipsColour class, so we get correct scaling automatically, and moves XYZ <-> scRGB conversion back on top of VipsColourCode, partially reverting #3627
see https://github.com/libvips/libvips/issues/4343
=> fix linear resize of 16-bit rgba

libvips/foreign/cgifsave.c, libvips/foreign/jxlsave.c, libvips/foreign/webpsave.c
we could modify a const pointer in some cases, causing unexpected side effects via the operation cache
see https://github.com/libvips/libvips/issues/4479
=> fix delay metadata for webp and jxl save

fuzz/oss_fuzz_build.sh
Mitigates issue https://github.com/mesonbuild/meson/issues/14524, the fuzz introspector build was already broken for some time due to https://github.com/google/oss-fuzz/pull/12983#issuecomment-2659255900.
This reverts commit 50caa1922fa88e02c8cbfb3192fe8282d7da6eee.
=> Revert "OSS-Fuzz: limit link jobs to 4 (#4108)"

fuzz/oss_fuzz_build.sh
Hopefully this would fix the failing CIFuzz build:
https://github.com/libvips/libvips/actions/runs/14728728549/job/41339474476
=> OSS-Fuzz: disable build of examples in spng

fuzz/oss_fuzz_build.sh
By appending the sanitizer-specific flags to the `LDFLAGS` env.
=> OSS-Fuzz: add workaround for mesonbuild/meson#14533

suppressions/lsan.supp
This was fixed in pyvips v3.0.
=> lsan: remove pyvips suppression

ChangeLog, doc/using-vipsthumbnail.md, libvips/resample/thumbnail.c, man/vipsthumbnail.1, test/test-suite/test_resample.py, tools/vipsthumbnail.c
We use `input-profile` and `output-profile` everywhere else, but `thumbnail` calls them `import-profile` and `export-profile`, confusingly. LittleCMS seems to use `input-profile` and `output-profile` too.
=> rename thumbnail's profile arguments

libvips/include/vips/enumtypes.c.in, libvips/include/vips/enumtypes.h.in
Otherwise, it will end up including `vips_saveable_get_type()` in the docs.
=> Ignore VipsSaveable type when generating introspection data

libvips/iofuncs/image.c, libvips/iofuncs/object.c, libvips/iofuncs/operation.c, libvips/iofuncs/region.c
I missed these in PR #4500. These occurrences were found using this regex: `(?s)/\* .*\[.*@.*\].* \*/` :sweat_smile:.
=> doc: avoid gi-docgen linking syntax for non-doc comments

libvips/resample/presample.h, libvips/resample/shrinkv.c, libvips/resample/shrinkv_hwy.cpp
i.e. read up to 16 (i.e. fatstrip) scanlines at a time.
Resolves: #4170.
=> shrinkv: align chunking with shrinkh

ChangeLog, libvips/foreign/heifload.c, libvips/foreign/heifsave.c, meson.build
Aligns with the libheif version provided by Debian 11, which seems to be the oldest version provided by any actively supported flavour of Linux (Ubuntu 20.04 is EOL this month).
=> Increase minimum version of libheif dependency to 1.11.0

libvips/resample/shrinkv.c
=> shrinkv: avoid possible overflow during multiplication

ChangeLog, libvips/foreign/heifload.c, meson.build
The upstream default is 4GB, which is too big for the fuzz test environment and IMHO is too big for a sensible default. Halving the default limit to 2GB means all the current "Out-of-memory" fuzz test failures will go away, and seems to be sufficient to process all the HEIF images I've tested with. It is however an(other) arbitrary value and I'd be happy to modify it based on further feedback.
The existing `unlimited` flag can be used to remove this.
Before:
```
$ vips heifload clusterfuzz-testcase-minimized-rawsave_buffer_fuzzer-6038980984635392
clusterfuzz-testcase-minimized-rawsave_buffer_fuzzer-6038980984635392: bad seek to 1024
...
heif: Invalid input: Unexpected end of file (2.100)
```
After:
```
$ vips heifload clusterfuzz-testcase-minimized-rawsave_buffer_fuzzer-6038980984635392 …
```
=> heifload: limit per-image memory usage to 2GB by default

ChangeLog, cplusplus/include/vips/VImage8.h, libvips/foreign/cairo.c, libvips/foreign/svgload.c, libvips/include/vips/internal.h, meson.build
With the increasing demand for high quality images - a need of rendering SVG with increased color-depth (more than 8 bit) has also appeared. 
Given Cairo introduced support for new data format unlocking this option for libvips -  `CAIRO_FORMAT_RGBA128F`: https://www.cairographics.org/news/cairo-1.17.2/ - this PR is an attempt to introduce `rgb128` flag into `svgload` to enable high-bit SVG rendering if needed.
=> svgload: introduce rgb128 parameter for SVG 128-bit load support

libvips/arithmetic/measure.c, libvips/colour/icc_transform.c, libvips/conversion/tilecache.c, libvips/create/text.c, libvips/foreign/csvload.c, libvips/foreign/exif.c, libvips/foreign/jpeg2vips.c, libvips/foreign/spngload.c, libvips/foreign/vips2jpeg.c, libvips/foreign/vipspng.c, libvips/histogram/maplut.c, libvips/iofuncs/image.c, libvips/iofuncs/init.c, libvips/iofuncs/memory.c, libvips/iofuncs/system.c, libvips/iofuncs/thread.c, libvips/iofuncs/vips.c, po/de.po, po/en_GB.po
In line with PR #4369.
This change was mostly automated with ast-grep:
```yaml
id: remove_i18n_from_g_warning
language: c
rewriters:
- id: i18n-remove
rule:
kind: call_expression
pattern: $ARG
constraints:
ARG: { regex: ^_ } # Only match if it starts with '_'
transform:
NEW_ARG:
substring:
source: $ARG
startChar: 2
endChar: -1
fix: $NEW_ARG
rule:
pattern:
context: g_warning($$$ARGS);
selector: call_expression
transform:
REMOVE_I18N_ARGS:
rewrite:
rewriters: [i18n-remove]
source: $$$ARGS
fix: g_warning($REMOVE_I18N_ARGS)
```
```console
$ ast-grep scan -r remove-i18n-from-g_warning.yml -U libvips/
Applied 106 changes
```
=> Apply i18n policy to all g_warning messages

libvips/colour/pcolour.h, libvips/colour/sRGB2scRGB.c, libvips/foreign/cairo.c, libvips/foreign/svgload.c, libvips/include/vips/internal.h
As it was pointed out in discussion here: https://github.com/libvips/libvips/pull/4529 - performing additional `vips_gamma` operation does not guarantee enough similarity between `high_biptdepth=true|false` outputs. 
As suggested - it turns out that `librsvg` - instead of simple pow operation applies sRGB curve as shown here:
https://github.com/GNOME/librsvg/blob/2.60.0/rsvg/build.rs#L28
This PR introduces port of mentioned logic and uses it as part of `svgload` pipeline. 
Please let me know if there's already an existing equivalent function available I should use instead and if there's a better place to apply it to pixels.
=> svgload: replaced vips_gamma with linearization through LUT usage

doc/check-sections.py
Noticed this while trying to build libvips for RHEL 9 (and its derivatives).
<details>
```console
stderr:
File "/builddir/build/BUILD/libvips-05d80c09c9168a6c5a2241b4b83284f13ca9e709/doc/check-sections.py", line 42
f'{{{namespace['goi']}}}alias': lambda n, _ : f'[alias@{n.attrib['name']}]',
^
SyntaxError: f-string: unmatched '['
```
</details>
=> doc: ensure `check-sections.py` works with Python < 3.12

fuzz/oss_fuzz_build.sh
Both issues[^1][^2] have been resolved in Meson 1.8.1, though this uncovered a new Meson bug[^3], for which I added a workaround in commit 695cb9bec7c438013f6e1bef179b7c39589df938.
[^1]: https://github.com/mesonbuild/meson/issues/14524
[^2]: https://github.com/mesonbuild/meson/issues/14533
[^3]: https://github.com/mesonbuild/meson/issues/14640
=> OSS-Fuzz: revise Meson-specific workarounds

libvips/foreign/matrixload.c, test/test-suite/test_connection.py
As required by `g_strlcpy()`.
<details>
```console
=================================================================
==5472==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x12acb2f65b40 at pc 0x7ffa9109cdc8 bp 0x00551e3fb3d0 sp 0x00551e3fb418
READ of size 1 at 0x12acb2f65b40 thread T-1
#0 0x7ffa9109cdc7 in g_strlcpy /var/tmp/tmp-glib-x86_64-w64-mingw32.shared.all.debug/glib-2.85.0.build_/../glib-2.85.0/glib/gstrfuncs.c:1476:14
#1 0x7ffa9185d214 in vips_foreign_load_matrix_source_is_a_source /var/tmp/tmp-vips-all-x86_64-w64-mingw32.shared.all.debug/libvips-libvips-8f95205.build_/../libvips-libvips-8f95205/libvips/foreign/matrixload.c:432:2
#2 0x7ffa9182b30a in vips_foreign_find_load_source_sub …
```
=> matrixload: ensure sniff data is null-terminated

cplusplus/meson.build
Previously, Doxygen documentation was installed in `doc/vips-doc`, which could be confused with GI-DocGen output located in `doc/vips`.
=> cplusplus: install Doxygen docs in `doc/vips-cpp`

_posts/2017-03-16-What's-new-in-8.5.md, _posts/2017-11-28-What's-new-in-8.6.md, _posts/2018-04-10-libvips-for-dot-net.md, _posts/2018-07-26-What's-new-in-8.7.md, _posts/2019-04-22-What's-new-in-8.8.md, _posts/2019-11-29-True-streaming-for-libvips.md, _posts/2019-12-11-What's-new-in-8.9.md, _posts/2020-06-18-What's-new-in-8.10.md, _posts/2020-09-01-libvips-for-webassembly.md, _posts/2021-03-08-ruby-vips-mutate.md, _posts/2021-06-04-What's-new-in-8.11.md, _posts/2022-05-28-What's-new-in-8.13.md, _posts/2023-10-10-What's-new-in-8.15.md, _posts/2024-10-10-What's-new-in-8.16.md, _posts/2025-01-31-nip4-January-progress.md, _posts/2025-03-12-nip4-for-nip2-users.md, _posts/2025-03-20-introduction-to-nip4.md, _posts/2025-06-05-What's-new-in-8.17.md
In preparation for PR #4457. 
Also, make all links in news posts relative. Note that some of them were already relative, see e.g.:
https://github.com/libvips/libvips/blob/4b693ddde72f92a751710ea18c2bc919898614d4/_posts/2023-10-10-What's-new-in-8.15.md#L140-L146
=> Update links in news posts

doc/meson.build
Fixes #4558
(Targets the master branch as 8.17 branch not yet created.)
=> Meson custom_target name is mandatory prior to 0.60.0

ChangeLog, libvips/foreign/dcrawload.c, libvips/foreign/foreign.c, libvips/include/vips/foreign.h
libraw has a buffer and a file interface. If you use the file interface, it's able to read secondary files and extract more metadata.
TODO
=> more work on dcrawload

ChangeLog, libvips/foreign/foreign.c, libvips/foreign/magick6load.c, libvips/foreign/magick7load.c, libvips/foreign/magickload.c, libvips/include/vips/foreign.h, libvips/module/magick.c, test/test-suite/test_foreign.py
test with eg.:
```
$ cat MARBLES.BMP | vips magickload_source "[descriptor=0]" x.v
$ cat MARBLES.BMP | vipsthumbnail stdin -o x.jpg
```
ImageMagick doesn't support generic IO, so it just maps the source into memory and uses the buffer interface.
magick6 and magick7.
See https://github.com/libvips/libvips/issues/4530
=> add magickload_source

ChangeLog, libvips/iofuncs/cache.c
These diagnostics are only useful during development and debugging.
See: #4595.
Targets the 8.17 branch.
=> cache: suppress invalidation errors in release builds

libvips/iofuncs/cache.c
Trivial backport of ee262ff45d1fc870e38091e04d0861537f0e302c to [`8.17`](https://github.com/libvips/libvips/tree/8.17), plus extended to guard `vips_operation_copy_argument()` as well.
=> Fix `-Wunused-function` warning

ChangeLog, libvips/foreign/dzsave.c, test/test-suite/test_foreign.py
Will improve compliance with IIIF v2 and v3, the specs of which both mandate support for the "full" region.
- https://iiif.io/api/image/2.0/compliance/#region
- https://iiif.io/api/image/3.0/compliance/#31-region
I've checked OpenLayers and OpenSeadragon and they both contain the same logic so it should address most of https://github.com/libvips/libvips/discussions/2036
- https://github.com/openlayers/openlayers/blob/7cf17b80aeefe7e6de867703f4239b362b19496b/src/ol/source/IIIF.js#L263-L270
- https://github.com/openseadragon/openseadragon/blob/a02c2456d972dd23f9c8d106ffbd2b29efcf56d1/src/iiiftilesource.js#L509-L513
This PR only handles the "region" part of the URL and doesn't touch the "size" as (I think) as long as the tile size is smaller than the original image size in either (or both) …
=> dzsave: IIIF: use named region of 'full' when no crop takes place

ChangeLog
I think it's time for a formal patch release.
We might also consider including a variant of PR #4599 in v8.17.1, although I think most users are already using the latest PDFium releases, i.e. similar to our approach in OSS-Fuzz:
https://github.com/google/oss-fuzz/blob/76d5d6351e09fc2a9da9e057001cd5daecb1b6a2/projects/libvips/Dockerfile#L37
=> Update ChangeLog ahead of v8.17.1

ChangeLog, libvips/foreign/foreign.c, libvips/include/vips/internal.h, libvips/include/vips/private.h, libvips/iofuncs/image.c, libvips/iofuncs/vips.c, libvips/iofuncs/window.c
At the moment, formats like JPEG will convert to uncompressed `.v` images in tmp and then be mapped into memory for processing.  In order to limit VMEM usage, this mapping is windowed, so only a few 100 scanlines are mapped at once.
However, this can cause severe performance issues with applications needing random pixel access, for example, image viewers. A viewer which is updating the screen in parallel will make scattered reads to the image, and each read will force the mmap window to scroll. With a large image, almost all time will be spent blocked on ioctl().
This PR makes the mmap window *much* larger, up to about 20,000 scanlines. Modern machines have much more VMEM available, so I think this will be OK.
Performance of interactive applications can improve by several 100 times.
=> use much larger mmap windows

libvips/foreign/magick.c
otherwise we mistake it for TGA
see https://github.com/libvips/libvips/issues/4612
=> add a sniffer for the XWD format

libvips/iofuncs/operation.c, tools/vips.c
Only possible for classes that have already been referenced before.
=> Simplify using `g_type_class_peek()`

fuzz/oss_fuzz_build.sh
The issue was resolved in Meson 1.8.3.
This reverts commit 6d9b90ae41f0710f7fb565324cbfc3b10df57c0b.
=> Revert "OSS-Fuzz: add workaround for mesonbuild/meson#14640"

suppressions/lsan.supp
The `___kmp_allocate` suppression applies to libomp (LLVM's OpenMP runtime library), but we also need to suppress `GOMP_parallel` when libgomp (GCC's OpenMP runtime library) is transitively used.
I noticed this while attempting to remove `-fopenmp` and `-fopenmp=libomp` from the CI configuration, since libvips itself doesn't use OpenMP, see:
https://github.com/kleisauke/libvips/actions/runs/16810815668/job/47616673957
=> lsan: suppress leak warnings for libgomp

.gitattributes
This was formatted in PR #4621 under the assumption that GitHub used 8-column tab stops by default, but that's no longer the case after:
https://github.blog/changelog/2025-08-07-default-tab-size-changed-from-eight-to-four/
(we could use spaces here, but tabs make it easier to confirm your tab size preference)
=> Reformat .gitattributes

ChangeLog, meson.build
The FP16/BF16 ops that these targets introduce are unused by us.
`vips --targets` diff:
```diff
@@ -1,4 +1,4 @@
$ vips --targets
-builtin targets:   AVX10_2 AVX3_SPR AVX3_ZEN4 AVX3_DL AVX3 AVX2 SSE4 SSE2
+builtin targets:   AVX3_DL AVX3 AVX2 SSE4 SSE2
supported targets: AVX3_ZEN4 AVX3_DL AVX3 AVX2 SSE4 SSSE3 SSE2
```
Context: https://github.com/lovell/sharp-libvips/commit/7f16f4eb9d8c5696748636df4a1c50db49d107b2#commitcomment-164146435.
Targets the 8.17 branch.
=> Disable redundant Highway AVX512 targets

ChangeLog, libvips/foreign/svgload.c
Pass the user-specified DPI to librsvg so that SVG elements using non-pixel units (e.g., mm, cm, in) are scaled correctly. Previously, these elements were always rendered at 72 DPI, which could result in incorrect sizes.
Resolves: #4628.
Targets the 8.17 branch.
=> svgload: honor DPI when scaling elements with non-pixel units

ChangeLog, libvips/foreign/tiff.c, libvips/foreign/tiff2vips.c
Ensures TIFF processing halts:
- for known-fatal errors relating to memory allocation
- for all other errors when `fail_on` is set to the `error` level or higher
Also, in a separate commit, increases the memory limit from 20MB to 50MB.
Fixes https://github.com/libvips/libvips/issues/4649
=> tiffload: improve handling of memory-related errors

libvips/foreign/tiffload.c
See commit dcb1df8 (discovered via https://github.com/libvips/libvips/issues/4664).
=> tiffload: ensure docs match memory limit behaviour

tools/vips.c
The "vips" driver program was not freeing the option parser on error. It doesn't matter at all, but fixing it makes valgrind output a little cleaner.
I now see:
```
$ valgrind --leak-check=full vips
==1207207== Memcheck, a memory error detector
==1207207== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==1207207== Using Valgrind-3.24.0 and LibVEX; rerun with -h for copyright info
==1207207== Command: vips
==1207207== 
Usage:
vips [OPTION…] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program
Help Options:
-h, --help                     Show help options
Application Options:
-t, --targets                  print vector targets
...
--vips-pipe-read-limit         read at most this many bytes from a pipe
==1207207== 
==1207207== HEAP SUMMARY:
==1207207==     in use at exit: …
```
=> fix trivial memleaks in "vips" driver prog

ChangeLog, cplusplus/VImage.cpp
The cpp binding could leak references for uncollected optional output images.
See https://github.com/libvips/libvips/issues/4662
Thanks @VivitionDeveloper
=> fix a cpp binding leak
