libvips/libvips

- cplusplus/include/vips/vips-operators.h
- cplusplus/vips-operators.cpp
- doc/function-list.xml
- libvips/foreign/foreign.c
- libvips/foreign/magick.h
- libvips/foreign/magick2vips.c
- libvips/foreign/magickload.c
- libvips/include/vips/foreign.h
- python/Vips.py
This commits adds buffer support for the ImageMagick backend, using the Blob
API.
> Add ImageMagick buffer support

- libvips/create/text.c
Didn't find any test for vips_text, so I guess it's okay to just add this?
> create/text: adding linespacing support

- bootstrap.sh
* Clean doc dir with find instead of moving files to keep to temp dir (old code could break on ctrl+c)
* Limited support for automake ACDIR dirlists (require for mac homebrew, no wildcard handling)
> bootstrap.sh: Better doc pruning / support acdir dirlists

- libvips/arithmetic/hist_find.c
Hi John, 
I hope to use `vips_hist_entropy` for a couple of shiny new features in sharp so took the liberty of perusing libvips' histogram code.
As the original comment in `vips_hist_find_uchar_scan` rightly suggested, the inner loop of the histogram builder can't be auto-vectorized by the compiler.
However, by manually unrolling this loop for the common cases of 1-4 band uchar images, I see a 3x reduction in instruction count and a 5x reduction in branch count for the `vips_hist_find_uchar_scan` function, resulting in an overall improvement for `vips_hist_find` of around 30%.
As always, feedback on a more elegant way to achieve this or correction of duff maths is welcome :)
Below are some timings and callgrind stats for a 10000x10000 3 band uncompressed VIPS image.
Before:
```sh
$ time …
```
> vips_hist_find: ~30% performance improvement for 1-4 band uchar

- cplusplus/include/vips/VImage8.h
Testing v8.3.0 with Windows, as promised :)
> Allow MSVC to link CPP overloads introduced in da43a40

- cplusplus/include/vips/vips-operators.h
- cplusplus/vips-operators.cpp
- libvips/arithmetic/arithmetic.c
- libvips/foreign/foreign.c
- libvips/foreign/radiance.c
- libvips/foreign/radiance.h
- libvips/foreign/radsave.c
- libvips/include/vips/foreign.h
As `dzsave` only supports buffer output, I added `radsave_buffer` functionality and split the class into file and buffer subclasses as in `pngsave.c`
> Add buffer write support for HDR Radiance

- libvips/foreign/dzsave.c
This improves the checks on when to abort dzsave due to lack of ZIP64
support in libgsf. ZIP64 is required for archives/files larger than 4GB
and if more than 65535 files need to be stored, which is the more likely
limit to hit when saving zoom images.
* Add check to abort when exceeding the 64k file limit
* Modify size check to account for per file and directory overhead
The previous estimation was ways off, subtracting only 100k for overhead
when the actual overhead would be several megabytes for file counts near
the limit.
Estimation Basis:
Per file overhead: 30B fixed size fields + filename + extras
Central directory overhead: 46B fixed size fields + filename + extras
End of central directory: 22B fixed size fields
ZIP64 specific header sizes are not estimated, because the checks are …
> [WIP] More accurate dzsave zip size estimation

- libvips/foreign/dzsave.c
> Revert "[WIP] More accurate dzsave zip size estimation"

- libvips/foreign/jpeg2vips.c
Pull request for the issue mentioned here https://github.com/jcupitt/libvips/issues/516
> Better support for exif resolution

- libvips/iofuncs/error.c
- libvips/iofuncs/generate.c
- libvips/iofuncs/header.c
- libvips/iofuncs/image.c
- libvips/iofuncs/memory.c
- libvips/iofuncs/object.c
- libvips/iofuncs/operation.c
- libvips/iofuncs/rect.c
- libvips/iofuncs/region.c
- libvips/iofuncs/reorder.c
- libvips/iofuncs/sink.c
- libvips/iofuncs/sinkdisc.c
- libvips/iofuncs/sinkscreen.c
- libvips/iofuncs/threadpool.c
- libvips/iofuncs/type.c
> Update GObject introspection annotations for libvips/iofuncs directory

- libvips/colour/HSV2sRGB.c
- libvips/colour/LCh2Lab.c
- libvips/colour/LCh2UCS.c
- libvips/colour/Lab2LCh.c
- libvips/colour/Lab2LabQ.c
- libvips/colour/Lab2LabS.c
- libvips/colour/Lab2XYZ.c
- libvips/colour/LabQ2Lab.c
- libvips/colour/LabQ2LabS.c
- libvips/colour/LabQ2sRGB.c
- libvips/colour/LabS2Lab.c
- libvips/colour/LabS2LabQ.c
- libvips/colour/UCS2LCh.c
- libvips/colour/XYZ2Lab.c
- libvips/colour/XYZ2Yxy.c
- libvips/colour/XYZ2scRGB.c
- libvips/colour/Yxy2XYZ.c
- libvips/colour/colourspace.c
- libvips/colour/dE76.c
- libvips/colour/dECMC.c
- libvips/colour/float2rad.c
- libvips/colour/icc_transform.c
- libvips/colour/rad2float.c
- libvips/colour/sRGB2HSV.c
- libvips/colour/sRGB2scRGB.c
- libvips/colour/scRGB2BW.c
- libvips/colour/scRGB2XYZ.c
- libvips/colour/scRGB2sRGB.c
> Update GObject introspection annotations for libvips/colour directory

- libvips/draw/draw_circle.c
- libvips/draw/draw_flood.c
- libvips/draw/draw_image.c
- libvips/draw/draw_line.c
- libvips/draw/draw_mask.c
- libvips/draw/draw_rect.c
- libvips/draw/draw_smudge.c
> Update GObject introspection annotations for libvips/draw directory

- configure.ac
- libvips/freqfilt/freqmult.c
- libvips/freqfilt/fwfft.c
- libvips/freqfilt/invfft.c
- libvips/freqfilt/phasecor.c
- libvips/freqfilt/spectrum.c
#741 
`freqfilt.h` had to be added to `headers` in `configure.ac`
> Update GObject instrospection annotations for libvips/freqfilt directory

- configure.ac
- libvips/histogram/hist_cum.c
- libvips/histogram/hist_entropy.c
- libvips/histogram/hist_equal.c
- libvips/histogram/hist_ismonotonic.c
- libvips/histogram/hist_local.c
- libvips/histogram/hist_match.c
- libvips/histogram/hist_norm.c
- libvips/histogram/hist_plot.c
- libvips/histogram/maplut.c
- libvips/histogram/percent.c
- libvips/histogram/stdif.c
#741 
`histogram.h` had to be added to `headers` in `configure.ac`
> Update GObject introspection annotations for libvips/histogram directory

- configure.ac
- libvips/mosaicing/global_balance.c
- libvips/mosaicing/im_remosaic.c
- libvips/mosaicing/match.c
- libvips/mosaicing/merge.c
- libvips/mosaicing/mosaic.c
#741 
`mosaicing.h` had to be added to `headers` in `configure.ac`
> Update GObject introspection annotations for libvips/mosaicing directory

- configure.ac
- libvips/create/black.c
- libvips/create/buildlut.c
- libvips/create/eye.c
- libvips/create/fractsurf.c
- libvips/create/gaussmat.c
- libvips/create/gaussnoise.c
- libvips/create/grey.c
- libvips/create/identity.c
- libvips/create/invertlut.c
- libvips/create/logmat.c
- libvips/create/mask_butterworth.c
- libvips/create/mask_butterworth_band.c
- libvips/create/mask_butterworth_ring.c
- libvips/create/mask_fractal.c
- libvips/create/mask_gaussian.c
- libvips/create/mask_gaussian_band.c
- libvips/create/mask_gaussian_ring.c
- libvips/create/mask_ideal.c
- libvips/create/mask_ideal_band.c
- libvips/create/mask_ideal_ring.c
- libvips/create/perlin.c
- libvips/create/sines.c
- libvips/create/text.c
- libvips/create/tonelut.c
- libvips/create/worley.c
- libvips/create/xyz.c
- libvips/create/zone.c
#741 
`create.h` had to be added to `headers` in `configure.ac`
> Update GObject introspection annotations for libvips/create directory

- install.md
...as I noticed this step was missing when helping to investigate https://github.com/lovell/sharp/issues/980
> Add ldconfig step to building instructions

- libvips/colour/sRGB2scRGB.c
Hi John, this PR moves some of the logic in `vips_sRGB2scRGB_gen` so the `BandFmt` conditional is outside the outer for-loop. It then adds optimised paths to the inner for-loop for common 3 (RGB) and 4 (RGBA) band input images. This reduces the instruction count per pixel by 5, including the removal of 2 branches.
Before:
```sh
$ time vips colourspace 10000x10000.v out.v scrgb
real    0m9.478s
user    0m1.340s
sys     0m1.240s
```
```
3,900,000,014  ???:vips_col_sRGB2scRGB_8 [/usr/local/lib/libvips.so.42.8.0]
2,301,250,004  ???:vips_sRGB2scRGB_gen [/usr/local/lib/libvips.so.42.8.0]
1,200,211,873  /build/glibc-bfm8X4/glibc-2.23/string/../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:__memcpy_avx_unaligned [/lib/x86_64-linux-gnu/libc-2.23.so]
```
After:
```sh    
$ time vips colourspace …
```
> Colour: ~20% sRGB to scRGB speedup for 3/4 channel images

- libvips/create/buildlut.c
- libvips/resample/bicubic.cpp
- libvips/resample/transform.c
Hi John, this small PR removes compilation errors from the following:
```sh
CFLAGS="-DDEBUG" CXXFLAGS="-DDEBUG" ./configure && make
```
> Allow compilation of debug build

- README.md
There were some broken links on the wiki.
> Fixing links for Build for Windows & OS X.

- _posts/2018-04-10-libvips-for-dot-net.md
As requested. I took the Lua binding blog post as model.
Let me know if anything needs to be changed.
> Blog post for NetVips

- README.md
relative links no longer work in the new home
> fix more links

- index.md
I didn't check for everything that might need updating. I only changed the first paragraph because it's high-visibility.
> update gh-pages index links

- libvips/iofuncs/vips.c
This should fix #1151, makes the Windows `_O_TEMPORARY` bit work again and simplifies the logic so the default and fallback behaviour are both the same statement.
This doesn't deal with updating `image->filename` to use the `O_TMPFILE` filename. This means that further errors involving the file, if any, will still include `/tmp/vips-xxx.v` rather than the actual  `/tmp/random-os-assigned-filename`.
> Fallback to standard temp file if O_TMPFILE fails

- .travis.yml
https://blog.travis-ci.com/2018-11-08-xenial-release
Puts us a bit closer to building Debian/Ubuntu packages:
https://github.com/libvips/libvips/issues/987#issuecomment-426619628
> Use Ubuntu 16.04 on Travis

- .travis.yml
https://docs.travis-ci.com/user/reference/osx/#os-x-version
Let's see if this works :)
> Use latest Xcode for macOS builds

- libvips/foreign/vipspng.c
Using the latest code on the `master` branch I was seeing XMP metadata attached to PNG output even when `[strip]` was set.
This PR fixes the problem by moving all of the metadata-writing logic into a single `if( !strip ) { ... }` block. (Thanks to indentation the diff is a bit wonky so this change looks greater than it really is.)
> PNG writer: ensure XMP metadata is ignored when strip=TRUE

- libvips/arithmetic/complex.c
Hello,
I was struggling to convert complex images and found out there is a copy-paste mistake in the _vips_rect_ function. It's a very small PR to fix it 😄 
Great lib!
> Fixed vips_rect function

- libvips/foreign/vips2webp.c
This was reported in https://github.com/lovell/sharp/issues/1740
> Ensure WebP quality option is set for lossless

- cplusplus/Makefile.am
- cplusplus/VImage.cpp
- cplusplus/VInterpolate.cpp
- cplusplus/VStream.cpp
- cplusplus/gen-operators.py
- cplusplus/include/vips/Makefile.am
- cplusplus/include/vips/VImage8.h
- cplusplus/include/vips/VInterpolate8.h
- cplusplus/include/vips/VStream8.h
- cplusplus/include/vips/vips-operators.h
- cplusplus/include/vips/vips8
- cplusplus/vips-operators.cpp
> Add support for streaming in the C++ binding

- libvips/colour/XYZ2Lab.c
> Revert "Performance: improve XYZ to LAB conversion by ~15%"

- libvips/foreign/heifload.c
see https://github.com/libvips/libvips/issues/1574
> try to work around some broken heic images

- _posts/2020-09-01-libvips-for-webassembly.md
> Blog post for wasm-vips

- libvips/foreign/heifsave.c
This parameter is currently only used for AV1 compression.
By limiting to a 0-8 range we can provide a consistent API for both the aom and rav1e encoders. (The rav1e encoder accepts speed values of 9 and 10 but these use 64x64 blocks and fast key frame detection, which are concepts more relevant to low quality video than still images.)
As discussed in #1788
(The SVT-AV1 encoder, not yet available via libheif, also uses the same 0 slowest to 8 fastest range for its `EncoderMode` speed setting so this approach is hopefully future proof for that too.)
> libheif: expose speed parameter

- libvips/foreign/heifload.c
> fix heif load fails with 0 length metadata

- configure.ac
- libvips/conversion/composite.cpp
Fixes https://github.com/mstorsjo/llvm-mingw/issues/190.
> Ensure max_band vector is aligned on a 16-byte boundary

- cplusplus/include/vips/VImage8.h
- libvips/foreign/heifsave.c
Stumbled upon this while tinkering with AVIF
> Set correct description for heifsave argument

- .github/workflows/ci.yml
- configure.ac
- libvips/create/text.c
> CI: fix failures in macOS runner

- cplusplus/include/vips/VImage8.h
- cplusplus/vips-operators.cpp
- doc/function-list.xml
- libvips/foreign/niftiload.c
(Perhaps too early, will regenerate when new operators are added)
> Update C++ binding and function list

- configure.ac
- test/test-suite/test_foreign.py
- Include the rgba image in the teardown of `TestForeign`.
- Fix merge conflict.
> Fix CI failures

- libvips/include/vips/foreign.h
Just added the save function for jxl in foreign.h :
- vips_jxlsave
- vips_jxlsave_buffer
- vips_jxlsave_target
> added the jxl save functions to foreign.h

- libvips/foreign/heifload.c
Possible fix for https://oss-fuzz.com/testcase-detail/6561408631308288
> heifload: verify page dimensions are non-zero

- libvips/iofuncs/header.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37815 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37812
> Handle error values when guessing interpretation

- libvips/iofuncs/vips.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37820
> Ensure VIPS_CODING_ERROR is handled for vips images

- .github/workflows/ci.yml
- test/test_descriptors.c
See the individual commits for more details. This incorporates a few changes from PR #2361.
> CI: resolve failures and various improvements

- ChangeLog
- libvips/conversion/flatten.c
- libvips/foreign/cgifsave.c
- libvips/include/vips/header.h
- libvips/iofuncs/header.c
- test/test-suite/test_conversion.py
Fixes https://github.com/libvips/libvips/issues/2431
> Fix flatten clip

- cplusplus/VImage.cpp
- cplusplus/examples/test.cpp
- libvips/iofuncs/image.c
> Try the new target API first in `VImage::write_to_buffer`

- configure.ac
- libvips/foreign/jxlsave.c
See https://github.com/libvips/libvips/commit/21cdf22535e2ff6f070dc54c1e172eca02100d10#commitcomment-60291444
> allow libjxl 0.5

- autogen.sh
- configure.ac
> Make GOI dependency optional

- libvips/foreign/dzsave.c
> dzsave.c: Remove trailing comma from IIIF folder names

- libvips/Vips-8.0.metadata
- libvips/colour/LabQ2sRGB.c
- libvips/colour/XYZ2Lab.c
- libvips/colour/colourspace.c
- libvips/conversion/conversion.c
- libvips/conversion/switch.c
- libvips/conversion/transpose3d.c
- libvips/deprecated/im_gradcor.c
- libvips/deprecated/im_linreg.c
- libvips/foreign/foreign.c
- libvips/include/vips/interpolate.h
- libvips/include/vips/sbuf.h
- libvips/include/vips/semaphore.h
- libvips/include/vips/threadpool.h
- libvips/include/vips/transform.h
- libvips/iofuncs/header.c
- libvips/iofuncs/image.c
- libvips/iofuncs/object.c
- libvips/iofuncs/rect.c
- libvips/iofuncs/region.c
- libvips/iofuncs/reorder.c
- libvips/iofuncs/type.c
> Revert "Enhance the introspection support by fixing annotations"

- libvips/Vips-8.0.metadata
- libvips/colour/LabQ2sRGB.c
- libvips/colour/XYZ2Lab.c
- libvips/colour/colourspace.c
- libvips/foreign/foreign.c
- libvips/include/vips/interpolate.h
- libvips/include/vips/sbuf.h
- libvips/include/vips/semaphore.h
- libvips/include/vips/threadpool.h
- libvips/include/vips/transform.h
- libvips/iofuncs/header.c
- libvips/iofuncs/image.c
- libvips/iofuncs/object.c
- libvips/iofuncs/rect.c
- libvips/iofuncs/region.c
- libvips/iofuncs/reorder.c
- libvips/iofuncs/type.c
Also refine the .metadata file
> Enhance the introspection support by fixing annotations

- libvips/deprecated/package.c
- libvips/iofuncs/init.c
- tools/vips.c
See: https://github.com/libvips/libvips/commit/d80185060dd26eb1151b965f6f893ec076a480d0#r67247589.
> Fix building with -Dmodules=disabled

- libvips/deprecated/package.c
- libvips/iofuncs/init.c
This PR is to check whether CIFuzz is now working.
> Add missing annotations to #endif directives

- libvips/iofuncs/window.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45015
h/t @kleisauke
> window: delay setting ref count

- libvips/include/vips/dbuf.h
- libvips/include/vips/foreign.h
> Add missing funcs to public C API

- libvips/foreign/cgifsave.c
As of now, the `maxerror` parameter cannot be applied to animated GIFs with an active alpha channel.
Make it possible to detect cases where the alpha channel component of the current frame matches with the one from the frame before.
In these cases it is possible to use the transparency index for the `maxerror` optimization instead of for the alpha channel.
This pull request helps to further improve the file size of animated GIFs (for reference: #2576).
**Example:**
`$ vips copy test.gif[n=-1] old.gif[maxerror=16]`
`$ vips copy test.gif[n=-1] new.gif[maxerror=16]`
`$ gifsicle -O3 test.gif -o gifsicle.gif`
**Results:**
`du -h *.gif`
` 1.0M	new.gif`
` 5.8M	gifsicle.gif`
` 6.1M	test.gif`
` 9.8M	old.gif`
> cgifsave: allow to apply maxerror optimization to frames with alpha channel

- libvips/foreign/quantise.c
- libvips/foreign/quantise.h
- libvips/foreign/spngsave.c
Also, use the correct conditional directive in `spngsave`.
> quantise: fix styling

- ChangeLog
- libvips/foreign/jxlload.c
- libvips/foreign/jxlsave.c
see https://github.com/libvips/libvips/issues/2568
> add libjxl ICC and scRGB support

- libvips/foreign/nsgifload.c
Hey!
It'd be nice if `nsgifload` set the `palette-bit-depth` header as `pngload` does. It's pretty handy when saving the result.
If there is only a global palette, `palette-bit-depth` is set to its bit size. Otherwise, it's set to the biggest palette bit size.
> nsgifload: add "palette-bit-depth" header

- libvips/foreign/cgifsave.c
Hey!
I noticed that we can threshold alpha and check for alpha constraint in a single pass. This doesn't increase speed dramatically yet saves some milliseconds.
> cgifsave: theshold alpha and check alpha constraint in one pass

- doc/Cite.xml
- doc/Examples.xml
- doc/How-it-opens-files.xml
- doc/How-it-works.xml
- doc/Makefile.am
- doc/Making-image-pyramids.xml
- doc/Using-vipsthumbnail.xml
- doc/binding.md
- doc/binding.xml
- doc/libvips-from-C++.xml
- doc/meson.build
Since it's currently unavailable on RHEL 9, see:
https://bugzilla.redhat.com/show_bug.cgi?id=2089013
> doc: make pandoc optional

- _posts/2022-05-28-What's-new-in-8.13.md
> Rework "image resize quality improvements"-section

- libvips/foreign/dzsave.c
- libvips/iofuncs/target.c
See: https://github.com/libvips/libvips/issues/2878#issuecomment-1184199505.
> Fix `dzsave_target` for ZIP output

- libvips/include/vips/enumtemplate
- libvips/include/vips/enumtypes.c.in
- libvips/include/vips/enumtypes.h
- libvips/include/vips/enumtypes.h.in
- libvips/iofuncs/enumtemplate
- libvips/iofuncs/enumtypes.c
> Update `glib-mkenums` templates

- configure.ac
- meson.build
Also, increment revision in the Autotools build.
> Meson: bump version to 8.13.1

- test/test-suite/test_iofuncs.py
See: https://github.com/libvips/pyvips/pull/341
> test: remove `TestIofuncs::test_split7`

- meson.build
This was found using the `-Dauto_features=disabled` option.
> Fix summary when build with `-Dnifti=disabled`

- libvips/convolution/convf.c
Similar to the vector path of `vips_convi`.
> convf: bake the scale into the mask

- README.md
Hi there, 
I'm working on [Elixir bindings](https://github.com/akash-akya/vix) for libvips for some time now.
I think now it is good enough for people to try out. If possible, please take a look. Any type of feedback is most welcome. 
Thanks to the libvips design, especially immutability aspect of it. It is a perfect match for Elixir/Erlang.
> Updated README.md to add Elixir language bindings (Vix)

- libvips/create/text.c
Cairo also does this check internally in `cairo_image_surface_create_for_data()`, see:
https://github.com/freedesktop/cairo/blob/2cfd08664d080ff22e357a5feeca9bc29ec1823c/src/cairo-image-surface.c#L532-L533
Test case:
```bash
$ vips text x.png $(printf '=%.0s' {1..9999})
text: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```
Context: https://github.com/kleisauke/net-vips/issues/178.
> text: simplify check for 32k pixel limit

- libvips/include/vips/meson.build
- libvips/iofuncs/init.c
- libvips/resample/dummy2.cc
Also, remove a remnant of Autotools.
> Ensure `--vips-config` only prints build configuration

- examples/meson.build
- examples/use-vips-func.c
first one! lots to go from the samples
> copied invert example into examples

- libvips/Vips-8.0.metadata
- libvips/iofuncs/header.c
- libvips/iofuncs/type.c
Enhance the introspection coverage and increase Vala API coverage
> Introspection improvements

- libvips/foreign/jxlload.c
This partially reverts commit e88db2ce.
---
Tested with (libjxl was build with `-DCMAKE_BUILD_TYPE=Debug`):
```bash
$ curl -LO https://jpegxl.info/logo.jxl
$ vipsheader logo.jxl
logo.jxl: 1000x1000 uchar, 3 bands, srgb, jxlload
$ vips avg logo.jxl
109.279851
$ vips copy logo.jxl x.jxl
$ vipsheader x.jxl
x.jxl: 1000x1000 uchar, 3 bands, srgb, jxlload
$ vips avg x.jxl
109.716552
```
> jxlload: simplify rewinding

- libvips/foreign/tiffsave.c
> Fixed typo in tiffsave

- ChangeLog
- libvips/foreign/spngsave.c
- libvips/foreign/vipspng.c
- test/test-suite/test_foreign.py
the "Exif\0\0" header isn't being added and removed correctly
needs tests
> add exif support to png load/save

- cplusplus/examples/resize.cpp
> cplusplus: add missing argc check in resize example

- po/POTFILES.in
- po/README
> Regenerate POTFILES.in

- .gitattributes
> Mark profiles.c as a generated file

- ChangeLog
- libvips/foreign/cgifsave.c
see https://github.com/libvips/libvips/discussions/3211
> gifsave: deprecate reoptimise, add reuse

- doc/Making-image-pyramids.md
Doc patch to add IIIF creation info
> Adding layout: IIIF and IIIF3 to documentation

- ChangeLog
- libvips/convolution/sharpen.c
See https://github.com/lovell/sharp/issues/3521
Plus starts a new changelog for 8.15.
> sharpen: reduce max sigma to 10

- ChangeLog
- libvips/foreign/nsgifload.c
- test/test-suite/test_foreign.py
> nsgifload: add support for the interlaced flag

- libvips/iofuncs/init.c
Trivial backport of #3391 to [`8.14`](https://github.com/libvips/libvips/tree/8.14).
> Backport #3391 to 8.14

- cplusplus/include/vips/VImage8.h
- cplusplus/vips-operators.cpp
- doc/function-list.xml
- po/POTFILES.in
Incorporates the changes of commit 4d51821 and 3be16bb.
> Regenerate POTFILES.in, C++ binding and function list

- libvips/foreign/jxlsave.c
See: https://github.com/libjxl/libjxl/commit/f38074f8474d8fbaf424b930caeaf0fb486886f5
> jxlsave: sync quality-to-distance calculation with libjxl

- ChangeLog
Relating to commits 236313a and 462dc2d
> Add missing changelog entries for future v8.14.3

- libvips/colour/scRGB2XYZ.c
> scRGB2XYZ: re-sync with `vips_col_scRGB2XYZ`

- libvips/foreign/jpeg2vips.c
> jpeg2vips: simplify

- libvips/colour/icc_transform.c
default to 16 output for a 16-bit source image
> make icc_transform autoset depth

- ChangeLog
List of changes since 8.14.3:
- fix null-pointer dereference during svgload [kleisauke]
- heif{load,save}: guard against NULL strings [kleisauke]
- pdfiumload: fix rendering of pages with different sizes [DarthSim]
> v8.14.4 release proposal

- ChangeLog
- cplusplus/README.md
- cplusplus/VImage.cpp
- cplusplus/gen-operators.py
- cplusplus/include/vips/VConnection8.h
- cplusplus/include/vips/VImage8.h
- cplusplus/include/vips/VInterpolate8.h
- cplusplus/include/vips/VRegion8.h
- fuzz/gifsave_buffer_fuzzer.cc
- fuzz/jpegsave_buffer_fuzzer.cc
- fuzz/jpegsave_file_fuzzer.cc
- fuzz/mosaic_fuzzer.cc
- fuzz/pngsave_buffer_fuzzer.cc
- fuzz/sharpen_fuzzer.cc
- fuzz/smartcrop_fuzzer.cc
- fuzz/thumbnail_fuzzer.cc
- fuzz/webpsave_buffer_fuzzer.cc
- libvips/conversion/composite.cpp
- libvips/resample/reduceh.cpp
- libvips/resample/reducev.cpp
- meson.build
> Modernize code to C++11

- libvips/foreign/archive.c
This is not necessary; the ZIP format maintains a hierarchical structure.
---
On a somewhat tangent, I noticed that `dzsave` causes non-deterministic ZIP output if concurrency is > 1.
```bash
export LD_PRELOAD=/usr/lib64/faketime/libfaketime.so.1
export FAKETIME=$(date +"%Y-%m-%d %H:%M:%S")
vips black x.jpg 1000 1000
vips dzsave x.jpg x.szi --overlap 0 # --vips-concurrency=1
expected_sha256=$(sha256sum "x.szi" | awk '{ print $1 }')
for run in {1..5}; do
vips dzsave x.jpg x.szi --overlap 0 # --vips-concurrency=1
echo "$expected_sha256 x.szi" | sha256sum --check
done
```
```console
$ ./check-deterministic.sh 
x.szi: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
x.szi: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
x.szi: FAILED
sha256sum: WARNING: 1 computed …
```
> archive: avoid creating entries for each directory

- libvips/foreign/exif.c
Hey there! 👋
https://github.com/libvips/libvips/pull/3674 led to a bug in a case where an EXIF string contains an invalid UTF8 character:
1. When vips loads an EXIF string, its invalid characters are fixed here https://github.com/libvips/libvips/blob/c1e4d031fba77b76d4ce5a104ac8608ffa8f1f18/libvips/iofuncs/type.c#L566
2. When vips updates EXIF during saving, it compares the string from the image's meta with the output of `vips_exif_to_s`. And since vips fixed the string during the load, the strings become different, so vips replaces the EXIF string with one from the image's meta which includes a human-friendly representation, size, components number, etc.
This PR adds `g_utf8_make_valid` to `vips_exif_to_s` so it returns a fixed UTF8 string.
> Fix saving EXIF strings with invalid UTF8 encoding

- libvips/foreign/heifload.c
Hey there 👋
I found a nasty bug in `heifload` that leads to segfault in specific cases.
`heifload` allocates memory for meta (EXIF, XMP, etc) and ICC profile as local to the output image. If you close the image while having its descendants alive, you'll get a segfault when one of its descendants try to read ICC/meta.
Here's a reproduction example:
```c
#include <vips/vips.h>
int main( int argc, char *argv[] )  {
if( argc < 2 ) {
printf("src image path is missing\n");
return 1;
}
vips_init("test");
VipsImage *im1, *im2, *im3;
if (!(im1 = vips_image_new_from_file(argv[1], "access", VIPS_ACCESS_SEQUENTIAL, NULL))) {
printf("Failed to load image: %s", vips_error_buffer());
return 1;
}
im2 = vips_image_copy_memory(im1);
g_clear_object(&im1);
vips_icc_import(im2, &im3, NULL); …
```
> heifload: don't allocate meta/ICC memory as local to out

- meson.build
(My spare time will be limited during this release cycle)
> Bump version to 8.16 for the next release cycle

- libvips/foreign/pdf.c
- libvips/foreign/pdfiumload.c
Noticed on OSS-Fuzz: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libvips
> Fix build with PDFium

- doc/Developer-checklist.md
- doc/Developer-checklist.xml
- doc/libvips-docs.xml
- doc/meson.build
How about a "Developer checklist" chapter in the docs listing things you (ideally) should / should not do? It could gather up many common questions and issues we see many times in discussions.
I put in a few obvious ones, but we should add more. Any thoughts?
> start a `dev checklist`

- .github/workflows/ci.yml
- .github/workflows/cifuzz.yml
- .github/workflows/codespell.yml
- .github/workflows/lint.yml
> CI: various improvements

- libvips/iofuncs/source.c
Introduced in commit 6f7e43b
https://github.com/libvips/libvips/actions/runs/7603275230
> Fix typo to appease codespell

- doc/Cite.xml
- doc/Developer-checklist.md
- doc/Developer-checklist.xml
Sorry to ping you @kleisauke, I added some more dev notes, what do you think? You have much more experience around this than me! Can you think of any other related things we could add? 
The order of items should probably be adjusted now as well.
Maybe there should be a section just for web server image handling?
> add some more notes to the dev checklist

- fuzz/meson.build
- fuzz/oss_fuzz_build.sh
- meson.build
- meson_options.txt
See:
https://github.com/google/oss-fuzz/issues/2164
https://github.com/google/oss-fuzz/pull/2312
> OSS-Fuzz: migrate from `-lFuzzingEngine` to `$LIB_FUZZING_ENGINE`

- ChangeLog
- cplusplus/VImage.cpp
- cplusplus/include/vips/VImage8.h
thanks @Julianiolo
see https://github.com/libvips/libvips/issues/4026
Perhaps there are some more we could add? I didn't look very carefully.
> add some missing consts to the C++ API

- doc/Making-image-pyramids.md
- doc/Making-image-pyramids.xml
See commit: 39e75e07a227169d9c53f910f32c395e6992a5fa
> doc: `vips-properties.xml` is always written now

- fuzz/StandaloneFuzzTargetMain.c
See:
https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/fuzzer/standalone/StandaloneFuzzTargetMain.c
> fuzz: re-sync `StandaloneFuzzTargetMain.c` with LLVM

- libvips/foreign/webpsave.c
Non-functional change ... this just reformats and makes variable naming more consistent.
> Polish webpsave

- index.md
> Docs: migrate to SPDX license

- libvips/create/text.c
> text: reformat and polish

- doc/meson.build
- libvips/create/buildlut.c
- libvips/create/invertlut.c
Resolves: #3336.
Context: https://github.com/libvips/libvips/discussions/4146#discussioncomment-10626247.
> Fix markup in generated gtk-doc

- doc/Using-vipsthumbnail.md
- doc/Using-vipsthumbnail.xml
- Trim whitespace.
- "jpeg" / "JPG" = "JPEG"
- "--input-profile" = "--import-profile"
> Improve `vipsthumbnail` docs

- libvips/conversion/cache.c
- libvips/include/vips/almostdeprecated.h
- libvips/include/vips/enumtypes.c.in
- libvips/include/vips/meson.build
See the individual commits for more details. The `abi-compliance-checker` results are available at:
https://kleisauke.nl/compat_reports/vips/8.15.5-rc1_to_abi-compat/compat_report.html
https://kleisauke.nl/compat_reports/vips/8.15.5-rc1_to_master/compat_report.html
> Ensure ABI compatibility

- ChangeLog
Simplify, fix typos and avoid use of `@` (to avoid GitHub users being tagged in the release notes).
> Revise ChangeLog

- index.md
- install.md
And proofread/revise `install.md` a bit.
(this includes the changes from PR #4200)
> Re-sync gh-pages with `README.md`

- libvips/include/vips/vips7compat.h
Looks like I was testing on a old rebase. Sorry for that.
> fixup! Fix build with orc (#4198)

- ChangeLog
Context: https://github.com/libvips/ruby-vips/pull/407#issuecomment-2455424610.
> Revise ChangeLog note

- libvips/conversion/extract.c
Hi, thank you for this great project and amazing maintenance efforts!
When playing with `libvips` it wasn't obvious to me how to use `vips_extract_band` despite reading the docs, so I'm providing suggestion on making the relevant parts slightly clearer. I tried to guess the right places with code search, please let me know if I misplaced my changes!
> docs: clarify descriptions for vips_extract_band docs

- libvips/iofuncs/image.c
- libvips/iofuncs/init.c
- libvips/iofuncs/thread.c
- libvips/iofuncs/vector.cpp
- meson.build
- tools/vips.c
Non-functional change, see the individual commits for more details.
> Simplify Meson build definition

- ChangeLog
- libvips/foreign/heifsave.c
Possible approach for https://github.com/libvips/libvips/issues/4393
> heifsave: improve alpha channel detection

- libvips/deprecated/format.c
- libvips/deprecated/im_magick2vips.c
Tested using:
```console
$ vips im_magick2vips test/test-suite/images/MARBLES.BMP x.png
```
Context: https://github.com/libvips/libvips/pull/4375#issuecomment-2729738142.
> Fix vips7 compatibility layer for *magick

- doc/function-list.md
- doc/gen-function-list.py
- doc/rename.sed
- libvips/include/vips/foreign.h
Also, fix the remaining issues in `function-list.md`.
> Add C declaration for fitsload_source

- doc/fixup-load-as-ctor.py
- doc/function-list.md
- doc/meson.build
- doc/rename.sed
- libvips/iofuncs/connection.c
- libvips/iofuncs/header.c
Old: https://kleisauke.nl/vips-gi-docgen-old/func.jpegload.html
New: https://kleisauke.nl/vips-gi-docgen/ctor.Image.jpegload.html
Context: https://github.com/libvips/libvips/pull/4441#discussion_r2020935684.
> doc: make the load functions part of the image ctors

- libvips/foreign/openslideconnection.c
The first three commits are genuine fixes, the last two IMO are improvements but feel free to do with them as you'd like.
I've smoke-tested this but haven't exercised the cache code in a meaningful way.
> openslideconnection: fixes and some cleanups

- libvips/iofuncs/target.c
`vips_target_new_to_file()` used to immediately create the target file. If the filename was not actually used (eg. by `dzsave`), a stray file would be left behind.
This PR moves the file create to the first `_write()` operation.
See https://github.com/libvips/libvips/issues/4476
> lazy create of file targets

- ChangeLog
- cplusplus/include/vips/VImage8.h
- libvips/foreign/cairo.c
- libvips/foreign/svgload.c
- libvips/iofuncs/sink.c
- libvips/iofuncs/sinkmemory.c
- meson.build
> Minor formatting improvements

- ChangeLog
- examples/vipsprofile
- tools/meson.build
Most users won't find it useful. I added a few comments to vipsprofile as well.
> move `vipsprofile` into the examples/ directory

- po/de.po
- po/en_GB.po
Automated using `meson compile vips8.17-update-po`.
> i18n: refresh translations

- libvips/foreign/dcrawload.c
- libvips/foreign/foreign.c
- libvips/foreign/meson.build
- libvips/include/vips/foreign.h
- meson.build
- meson_options.txt
This PR adds support for basic libraw supports. I tried to do the bare minimum so I can get early feedback and build upon that.
Looking forward to your feedback.
> Add the basic support for loading RAW format files with libRAW

- ChangeLog
- libvips/morphology/morphology.c
- libvips/morphology/rank.c
- meson.build
only there for three years sigh
see https://github.com/libvips/libvips/issues/4609
> fix an off by one error in rank

- .gitattributes
> Mark libnsgif directory as vendored

- ChangeLog
- libvips/foreign/pdfiumload.c
In line with commit 0c7b65e1569f28ceee74c9b5e348edb3a18aff68.
Targets the 8.17 branch.
> pdfiumload: allow both dpi and scale to be set

- ChangeLog
- libvips/foreign/pdfiumload.c
In line with commit 0c7b65e1569f28ceee74c9b5e348edb3a18aff68.
> pdfiumload: allow both dpi and scale to be set (#4629)

- libvips/iofuncs/operation.c
Context: https://github.com/libvips/libvips/pull/4641#issuecomment-3210822736.
> operation: include "nocache" flag in class summary
